### ISSUE TITLE
Memory corruption related to TextOut

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#100]
When running with FastMM4 full debug mode, it's detected quite early, in InitExtTextOutDistance there is

    ReallocMem(FExtTextOutDistance, ALength * SizeOf(Integer));

but at the end of AdjustLastCharWidthAndRect there is 

    FExtTextOutDistance[ALength] := Max(LRealCharWidth, LNormalCharWidth);

which is out of bounds, I don't know if that last access is correct or not.

Besides that issue, it is not necessary to use manual allocation for FExtTextOutDistance a simple IntegerArray could do - and would provide optional bounds checking :)

tentative fix:
https://bitbucket.org/egrange/tbceditorxe/commits/1384dba8b5bfc9d7ab94b5aa86ab05d1e10bf440

**Comment by bonecode** [comment]
This is wrong: FExtTextOutDistance[ALength] := Max(LRealCharWidth, LNormalCharWidth);

Should be FExtTextOutDistance[ALength - 1] := Max(LRealCharWidth, LNormalCharWidth); because FExtTextOutDistance is zero-based.

I have lived in the belief that SetLength is slower than ReallocMem but I quess it's not...

**Comment by EricGrange** [comment]
I first assumed it was ALength-1, but when doing that, the rendering was broken...

So if ALength-1 is right, then there must be another bug somewhere else.

**Comment by EricGrange** [comment]
Also SetLength is not faster, the point is to only grow the array when it's not large enough, rather than all the time.

**Comment by bonecode** [comment]
Yes, there were also other ALength's before that row. I uploaded a fix for that. 

Ok, that is a good point. If Winapi.Windows.ExtTextOut doesn't care about the over length, then this is obviously a good fix...

**Comment by bonecode** [comment]
Fixed.
