### ISSUE TITLE
ShrinkAtWideGlyphs optimization

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#102]
https://bitbucket.org/egrange/tbceditorxe/commits/645e652d469c8398a4b5c6e7dfa686b591da5606

also reduces pressure on the memory manager a bit, but base trouble lies with the use of small temporary string throughout the tokenisation/parser

**Comment by EricGrange** [comment]
As illustration, here are profiler top spots for the System unit

![image](https://cloud.githubusercontent.com/assets/2197210/8001770/378060be-0b69-11e5-93f4-2e20acce3082.png)

this points to a lot of traffic in allocating, clearing and assigning small strings.

**Comment by bonecode** [comment]
Fixed, thanks.
