### ISSUE TITLE
TBCBaseEditor.ScanCodeFoldingRanges optimizations

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#104]
Use a local var for the LIsOneCharFolds scan

https://bitbucket.org/egrange/tbceditorxe/commits/681fcb2268a6af6e2ead9918722d333311edc8d6

A lot opportunities for similar optimization / code readability fix abound in  ScanCodeFoldingRanges.
This is also made worse then TCollection are used, as the GetItem is actually three nested calls (the GetItem of the overidden TCollection, the GetItem of TCollection, and the Get of TList)

Another optimization is a bit more involved but I think very necessary, as it's the cause of much slowdown when editing a large file with many fold regions (not when scrolling, but whenever you type) : all the lines are upper-cased by:

    LTextPtr := PChar(UpperCase(AStrings[LLine]));

besides being quite inefficient, this is also somewhat unsafe as the PChar is acquired on a temporary string.

A solution would be to not UpperCase the whole string, but just UpCase at the character level where necessary, and use a local variable to hold the character rather than deferring the PChar each time.

**Comment by bonecode** [comment]
Fixed.
