### ISSUE TITLE
How do you specify the element of bounding tokens of a sub-rule?

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#108]
for instance in

    blabla
    <script>
    some javascript
    </script>
    blabla

I would like to have " < script > " & " < /script > " use a different style from "some javascript"

**Comment by bonecode** [comment]
You can give a color element for a symbol, if that is what you're looking for...

<pre>
"KeyList": [
         {
	    "Type": "Symbol",
	    "Words": [
	        "\""
	    ],
	    "Attributes": {
	        "Element": "Symbol",
	        "ParentBackground": true
	    }
	}
]
</pre>

**Comment by EricGrange** [comment]
I mean something like this

![image](https://cloud.githubusercontent.com/assets/2197210/8031406/4b289e80-0dce-11e5-93e0-d4778e1cea07.png)

where the boundary tags have an element of their own, that is distinct from both the parent and the child range.

Also ideally there would be need for an "Open Token Close" and a "Close Token Open", so that in ' < script type="javascript" > ' the open token would be from < to >, and in the close token it would start at the first < preceding the token end, something like 

    "TokenRange": {
        "Open": "<script",
        "OpenClose": ">",
        "Close": "/script>",
        "CloseOpen": "<"
    },

yes, it gets a little less obvious  :)

**Comment by EricGrange** [comment]
I tried to tweak the CSS inclusion rules with a KeyList entry

							{
								"Name": "CSS Boundary",
								"Type": "ReservedWord",
								"Words": [
									"<style>"
								],
								"Attributes": {
									"Element": "ReservedWord",
									"ParentBackground": true
								}
							}


but this did not work, either in the parent JSON (HTML) or child (CSS), I guess that the whole token is part of neither?

**Comment by bonecode** [comment]
How about:

<pre>
{
    "Type": "Tag",
    "Attributes": {
        "Element": "ReservedWord",
        "UseParentElementForTokens": true
    },
    "Properties": {
        "CloseOnEol": true
    },
    "TokenRange": {
        "Open": "<",
        "Close": ">"
    },
    "SubRules": {
        "Range": [
            {
                "Type": "Comment",
                "Attributes": {
                    "Element": "Comment",
                    "ParentBackground": true
                },
                "TokenRange": {
                    "Open": "script",
                    "Close": "/script"
                }
            },
    ...
</pre>
