### ISSUE TITLE
MiniMap optimization

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#109]
As most of the slowdown in editing boils down to the minimap, up until it can be optimized to lightning fast speeds (which it may never be due to font rendering), an "optimization" could be to fake it ala Apple iOS, by turning off updates when they're unlikely to be noticed.

- always double-buffer the minimap internally
- update it no more than N times per second when typing, editing or selecting text, by updating the minimap buffer not in Paint, but in a timer event
- when scrolling on the minimap, bypass the timer

I had used this before when using a second SynEdit as minimap, this ensures that when typing/editing, you do not feel the slowdown of repainting the minimap. About 4 updates per second seemed quite enough when typing.

In Paint, you just arm the minimap repaint timer if it is not armed already, when the timer fires, you paint the minimap, and invalidate the editor (so the minimap update becomes visible).
If the timer is nearing its end and you're doing a Paint, then you can refresh the minimap and disarm the timer directly (this avoids the extra invalidate, and is mostly relevant when doing keyboard stuff like extending a selection, which results in a lot of repaints a couple dozen milliseconds apart).

Ideal but a lot more involved would be to repaint the minimap in a thread, but that would only be worth it with a deferred line renderer (this way only the deferred paint would take place in the thread, and there would be no need to have the whole lines and codefolding stuff be thread safe, you would perform the building of the deferred rendering graph in the main thread)

**Comment by bonecode** [comment]
Hmm, I don't feel any slowdown when typing with visible mini map. Feels exactly the same with or without the mini map. Mini map is also painted only if needed.

**Comment by EricGrange** [comment]
I notice it also when extending selection, with minimap on, the selection trails the mouse, with minimap off, the selection follows the mouse with no lag.

**Comment by bonecode** [comment]
I also just noticed that scrolling with the down/up key is lagging at times...

**Comment by bonecode** [comment]
I made a buffer for a minimap. Better or worse?

**Comment by EricGrange** [comment]
On the latest code, I do not have any lag anymore, even with FastMM full debug mode active :+1: 

That said, I suspect that simply buffering the minimap will not yield the best result, ideal would be to limit the number of times per second it's updated.

Also on the non-scientific test of scrolling wildly (grab the scrollbar and jerk it up down), the CPU usage of BCEditor goes to 100% of one core with minimap on, and about 70% with minimap off, while doing the same with the Delphi XE editor maxes at about 30% of one core - so there is still some room for improvement :)

**Comment by bonecode** [comment]
No doubt, there is a lot of code that can be optimized, refactored. and even removed as obsolete.

For the minimap scrolling I have a few ideas... there's also no need to paint all the lines over and over again. I will tackle that next.

**Comment by bonecode** [comment]
Closed. Nothing acute here. Minimap scrolling is on my todo list.
