### ISSUE TITLE
Access Violation in TBCEditorHighlighterJSONImporter.ImportCodeFoldingSkipRegions

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#110]
The first characters of LOpenToken & FCloseToken are accessed without checking if the string is empty, which results in an AV when it is.

In the case above I could trace it to a problem with file imports, after importing there is 

      { Skip duplicates }
      if LFoldRegions.SkipRegions.Contains(LOpenToken, LCloseToken) then
        Continue;

but for a file import, both LOpenToken & LCloseToken are empty, so the code proceeds to import the region, and kaboom. I guess it should just be "Continue".

Same issue exists in ImportCodeFoldingFoldRegions

**Comment by bonecode** [comment]
Fixed.
