### ISSUE TITLE
Prefixing of elements of sub-highlighters

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#112]
Currently all highlighters share the same element names, this is a request that a File inclusion be able to inject a prefix for the element names.

So if you use CSS.json directly f.i. its keywords would use the Attribute element (as currently), but if you include it with 

    {
        "File": "CSS.json",
        "AttributePrefix": "css"
    }

then the importer would inject "css" as prefix on elements, and it would use "cssAttribute" element (and "cssEditor" and "cssReservedWords", etc.) this way it becomes possible to apply different colors/style to css attributes and html attributes.

**Comment by bonecode** [comment]
Added ElementPrefix. Usage as you wished except AttributePrefix is obviously ElementPrefix.
