### ISSUE TITLE
TBCEditorAllCodeFoldingRanges.GetAllFoldRange optimization

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#113]
This fixes the range checking test for negative values, and since it does range checking tes, it can bypasses TList.Get

https://bitbucket.org/egrange/tbceditorxe/commits/8ba997e767f25f9012b9228fd9d9f7cd0894dff2

This has a noticeable effect on all loops over code folding ranges, and among other things halves the execution times for TBCBaseEditor.PaintGuides and TBCBaseEditor.CodeFoldingCollapsableFoldRangeForLine

(as a side note, I am not sure if returning a nil there is really appropriate)

**Comment by bonecode** [comment]
TList Get does exactly same range check and gets the value from pointer list. It's quite hard to see how this can make any difference?

**Comment by EricGrange** [comment]
Look at he CPU view  :)

The bottleneck is not just the extra call but also the stack juggling that comes because you have a method call. Basically that procedure spends its time juggling with the stack.

**Comment by bonecode** [comment]
Aaah, explanation approved :)

**Comment by bonecode** [comment]
Fixed.
