### ISSUE TITLE
Minimap drag is weird

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#114]
Clicking and dragging in the minimap results in a sort of infinite scrolling (try it on a large file like BCEditor.Editor.Base)

**Comment by bonecode** [comment]
I know, it is a feature. :) I kind of like it like that (scrolling slow or fast to a certain point) but maybe it should work like a scroll bar...

**Comment by EricGrange** [comment]
I kinda like how the one in SublimeText works (and I guess that's what people will expect)

**Comment by bonecode** [comment]
Yes, I think I have to admit my defeat. :D

**Comment by bonecode** [comment]
Fixed weirdness.
