### ISSUE TITLE
Paint RightMargin all at once

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#115]
Currently the right margin is painted line by line, then all at once beyond the last line.

AFAICT it should be possible to paint it all at once at the end of PaintLines

        if not AMinimap and LPaintRightMargin then
        begin
          Canvas.Pen.Color := FRightMargin.Colors.Edge;
          Canvas.MoveTo(LRightMarginPosition, 0);
          Canvas.LineTo(LRightMarginPosition, Height);
        end;

(noticed this as MoveTo/LineTo is starting to bubble up in the gdi32.dll bottlenecks)

**Comment by bonecode** [comment]
True, that is obsolete code once again. A few months ago there was a line painting with a different color after the right margin but I removed it.

**Comment by bonecode** [comment]
Fixed. That LPaintRightMargin variable is not needed anymore.
