### ISSUE TITLE
GetUncollapsedLineNumberDifference cache

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#116]
Partial optimization as I do not know when the cache should be flushed, I suppose every time the content, collapsing or the highlighter changes.
The cache will improve performance during scrolling, arrow key navigation & selection.

New field:

    FCollapsedLinesDifferenceCache: array of Integer;

To flush the cache, just set it to nil or SetLength to zero.

Given it's a sparse array, a TDictionnary could theoretically work fine, but the one in Generics.Collections is sluggish and uses a slow hash function, which negates most advantages of the cache... so a specialized dictionary would be required.

Updated method:

      function TBCBaseEditor.GetUncollapsedLineNumberDifference(ALine: Integer): Integer;
      var
        i: Integer;
        mid: Integer;
        LCodeFoldingRangeForLine: TBCEditorCodeFoldingRange;
        LCodeFoldingRange: TBCEditorCodeFoldingRange;
      begin
        LCodeFoldingRangeForLine := CodeFoldingRangeForLine(ALine);
        Result := 0;

        if ALine > High(FCollapsedLinesDifferenceCache) then
          SetLength(FCollapsedLinesDifferenceCache, ALine+1);

        Result := FCollapsedLinesDifferenceCache[ALine];
        if Result >0 then Exit(Result-1);

        for i := 0 to FAllCodeFoldingRanges.AllCount - 1 do
        begin
          LCodeFoldingRange := FAllCodeFoldingRanges[i];
          if LCodeFoldingRange.FromLine < ALine then
          begin
            if (LCodeFoldingRange <> LCodeFoldingRangeForLine) and LCodeFoldingRange.Collapsed and not LCodeFoldingRange.ParentCollapsed then
              Inc(Result, Max(LCodeFoldingRange.CollapsedLines.Count - 1, 0))
          end
          else
            Break;
        end;

        FCollapsedLinesDifferenceCache[ALine] := Result+1;
      end;

**Comment by bonecode** [comment]
I had a little different approach a little while ago where I calculated the difference for every line and GetUncollapsedLineNumberDifference would get the value simply from the array. I left it to simmer because there was some problem... I didn't prepare it in the right places. I will try it again... or use your solution.

**Comment by EricGrange** [comment]
Unless I'm mistaken in a large file (where performance matters) the values are needed for only a very small number of the lines, so I assumed that computing them all would be inefficient.
When testing (without a flush and without editing) the cache makes the method disappear from the bottleneck, the few times where a value is not cached appear to not matter.

**Comment by bonecode** [comment]
Unfortunately your algorithm does not work. If you collapse a fold, line numbers stay same.

**Comment by EricGrange** [comment]
Yes the cache needs to be purged when editing, collapsing or changing highlighter.

**Comment by bonecode** [comment]
I added purge into CodeFoldingCollapse, CodeFoldingUncollapse, LinesChanged, ClearCodeFolding, CodeFoldingUncollapseLevel, and InitCodeFolding. I hope that's enough.

**Comment by EricGrange** [comment]
Maybe you could add a "FlushCodeFolding" method or something like that, call it from all those places, and in its implementation, purge the cache.

This would create a single place where codefolding-related caches could purge themselves, and a single entry point where stuff that affects codefolding would have to call.
