### ISSUE TITLE
CodeFolding-safe way to change content by actual line/colon

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#117]
Is there a CodeFolding safe way to change content by actual (uncollapsed) line/colon?

The purpose is a symbol normalizer/renamer, when you edit or rename a symbol (variable, function, etc.), all the other occurences are normalized/renamed. This is done in a safe way through a parser/compiler, which works on the actual source (it's not a "stupid" search/replace, if you have several variables "v" and rename one, only the references to that particular "v" wiil be renamed, the others will be left untouched)

However at the moment there does not seem to be any codefolding-safe way to achieve that in the editor short of replacing the the whole editor content... which has many other side-effects.

**Comment by bonecode** [comment]
Can you give an example how have you tried to change the text? 

I've used SelectedText for example to change case. Which I just tested and it seems to have a little problem with multiple lines. :)

**Comment by EricGrange** [comment]
I have tried something like

    Editor.SelectionBeginPosition:=BCEditorTextPosition(col, line);
    Editor.SelectionEndPosition:=BCEditorTextPosition(col+Length(text), line);
    Editor.SelectedText:=text;

However if the location is collapsed, it replaces arbitrary text somewhere below the collapsed region.

Also using SelectedText affects the scroll position, and when doing undo, it goes back to the replaced text selected, rather than how things where originally.

(FWIW the replaced text above is was a single word, with no multilines)

**Comment by EricGrange** [comment]
Tried InsertBlock, it does worse so I opened a ticket for it.

**Comment by bonecode** [comment]
In your case SelectedText won't work because when the fold is collapsed Lines does not contain the text you want to select. It is stored into TBCEditorCodeFoldingRange's CollapsedLines.

**Comment by EricGrange** [comment]
Ok, for the moment I will turn off code folding, and then see if I can whip something.

In terms of spec, which position is guaranteed to always be expressed in terms of uncollapsed-lines?

**Comment by EricGrange** [comment]
Experimental map class that gives read/write access to uncollapsed lines

https://bitbucket.org/egrange/tbceditorxe/commits/c28ad73ad5cd6a9f1bacf9645e8e9663dc16a5ac

There are some glitches, like no undo, but it covers the basics of what I was after, it also behaves better (in terms of performance) than CreateUncollapsedLines when you do not need to access all lines.

Ideal would be being able to insert & delete lines as well, but that's more problematic to achieve given the hierarchic codefolding structure currently used. I guess the CodeFoldingRange should eventually be changed for a hierarchic tree to a skip list over an array of uncollapsed strings, this would also help with other methods like GetUncollapsedLineNumberDifference.

At some point LinesMap could be based on a TStrings, but basing on a TStrings is making promises for a lot of things (insert/delete among others).

**Comment by bonecode** [comment]
Hmm, interesting. Indeed the current structure is not optimal but at least it works (at some level). It is a pity that I currently have so little time for this. Some parts require longer focus and in short time I might do more damage than good...

**Comment by bonecode** [comment]
I quess this is done. :)
