### ISSUE TITLE
InsertBlock issues

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#118]
When trying to replace some content with InsertBlock, I ran into the following issue:

* with AddToUndoList, if you do an undo after an InsertBlock, you do not go back to the initial state, but to an intermediate state with the block deleted*
* InsertBlock seems to have no effect if the caret is beyond the last character of a line when InsertBlock is invoked

*: this was with multiple InsertBlock from within a Begin/EndUndoBlock

**Comment by bonecode** [comment]
I commented out crWhiteSpaceAdd. It seems obsolete. That caused the "intermediate state". 

The second case I couldn't repeat.
