### ISSUE TITLE
OnAfterPaintLine event

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#119]
Purpose: I would like to be able to paint something over some lines, for instance red error squigglies

I could brute-force myself in the Paint event, but that would fall apart once you start optimizing line painting to avoid painting the same lines again and again.

The event should provide a way to differentiate between main editor & minimap (f.i. to paint squigglies on the main editor, and something else or nothing for the minimap)

**Comment by bonecode** [comment]
Added OnAfterLinePaint event.
