### ISSUE TITLE
Incorrect background after a collapsed region

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#120]
This issue was introduced recently AFAICT

![image](https://cloud.githubusercontent.com/assets/2197210/8132435/0a558204-1122-11e5-8649-476859c07229.png)

collapse a region followed by a non empty line, click on that non-empty line, then click somewhere else, the line will get a background color

**Comment by bonecode** [comment]
Fixed PaintCodeFoldingCollapseMark. Really strange stuff. Canvas FrameRect call did somehow lock the brush color.
