### ISSUE TITLE
Code folding & cut

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#125]
Collapse the "begin" of a procedure, then select from after the "..." (on the same line as the "...") to the beginning of the declaration (left of "procedure"), cut.

The '...' will stay visible but moved below

Also if you paste it will not paste the whole procedure, but just up to the "begin".

**Comment by bonecode** [comment]
Yes, there are some issues. If the folded line is edited, it should uncollapse the fold.

**Comment by bonecode** [comment]
Fixed.
