### ISSUE TITLE
Block Indent + Folded lines + Undo = Crash

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#126]
Using BEditor.Editor.Base, fold the "initialization", select a line above and a line below, indent with tab, then hit ctrl+z, close the application -> memory leaks

If instead of closing you keep editing or repeat the operation, at some point it crashes with an AV or a memory overwrite detection error from FastMM4.

Also depending on what is selected, sometimes the folded regions will be unfolded when indenting/unindenting, and sometimes they are not.

**Comment by bonecode** [comment]
That memory leak should be fixed.
