### ISSUE TITLE
Assiging SelectedText deselects

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#130]
While the SelectedText should still be selected.

For instance when implementing a "duplicate selection" command:

    editor.SelectedText := editor.SelectedText + editor.SelectedText;

the duplicated selection is no longer selected.

**Comment by bonecode** [comment]
Fixed.

**Comment by bonecode** [comment]
The selection must be done by the "duplicate selection" command. 

<pre>
LBeginTextPosition := Editor.SelectionBeginPosition;
Editor.SelectedText := Editor.SelectedText + Editor.SelectedText;
Editor.SelectionBeginPosition := LBeginTextPosition;
Editor.SelectionEndPosition := Editor.CaretPosition;
</pre>
