### ISSUE TITLE
Build & install in XE6?

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/TBCEditor#131]
Has anyone been able to compile this editor in RAD Studio XE6? I'm running into a lot of issues. I think the install packages have a lot of bugs in them.

**Comment by bonecode** [comment]
Fixed. Better?

**Comment by AlbertWiersch** [comment]
Yes! Getting better. I opened the XE6 groupproj and successfully built BCEditorRXE6.bpl but I did get a warning that seems to be because I turned on C++ file generation:
[dcc32 Warning] BCEditor.Encoding.pas(1): W1025 Unsupported language feature: 'class constructor'

But when I tried to build BCEditorDXE6_XE6.bpl, I got this error:
[Fatal Error] Can't load package BCEditorDXE6_XE6.bpl.
The system cannot find the file specified

Filename naming error?

**Comment by bonecode** [comment]
Should be fixed.

**Comment by AlbertWiersch** [comment]
Thanks for the quick support! I'm getting closer (both projects build fine now) but when I try to install it I get an error that "The program can't start because BCEditorRXE6.bpl is missing from your computer.". Yet, that file is there in my folder "C:\AlC_Components_XE6\TBCEditor-master\Packages".

I added a library path to that folder in Tools->Options but it didn't seem to help.

Any ideas?

**Comment by bonecode** [comment]
I think the bpl should be built into a folder like C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl to be found...

**Comment by AlbertWiersch** [comment]
Components are installed! I haven't tried to use them yet though but they are installed. :)

I "hard-coded" the DCP output and Package output directories to something like what you suggested. Perhaps there is an environment variable or something this could be set to in the project? NOTE: I tried $(BDSUSERDIR)\BPL but it didn't work for some reason which is why I ended up putting the specific path in there and not using any environment variables.

Now on to the next problem.... I created a new VCL Forms application in C++Builder (I added "C:\AlC_Components_XE6\TBCEditor-master\Packages" to the system include path because that's where the hpp header files were). I dropped a TBCEditor component onto the form. It appeared. However, when I try to compile I get this error (and some other similar errors):

[bcc32 Error] BCEditor.MacroRecorder.hpp(233): E2062 Invalid indirection
  Full parser context
    Unit1.cpp(6): #include Unit1.h
    Unit1.h(11): #include C:\AlC_Components_XE6\TBCEditor-master\Packages\BCEditor.Editor.hpp
    BCEditor.Editor.hpp(18): #include C:\AlC_Components_XE6\TBCEditor-master\Packages\BCEditor.MacroRecorder.hpp
    BCEditor.MacroRecorder.hpp(31): namespace Bceditor
    BCEditor.MacroRecorder.hpp(33): namespace Macrorecorder
    BCEditor.MacroRecorder.hpp(200): class TBCBaseEditorMacroRecorder

The line in BCEDitor.MacroRecorder.hpp is:
	__property Bceditor::Editor::Keycommands::TBCEditorCommand RecordCommandID = {read=FCommandIDs[0], nodefault};

I think it has something to do with FCommandIDs[0]. I get similar errors on lines where FCommandIDs[1], FShortCuts[0], and FShortCuts[1] are used.

**Comment by AlbertWiersch** [comment]
UPDATE: I managed to compile by commenting out the offending lines in the header files. Perhaps something is being used that is not C++Builder compatible?

**Comment by bonecode** [comment]
Hmm, maybe a compatibility issue...

FCommandIDs and FShortCuts are getting their value by enumeration and items do not use values. For example:

<pre>
TBCEditorMacroCommand = (mcRecord, mcPlayback); 
FShortCuts: array [TBCEditorMacroCommand] of TShortCut;
FShortCuts[mcRecord]...
</pre>
