### ISSUE TITLE
Best way to handle a tabful of opened documents

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/TBCEditor#134]
My editor allows lots of files opened at one time with a tab control to select which document is currently being edited. This is easy with my current editor component (LMD SyntaxEdit) because the editor and sources are separate so I just have to set a new source for the editor component when the user switches documents using the tab control.

But BCEditor does not use separate sources so what is the best way to go about getting the same functionality? Is it to create an editor object for each open document and remove and add editor components from and to the underlying container component when the user switches documents?

**Comment by bonecode** [comment]
I have exactly same case with my EditBone application. Currently I am creating a frame for every tab which contains the editor component. There's no hassle with the state of the editor but of course it will use some memory... actually huge amount of memory at the moment. This memory consumption is now my main head ache. TBCEditorRange is the cause and it must be fixed before I can think anything else.

**Comment by AlbertWiersch** [comment]
Thanks. I hope the memory issue can be addressed quickly.

I'll try removing and adding the appropriate editor component to the tab control instead of a frame for each editor since that will make it easier for me to upgrade the editor component I have now... I hope that will work.

**Comment by bonecode** [comment]
Yes, that was caused by "array [Char] of". Where Char was a word-sized (16-bits) character type.

I will also remove my frames. Seems to use too much memory...
