### ISSUE TITLE
Crash when adding a line

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#135]
In a form OnCreate, just do

    ed := TBCEditor.Create(Self);
    ed.Lines.Add('hello');

it will crash in TBCEditorHighlighter.SetCurrentLine

(originally got it when trying to fill the editor with a TMemIniFile.GetStrings, which basically just clears then adds lines.

If the lines are specified as a whole with something like

    ed.Lines.Text := 'hello';

then there is no crash, so the issue is specifically related to adding a line.

**Comment by bonecode** [comment]
Fixed ListInserted.
