### ISSUE TITLE
Minimap dragging & dropping

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#137]
BCEditor burns the CPU when dragging & dropping minimap

**Comment by bonecode** [comment]
Caching minimap is on my todolist but the priority is not very high. Fix coming sooner or later. :)

**Comment by bonecode** [comment]
The CPU usage is now half what it was.

**Comment by noname00-pas** [comment]
Confirmed. The CPU usage is now half of what it was before.

**Comment by bonecode** [comment]
I am happy with this. If somebody wants to optimize this more, just do it. I need to spend my time for something that makes a living.
