### ISSUE TITLE
Syntax highlighting for contextual keywords

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#139]
Some keywords are contextual, for instance in Delphi read/write/index should only be bolded in property declarations (between a 'property' and its corresponding ';')

Currently this does not seem supported... or is it?

**Comment by bonecode** [comment]
Everything is possible. :)

<pre>
{
	"Properties": {
	    "CloseOnEndOfLine": true
	},
	"TokenRange": {
	    "Open": "property",
	    "Close": ";"
	},
	"SubRules": {
	   "KeyList": [
	      {
	          "Type": "ReservedWord",
	          "Words": [
	              "index"
	          ],
	          "Attributes": {
	              "Element": "ReservedWord",
	              "ParentBackground": true
	          }
	      }
	   ]
	}
},
</pre>

**Comment by EricGrange** [comment]
Cf Issue #142
