### ISSUE TITLE
Rescan highlighter ranges after highlighter is changed

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#140]
When the highlighter is changed (for instance by loading a new one), the ranges are not rescanned.

The RescanHighlighterRangesFrom is also not public, so a rescan cannot be manually requested.

**Comment by bonecode** [comment]
Can you give an example? I haven't noticed this. When I change the highlighter (for example in the demo or my editor), ranges are scanned.

**Comment by EricGrange** [comment]
In a Form OnCreate

    ed:=TBCEditor.Create(Self);
    ed.Align:=alClient;
    ed.Parent:=Self;

    hi:=ed.Highlighter;

    ed.LoadFromFile('BCEditor.Editor.Base.pas');
    ed.Lines.InsertText(1, '{'#13#10'hello'#13#10'}');

    hi.LoadFromFile('D:\GC\TBCEditorXE\Highlighters\Text.json');

    hi.LoadFromFile('D:\GC\TBCEditorXE\Highlighters\Object Pascal.json');

    hi.Colors.LoadFromFile('D:\GC\TBCEditorXE\Colors\Default.json');

After that the inserted multi-line comment will not be correctly highlighted.
If you then cut & paste it however, it will become correctly highlighted.

**Comment by bonecode** [comment]
Hmm, I think the problem is setting parent before the parent is actually created. But I check this later at home.

**Comment by EricGrange** [comment]
At this point the parent form has been created, but the issues is not related, it happens even if you place that code in a button click, or spread it over several button clicks (in my case the highlighter is changed later in the application execution, by user action)

**Comment by bonecode** [comment]
At some point I got exception from the paint, if I set the parent in OnCreate...but now I remember that I had a similar case when setting the sample text in the demo.

**Comment by bonecode** [comment]
Does it work, if you use Lines.Text instead of Lines.InsertText?
<pre>
Lines.Text := '{'#13#10'hello'#13#10'}';
</pre>

**Comment by bonecode** [comment]
I got the same issue repeated by changing highlighter with starting comment.

**Comment by bonecode** [comment]
Fixed.
