### ISSUE TITLE
Highlighter is wrong

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#141]
Test with this code:
procedure{Enter}
TBCEditor.... {There is no space at the beginning of this line}

![capture](https://cloud.githubusercontent.com/assets/7973218/8695947/c401ac50-2b12-11e5-9041-7152cfbb2c62.PNG)

**Comment by bonecode** [comment]
Fixed.

**Comment by noname00-pas** [comment]
Another wrong:
![capture](https://cloud.githubusercontent.com/assets/7973218/9400133/f7dc71bc-47e7-11e5-8082-74e4f832a74a.PNG)
