### ISSUE TITLE
Followup for Syntax highlighting for contextual keywords

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#142]
(Issue #139)

Two issues :)

First one is that default is *after* the semi-column, f.i.

    property Coords[Index: Integer] : Longint
             read GetCoord write SetCoord; default;

...can that be handled?

Second is that properties can span multiple lines, so 

    "Properties": {
        "CloseOnEndOfLine": true
    },

should be removed.

And bonus props for handling index correctly (which Delphi does not), the Index is the snippet above is not a keyword, it's a variable name, and should not be bolded, while it is a keyword in 

    property Left   : Longint Index 0 read GetCoord write SetCoord;

(snippets taken from http://www.delphibasics.co.uk/RTL.asp?Name=Default)

**Comment by bonecode** [comment]
1. Can default be then a regular keyword? It's outside property...; range.
2. Yes, for multiple lines that should be removed.

**Comment by bonecode** [comment]
I updated Object Pascal highlighter.
