### ISSUE TITLE
Breaking things announcement

### ISSUE THREAD

**Issue by bonecode** [bonecode/TBCEditor#143]
The time has come to break things. :) Currently code folding collapse and uncollapse are updating lines and causing problems which I have mostly fixed. But with this strategy for example undo/redo will never work perfectly, replace is not replacing text inside collapsed folds, editing lines is quite difficult, saving a file requires uncollapsing for all folds, etc. 

Changing this might take some time but must be done.

**Comment by sglienke** [comment]
May I ask why this is done in master and not in its own branch?

**Comment by bonecode** [comment]
This is still a beta, not a release. There is no point of making own branch because there has not yet been any satisfactorily working version. But getting there, please be patient.

**Comment by bonecode** [comment]
Big problems should be behind. Needs more testing thou.
