### ISSUE TITLE
Text selection does not work properly

### ISSUE THREAD

**Issue by subsol** [bonecode/TBCEditor#144]
Without wordwrap, there are various issues trying to select first line. Starting from the second line, selecting with mouse or shift+cursor keys looks good. Once wordwrap is switched on, it is impossible to select or navigate the text at all. The downloaded BCEditorComponentDemo32 does not show any of these problems.

Built with XE5.

Update: Created a blank new project, dropped TBCEditor on the form, and ran the project. Pressed Enter, the form freezes and starts burning the CPU.

On package installation, the file BCEditor.Editor.WordWrap.Helper.pas was missing, so I removed the reference from dpk. Is that the source of all issues?

Thank you.

**Comment by bonecode** [comment]
There are big changes going on and the current version is not yet stable. See: https://github.com/bonecode/TBCEditor/issues/143 The demo is almost a month old and then things were quite different.

I am going going through ExecuteCommand procedure step by step. Selection issues are fixed today.

I will remove the BCEditor.Editor.WordWrap.Helper.pas from the projects, it's not needed anymore.
