### ISSUE TITLE
Quickly switch highlighters

### ISSUE THREAD

**Issue by subsol** [bonecode/TBCEditor#145]
What is the best way to quickly switch highlighters? While navigating a grid, I want to show cell details in BCEditor, and these details vary - text, json, xml. Highlighter.LoadFromFile does not seem quite suitable here. If it makes sense, I would rather create 3 instances of TBCEditorHighlighter, and assign them when necessary.

Also, would be nice to have Highlighter.LoadFromStream, in case there is a need to embed json files as app resource data.

Thank you.

**Comment by bonecode** [comment]
See this issue: https://github.com/bonecode/TBCEditor/issues/59
<pre>
public
  function CreateFileStream(AFileName: string): TStream; virtual;
...
function TBCBaseEditor.CreateFileStream(AFileName: string): TStream;
begin
  Result := TFileStream.Create(GetHighlighterFileName(AFileName), fmOpenRead);
end;
</pre>
You can override CreateFileStream to handle the stream.
