### ISSUE TITLE
The ability to load a highlighter definition from a stream

### ISSUE THREAD

**Issue by NickRing** [bonecode/TBCEditor#157]
Having the ability to load a highlighter definition from a stream would allow user to store the highlighter definition in a resource and not worrying where to store it on the file system.

**Comment by bonecode** [comment]
You can override this:

function CreateFileStream(AFileName: string): TStream; virtual;

See https://github.com/bonecode/TBCEditor/issues/59.

**Comment by NickRing** [comment]
I would be nice not having to subclass the component, as sub-classing it would mean that I would have to get it on to the component palette so I can use it at design time.

I would prefer to be able to create a stream and pass that to the Editor to be read from.

**Comment by bonecode** [comment]
Problem with the LoadFromStream method is multi highlighters. Multi highlighters can include other files and then LoadFromStream is not a solution. I will add those LoadFromStream methods back and there will be a check that the highlighter can't be multi highlighter. 
```
"General":{
            "MultiHighlighter":true,
```

**Comment by NickRing** [comment]
Since I am quite new to TBCEditor (which is very nice BTW), what does "MultiHighlighter:true" allow/do?

**Comment by bonecode** [comment]
It allows to include ranges from other files into highlighter. See for example "HTML with Scripts.json":
```
...
"Range":[
  {
     "File":"PHP.json",
     "IncludeRange":"PHP"
  },
...
```
