### ISSUE TITLE
Highlighting doesn't always work

### ISSUE THREAD

**Issue by NickRing** [bonecode/TBCEditor#158]
When using the 'Object Pascal.json' highlighting and 'Default.json' colors, the following text only shows the top line as a comment and doesn't set the colour for the embedded comment:
```
(* test comment *)
procedure (* test comment *) hello;
begin
end;
```

**Comment by bonecode** [comment]
Horrible place to set a comment. :) Same problem with {}, //, quotes, etc. Will be fixed asap.

**Comment by NickRing** [comment]
Property seems to suffer from a similar issue also:
```
type
 TMyClass = class
    property Hello : string read (* comment *) write (* another comment *)
  end;
```

Yes - horrible places to have comments but these are semi-real world examples.

**Comment by bonecode** [comment]
Both cases fixed.
