### ISSUE TITLE
Multi-caret editing

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#169]
Please see here: http://uvviewsoft.com/synwrite/images/MCarets.gif

**Comment by bonecode** [comment]
Yes, multi caret and multiple selection are features on my todolist but after release.

**Comment by noname00-pas** [comment]
@bonecode Why don't you use Labels functionality for tagging issue? It will be easy to read & search.
![capture](https://cloud.githubusercontent.com/assets/7973218/10092607/968e3502-6372-11e5-8899-8178d9048e03.PNG)

**Comment by bonecode** [comment]
The world is full of great stuff but I will concentrate on the essentials. I am also not a big fan of github and maybe that's why I go there where the fence is down. :)

**Comment by bonecode** [comment]
Note to myself: Ctrl + Click adds a caret and Ctrl + Shift + Click adds multiple carets.

**Comment by bonecode** [comment]
Note to myself: Ctrl + Click adds a caret and Ctrl + Shift + Click adds multiple carets.

**Comment by bonecode** [comment]
Added.
