### ISSUE TITLE
Group undo (One step to doing undo "Replace All" action)

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#173]
When replacing, if there are many "Search text" (100 items) and then I want to revert the editor to the point before replacing, I need do undo 100 times. Need do undo by one step.

**Comment by bonecode** [comment]
Is the Undo.Options => uoGroupUndo = True?

**Comment by noname00-pas** [comment]
Oh, It was my mistake. You can close this issue! Thanks :-)
