### ISSUE TITLE
Collapsed range drawing

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#174]
Tested code:
<?php

function test {
}

BCEditor:
![1](https://cloud.githubusercontent.com/assets/7973218/9976934/2851d122-5f1f-11e5-9ea8-efee2b8e9b85.PNG)

Another program:
![2](https://cloud.githubusercontent.com/assets/7973218/9976933/0eedfada-5f1f-11e5-895c-db246bce91d5.PNG)

**Comment by bonecode** [comment]
Fixed.
