### ISSUE TITLE
Adding BCEditor to Delphinus Packagemanager

### ISSUE THREAD

**Issue by Memnarch** [bonecode/TBCEditor#185]
Hi,
BCEditor seems to be quite interesting and a possible successor to Synedit? Are you interested in adding it to the Delphinus Packagemanager?

Delphinus is a Packagemanager like GetIt but supports Delphi XE to Seattle. It runs directly from the IDE, too. All that's required is to add 2 files (one for general information and one which is the install script) to the Github-repository with an extra keyword in the readme. It is then automatically found by the clients for installation.

For more information: https://github.com/Memnarch/Delphinus/wiki
or simply ask me if you have any problems or questions

PS: If you add it to Delphinus, i encourage you to use the release feature of Github (after release if you want, instead of just changing the readme). This way, users get a notification when a new version is available and can update directly.

**Comment by bonecode** [comment]
Maybe after release. There are a still work to be done before the desirable quality is reached.

**Comment by Memnarch** [comment]
Okay :)
PS: this issue wasn't meant to be implemented right away, in case it looked like it, i am sorry.

**Comment by Memnarch** [comment]
Hi,
It seems you have made some great progress (and some releases ;) ). If you're interested i'd like to help you where ever i can.

**Comment by bonecode** [comment]
If you mean the package manager, I haven't thought about it much. I am moving to another city soon, so there are other things to think about. :)

**Comment by Memnarch** [comment]
Currently moving aswell ;)
