### ISSUE TITLE
CompletionProposal bug

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#186]
unit BCEditor.Editor.CompletionProposal.Form;

procedure TBCEditorCompletionProposalForm.RemoveKeyPressHandler;
var
  Editor: TBCBaseEditor;
begin
  Editor := Owner as TBCBaseEditor;
  if(Assigned(Editor))then      //by ning 20151002
    Editor.RemoveKeyPressHandler(EditorKeyPress);
end;
procedure TBCEditorCompletionProposalForm.HandleOnValidate(Sender: TObject; Shift: TShiftState; EndToken: Char);
var
  Editor: TBCBaseEditor;
  Value: string;
begin
  Editor := Owner as TBCBaseEditor;
  with Editor do
  begin
    BeginUpdate;
    BeginUndoBlock;
    try
      if FAdjustCompletionStart then
        //FCompletionStart := GetTextPosition(FCompletionStart, DisplayCaretY).Char;
        FCompletionStart := GetTextPosition(FCompletionStart, DisplayCaretY-1).Char;  //by ning 20151002
      //SelectionBeginPosition := GetTextPosition(FCompletionStart, DisplayCaretY);
      SelectionBeginPosition := GetTextPosition(FCompletionStart, DisplayCaretY-1);   //by ning 20151002
      if EndToken = BCEDITOR_NONE_CHAR then
        //SelectionEndPosition := GetTextPosition(WordEnd.Char, DisplayCaretY)
        SelectionEndPosition := GetTextPosition(WordEnd.Char, DisplayCaretY-1) //by ning 20151002
      else
        //SelectionEndPosition := GetTextPosition(DisplayCaretX, DisplayCaretY);
        SelectionEndPosition := GetTextPosition(DisplayCaretX, DisplayCaretY-1);  //by ning 20151002

      if FAssignedList.Count > Position then
        Value := FAssignedList[Position]
      else
        Value := SelectedText;

      if SelectedText <> Value then
        SelectedText := Value;

      with Editor do
      begin
        CancelCompletion;
        if CanFocus then
          SetFocus;
        EnsureCursorPositionVisible;
        TextCaretPosition := SelectionEndPosition;
        SelectionBeginPosition := TextCaretPosition;
      end;
    finally
      EndUndoBlock;
      EndUpdate;
    end;
  end;
end;

**Comment by bonecode** [comment]
Fixed.
