### ISSUE TITLE
Highlighters

### ISSUE THREAD

**Issue by bonecode** [bonecode/TBCEditor#187]
Following highlighters already requested:

<strike><i>ASP</i></strike>
Clojure
<strike><i>CoffeeScript</i></strike>
<strike><i>GLSL</i></strike>
<strike><i>Go</i></strike>
<strike><i>Groovy</i></strike>
Haskell
<strike><i>LaTeX</i></strike>
<strike><i>Lisp</i></strike>
Makefile
<strike><i>OCaml</i></strike>
<strike><i>Scala</i></strike>
<strike><i>TCL/TK</i></strike>
<strike><i>XSL</i></strike>
<strike><i>Windows PowerShell</i></strike>
YAML

If you create a new highlighter file and you want others to enjoy it, send it to lasse@bonecode.com.

**Comment by noname00-pas** [comment]
Rust, please!
https://www.rust-lang.org/

**Comment by bamlan** [comment]
unit BCEditor.Highlighter.JSONImporter;

//Line 488, if LJSONObject.Contains('CodeFolding') then 
//==>
//if LJSONObject.Contains('CompletionProposal') then

procedure TBCEditorHighlighterJSONImporter.ImportCompletionProposal(ACompletionProposalObject: TJsonObject);
var
  i: Integer;
  LSkipRegionItem: TBCEditorSkipRegionItem;
  LJsonDataValue: PJsonDataValue;
  LFileName: string;
  LEditor: TBCBaseEditor;
  LFileStream: TStream;
  LJSONObject: TJsonObject;
begin
  if not Assigned(ACompletionProposalObject) then
    Exit;
  { Skip regions }
  for i := 0 to ACompletionProposalObject['SkipRegion'].ArrayValue.Count - 1 do
  begin
    LJsonDataValue := ACompletionProposalObject['SkipRegion'].ArrayValue.Items[i];

    if FHighlighter.MultiHighlighter then
    begin
      { Multi highlighter code folding skip region include }
      LFileName := LJsonDataValue.ObjectValue['File'].Value;
      if LFileName <> '' then
      begin
        LEditor := FHighlighter.Editor as TBCBaseEditor;
        LFileStream := LEditor.CreateFileStream(LEditor.GetHighlighterFileName(LFileName));
        LJSONObject := TJsonObject.ParseFromStream(LFileStream) as TJsonObject;
        if Assigned(LJSONObject) then
        try
          //if LJSONObject.Contains('CodeFolding') then
          if LJSONObject.Contains('CompletionProposal') then
            ImportCompletionProposal(LJSONObject['CompletionProposal'].ObjectValue);
        finally
          LJSONObject.Free;
          LFileStream.Free;
        end;
      end;
      { Skip duplicates }
      if FHighlighter.CompletionProposalSkipRegions.Contains(LJsonDataValue.ObjectValue['OpenToken'].Value, LJsonDataValue.ObjectValue['CloseToken'].Value) then
        Continue;
    end;

    LSkipRegionItem := FHighlighter.CompletionProposalSkipRegions.Add(LJsonDataValue.ObjectValue['OpenToken'].Value,
      LJsonDataValue.ObjectValue['CloseToken'].Value);
    LSkipRegionItem.RegionType := StrToRegionType(LJsonDataValue.ObjectValue['RegionType'].Value);
    LSkipRegionItem.SkipEmptyChars := LJsonDataValue.ObjectValue.B['SkipEmptyChars'];
  end;
end;
