### ISSUE TITLE
Requirements to build

### ISSUE THREAD

**Issue by int0h** [bonecode/TBCEditor#189]
I'm very impressed by the demo. Could you please explain do I need to Buy and Install any proprietary software to use it? Because I've seen AlphaControlls in requirements in relative projects.

**Comment by bonecode** [comment]
See build requirements and conditional compilation from https://github.com/bonecode/TBCEditor/blob/master/README.md

AlphaSkins is not required to use the control. But the control has a conditional native support for it.
