### ISSUE TITLE
Clicking on minimap should bring the editor where clicked

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#19]
Clicking on minimap should bring the editor at the clicked line

Currently it just scrolls down/or up once.

Ideal would be if you could also drag the current view area in the minimap (same as scrollbar drag, just with a different scale and with preview)

**Comment by bonecode** [comment]
Yes, it should scroll at the clicked line and also dragging should work. I will check this, when I get home.

**Comment by EricGrange** [comment]
Actually it goes where clicked but it does so so slowly I thought it was not going there. And instantaneous jump rather than a scroll might help.

Dragging does not drag the visible area, it does a slow mouse-relative scrolling, similar to what the middle-button does in usual scrollable controls in Windows.
The behavior could be changed to dragging the zone (with scrolling only at the edges, like in Excel selection extension), and adding middle-button support to the code editor area for the mouse-relative scrolling.

**Comment by bonecode** [comment]
True, it works but has plenty of room for improvement. I will put this on my todolist.

**Comment by bonecode** [comment]
Fixed.
