### ISSUE TITLE
Use vcl styles

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#191]
vcl style has bug,only check the Form.BorderStyle property, without SetWindowLong settings,so

unit BCEditor.Editor.CompletionProposal.Form;

constructor TBCEditorCompletionProposalForm.Create(AOwner: TComponent);
{$IFDEF USE_ALPHASKINS}
var
  LSkinProvider: TsSkinProvider;
{$ENDIF}
begin
  CreateNew(AOwner);

  AddKeyPressHandler;

  ....
  
  //add by ning 20151004
  {$IFDEF USE_VCL_STYLES}
   Self.StyleElements := Self.StyleElements - [seBorder];
  {$ENDIF}
end;

**Comment by bonecode** [comment]
I am not happy with this proposal form at all. I did fix it a little but I need to investigate a better solution for it. I will put this on my todolist.

**Comment by bonecode** [comment]
Code folding hint and completion proposal forms are separated. Completion proposal still needs some love.
