### ISSUE TITLE
Horizontal scrolling when text contains multi-byte characters

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#194]
Text contains multi-byte char (for example: Chinese characters), horizontal scrolling, multi-byte character paint is not correct.
![bug1](https://cloud.githubusercontent.com/assets/6913934/10303503/bdfc8aee-6c46-11e5-820f-d5e5981678e6.png)
![bug2](https://cloud.githubusercontent.com/assets/6913934/10303514/cd4c6c44-6c46-11e5-99f5-53357bda8029.png)

**Comment by bamlan** [comment]
The effect of using SynEdit：
![bug3](https://cloud.githubusercontent.com/assets/6913934/10303630/a3b31846-6c47-11e5-99e4-42065394946c.PNG)

**Comment by bonecode** [comment]
Fixed.
