### ISSUE TITLE
Painting guide lines

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#197]
File: BCEditor.Editor.Base.pas
Cursor position: 10868:63
![capture](https://cloud.githubusercontent.com/assets/7973218/10356931/8fc68524-6da6-11e5-876d-d29a58e4e604.PNG)

**Comment by noname00-pas** [comment]
![capture](https://cloud.githubusercontent.com/assets/7973218/10356976/f16f28ee-6da6-11e5-82da-c556ad2e09f2.PNG)

**Comment by bonecode** [comment]
It was just bad indention.
