### ISSUE TITLE
[Object Pascal] Need an option to hide guild line for {$REGION} region

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#198]
![capture](https://cloud.githubusercontent.com/assets/7973218/10384362/4c8f597a-6e64-11e5-9b3d-f84826ec766d.PNG)

**Comment by bonecode** [comment]
I will add a "ShowGuideLine" property for the code folding fold region range (in the highlighter file). Indeed, not necessary to show the guide line there.

**Comment by bonecode** [comment]
Fixed.
