### ISSUE TITLE
Matching pair highlighting & minimap drawing

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#199]
Video: https://dropfile.to/mWsHC
The tested file: http://pastebin.com/wguwhwAL

**Comment by EricGrange** [comment]
Video file expired

**Comment by bonecode** [comment]
It was a painting issue but I couldn't repeat it. What was the Windows version?

**Comment by noname00-pas** [comment]
@bonecode I'm using Windows 7 Sp1 x64 and Classic theme

**Comment by bonecode** [comment]
Ok, thanks. I haven't tested classic theme for a long time but I will.

**Comment by noname00-pas** [comment]
Classic theme makes me remember the day when I start using Win95 :smiley: It's why I always use Classic theme :smile: 
Thanks for your support Classic theme :+1:

**Comment by bonecode** [comment]
Many times the classic theme brings out painting errors that would otherwise remain undetected.

**Comment by bonecode** [comment]
Do you still get this paint issue? Minimap invalidate is fixed.

**Comment by noname00-pas** [comment]
I still get the minimap painting issue on Windows with classic theme

**Comment by bonecode** [comment]
Ok, thanks. I will download a virtual machine for testing because Windows 10 does not have the classic theme.

**Comment by bonecode** [comment]
Fixed.
