### ISSUE TITLE
CompletionProposalForm and CodeFoldingHintForm activate to cause the OwnerForm deactivate

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#200]
add WMActivate Message procedure;

unit BCEditor.Editor.CodeFolding.Hint.Form;
unit BCEditor.Editor.CompletionProposal.Form;

TBCEditor...Form = class(TCustomForm)
protected
    ...
    procedure WMActivate (var Message: TWMActivate); message WM_ACTIVATE;
    ...
end;

procedure TBCEditor...Form.WMActivate(var Message: TWMActivate);
var
  ParentForm: TCustomForm;

  function GetOwnerForm(Sender:TComponent):TCustomForm;
  var
    LOwner:TComponent;
  begin
    Result:=nil;
    if(Assigned(Sender))then
    begin
      if(Sender is TCustomForm) then
        Exit(Sender as TCustomForm);

      LOwner := Sender;
      while Assigned(LOwner.Owner) do
      begin
        LOwner:=LOwner.Owner;
        if(LOwner is TCustomForm)then
          Exit(LOwner as TCustomForm);
      end;
    end;
  end;
begin
  if not (csDesigning in ComponentState) then
  begin
    ParentForm := GetOwnerForm(Owner);

    if Assigned(ParentForm) and ParentForm.HandleAllocated then
      SendMessage(ParentForm.Handle, WM_NCACTIVATE, Ord(Message.Active <> WA_INACTIVE), 0);
  end
  else
    inherited;
end;

**Comment by bonecode** [comment]
That is a hack. :) There was a much better solution. Fixed.

**Comment by bamlan** [comment]
Current update,Input WordBreakChar can not entered and hide CompletionProposalForm.

**Comment by bonecode** [comment]
Ah, that form is rubbish. I need to refactor the whole form.

**Comment by bonecode** [comment]
Fixed but needs more love later
