### ISSUE TITLE
TBCBaseEditor MouseDown proc bug, Cann't drag selection block

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#201]
ComputeCaret proc clear selection:

procedure TBCBaseEditor.MouseDown(Button: TMouseButton; Shift: TShiftState; X, Y: Integer);
...
  { Move caret }
  if (Button in [mbLeft, mbRight]) and (X > LLeftMarginWidth) then
  begin
    if Button = mbRight then
    begin
      if (coRightMouseClickMovesCaret in FCaret.Options) and
        (SelectionAvailable and not IsPointInSelection(DisplayToTextPosition(PixelsToRowColumn(X, Y))) or not SelectionAvailable) then
      begin
        InvalidateSelection;
        FSelectionEndPosition := FSelectionBeginPosition;
        ComputeCaret(X, Y);  
      end
      else
        Exit;
    end
    else
      ComputeCaret(X, Y);  //here clear current selected
  end;

  if Button = mbLeft then
  begin
    MouseCapture := True;
    { if mousedown occurred in selected block begin drag operation }
    Exclude(FStateFlags, sfWaitForDragging);
    if LWasSelected and (eoDragDropEditing in FOptions) and (X > LLeftMarginWidth) and
      (FSelection.Mode = smNormal) and IsPointInSelection(DisplayToTextPosition(PixelsToRowColumn(X, Y))) then
      LStartDrag := True
  end;
...
end;

procedure TBCBaseEditor.ComputeCaret(X, Y: Integer);
var
  LCaretNearestPosition: TBCEditorDisplayPosition;
begin
  LCaretNearestPosition := PixelsToNearestRowColumn(X, Y);
  LCaretNearestPosition.Row := MinMax(LCaretNearestPosition.Row, 1, FLineNumbersCount);
  if FWordWrap.Enabled then
    if FWordWrapLineLengths[LCaretNearestPosition.Row] <> 0 then
      LCaretNearestPosition.Column := MinMax(LCaretNearestPosition.Column, 1, FWordWrapLineLengths[LCaretNearestPosition.Row] + 1);
  //SetDisplayCaretPosition(LCaretNearestPosition);  //this call clear selected
  //Modified by Ning 2015/10/9
  SetDisplayCaretPosition(True,LCaretNearestPosition);
end;

**Comment by bonecode** [comment]
Thanks. I fixed also the caret when dragging.
