### ISSUE TITLE
GroupUndo should take mouse actions as "group breaker"

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#203]
For instance if you have 

    Foo - Bar

If you select "Foo" with a double-click, hit delete, then move the cursor to "Bar", then select with a double click, hit delete, then you need two ctrl+z to revert both deletes.

However if you double-click "Foo", hit delete, then double-click "Bar", hit delete, then a single ctrl+z will revert both deletes.

Ideally you should need two ctrl+z in both cases.

More generally mouse interactions (moving the cursor, selecting...) should account just like a keyboard arrow action in terms of undo grouping.

**Comment by bonecode** [comment]
Fixed.
