### ISSUE TITLE
Copy collapsed lines

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#204]
Starting for instance from

    if not Assigned(ScrollHintWindow) then
    begin
      ScrollHintWindow := THintWindow.Create(Application);
      ScrollHintWindow.DoubleBuffered := True;
    end;

If you collapse the "begin", you end up with "begin..end;".

If you then select that line, copy it then paste below, you will get the whole begin-end block.

However if you select from before the "b" of begin to after the ";", copy and paste, only the "begin" line will have been copied.

**Comment by bonecode** [comment]
Fixed.
