### ISSUE TITLE
Normal SelectionMode

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#205]
Currently none of the SelectionMode seem to match that of Delphi (and notepad++, and Word, and Chrome...), which is that if you select with the mouse from beyond the last character of a line, the selection begins from after the last character of that line.

**Comment by bonecode** [comment]
So it seems but when I think about this... should it start from somewhere where you didn't start it?

**Comment by EricGrange** [comment]
It works a bit contrarily to other editors however, as those are "virtual space", and starting from the last character makes it clear where you're really copying from (so as to differentiate cases where virtual space will be materialized, and those where they ill not be)

Also editing without soPastEndOfLine is impractical currently as the editor does not "remember" the column between lines: usually when moving down the arrow key f.i. and not soPastEndOfLine equivalent option, the editors make an effort to stick to the column f.i. in

    Here goes long |text 
    short
    some long text again

with | the initial carte position, when hitting arrow key down, editors will place the caret after short

    Here goes long text 
    short|
    some long text again

but if you hit down again it will return to the column it was in the first line:

    Here goes long text 
    short
    some long text |again

**Comment by bonecode** [comment]
Well, when things are not in the same way as other, it does not mean that they were right. :)

I think when soPastEndOfLine is true, it should work just like that. Also when soPastEndOfLine is true, the caret is sticking to the column. soPastEndOfLine = False is another story. But this can be a matter of taste and maybe dividing option to smaller pieces could help it...

**Comment by EricGrange** [comment]
Being "right" is not the issue, having to justify a behavior as being right to a whole world of users out there is the issue.
In practice, if it stays that way I will implement a kludge to get the behavior users expect, as doing so is a one-time task, while explaining/justifying the "right" behavior is a never-ending task :)

**Comment by bonecode** [comment]
"get the behavior users expect"... No, it should be: get the behavior that makes users happy. :) For example when I select text from a browser, I get angry before I even do it. :D What if Steve Jobs would have thought that "nah, let's just give them what they expect"... I think the world would be quite different nowadays. :)

But the solution for this could be to divide soPastEndOfLine option into smaller parts, if possible.

**Comment by bonecode** [comment]
Fixed.

You can now decide where the selection start by using soFromEndOfLine selection option. False means it start from where the caret is and True means it starts from end of line.
