### ISSUE TITLE
TBCEditorTextPosition first line convention

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#209]
TBCEditorTextPosition.Line seems to have changed convention, with the first line now having an index of 0 rather than 1.

Is the new convention going to "stick" or is there a risk of a reversal?

(got plenty of off-by-one errors, would prefer not to have to flip-flop again after fixing them)

**Comment by EricGrange** [comment]
Also see Issue #210

**Comment by bonecode** [comment]
Yes, text position is zero based and it goes with the Lines now and forever. Display position starts from 1 and it can vary depending on the code folding, word wrap, etc.

I did a huge refactoring during this summer. The rendering (paint) is now separated from the Lines.
