### ISSUE TITLE
Custom gutter/margin paint events

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#21]
Is there a way to perform custom gutter/margin paint? Or place custom markers?

The use case would be for breakpoints and "lines with compiled code" (same as blue dots in Delphi)

**Comment by bonecode** [comment]
There is a property Marks which can be used for custom markers but I have to admit that I haven't test it at all.

**Comment by EricGrange** [comment]
Thanks, seems to work fine so far I tested.
