### ISSUE TITLE
CodeFoldingCollapseAll does not fold all regions

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#212]
Tested file: https://dropfile.to/rA9W3
Result:

![capture](https://cloud.githubusercontent.com/assets/7973218/10509687/ba138392-7358-11e5-941f-d8cb7ff8aeed.PNG)

**Comment by bonecode** [comment]
function update_result_page code folding range does not include function update_info_page. So, it works like it should. I did also test the code folding collapse all procedure and it works.
