### ISSUE TITLE
FoldRangeLevel is wrong

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#213]
Test file: https://dropfile.to/XsJhD
Add CodeSideLogging unit to BCEditor.Editor.Base.pas
Add this code to procedure TBCBaseEditor.CodeFoldingCollapseLevel(ALevel: Integer);

    LCodeFoldingRange := FAllCodeFoldingRanges[i];
    // ---->
    CodeSite.Send('FromLine: ' + LCodeFoldingRange.FromLine.ToString() +
      ' - ToLine: ' + LCodeFoldingRange.ToLine.ToString() +
      ' - Level: ' + LCodeFoldingRange.FoldRangeLevel.ToString());
Open the test file, call FEditor.CodeFoldingCollapseLevel(1);

Result: 
![capture](https://cloud.githubusercontent.com/assets/7973218/10533785/6071db18-73f8-11e5-9b7e-290b5e03aff0.PNG)

**Comment by bonecode** [comment]
File expired.

**Comment by noname00-pas** [comment]
I reupload the file here: https://dropfile.to/sam32

**Comment by bonecode** [comment]
Levels are correct now.
