### ISSUE TITLE
End-key does not go end of the line on very long lines

### ISSUE THREAD

**Issue by mWaltari** [bonecode/TBCEditor#214]
![editbonelongline_endkey](https://cloud.githubusercontent.com/assets/4082975/10535916/8bbb6df6-73ef-11e5-84cc-0952b5168e17.gif)

In animated .gif you can see that end key goes into the middle of the line, then I press enter and repeat again until it goes up until the very end.

**Comment by bonecode** [comment]
Works when Options->Scroll->Autosize max width = Yes (Scroll.Options: soAutosizeMaxWidth). Otherwise scroll is limited to scroll.max width (default 1024).
