### ISSUE TITLE
Minimap drawing

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#219]
Please fill the background to the end of minimap:

![capture](https://cloud.githubusercontent.com/assets/7973218/10631867/e96f17c6-780a-11e5-9a16-7eedce15f99f.PNG)

**Comment by noname00-pas** [comment]
Please update  the scrollbar position when dragging minimap immediately.

**Comment by bonecode** [comment]
Obviously this is happening with the classic theme...

**Comment by noname00-pas** [comment]
1. 174 is the last row
2. It happens in both classic theme and aero

**Comment by bonecode** [comment]
And you were dragging the minimap? I can't get it repeated. Can you repeat that with any file?

**Comment by bonecode** [comment]
Now I got it. Just scroll at the end of the document and enable minimap.

**Comment by bonecode** [comment]
Fixed.
