### ISSUE TITLE
Mouse cursor should be margin's Cursor over left margin

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#22]
Current stays at IBeam (code area's cursor) for most of the margin, including over code folding controls.
Problematic code seems to be in BCEditor.Editor.Base line 6686:

    if not FMouseOverURI then
      if Cursor <> FCodeFolding.Hint.Cursor then { avoid cursor flickering when code folding hint is shown }
        SetCursor(Screen.Cursors[crIBeam]);

When the above is commented out, cursor is correct, and no flickering is visible AFAICT.

**Comment by bonecode** [comment]
Fixed.

procedure TBCBaseEditor.MouseMove(Shift: TShiftState; X, Y: Integer);
...
begin
  if LeftMargin.Bookmarks.Visible and (X < FLeftMargin.Width + FCodeFolding.Width) then
    Exit;
