### ISSUE TITLE
[Question] How to get token name at a position?

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#222]
How to get this value?
![capture](https://cloud.githubusercontent.com/assets/7973218/10689451/8afe785c-79a5-11e5-91b9-5fa36f7c72bb.PNG)

**Comment by bonecode** [comment]
A range name is not stored because there isn't any use for it. Do you need it for something?

**Comment by noname00-pas** [comment]
Yes, I do. Ex: if I wanna populate code completion for HTML with scripts highlighter, I need to know which range (PHP, javascript, css or HTML) is at the cursor to load exact items.

**Comment by bonecode** [comment]
A range name does not help much. Highlighter.GetCurrentRangeAttribute can give you the current range attribute object (see GetMatchingToken). You could use own color elements for PHP, Javascript, CSS, and HTML. But that is just a thought... I haven't really thought about that kind of code completion for multi-highlighter. Anyway, you need to do some own coding for that.
