### ISSUE TITLE
BCEditor.Utils's RoundCorrect is not correct

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#225]
By default Round() does a "banker's rounding" which statistically minimizes rounding bias.

RoundCorrect is apparently attempting to round 0.5 upward, which will introduce bias, and when it has any positive effect, it is actually a sign of numerical stability issues.

Most of the usage cases in TBCEditor fall under the numerical stability issues, and can be solved by removing RoundCorrect and using integer math directly most of the time (f.i. use "div 2" rather than "*0.5", etc.).

This also seems to fix some "wobblyness" in the searchmap.

**Comment by bonecode** [comment]
I agree, it was legacy junk.
