### ISSUE TITLE
"ParentBackground":true

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#226]
Would it be able to have an option to have ParentBackground set to true by default?

I'm using sub-highlighters, with region colors defined at the parent level, so basically all by Attributes end up with a "ParentBackground":true

**Comment by bonecode** [comment]
If ParentBackground attribute is true for all ranges, it will cause an infinite loop because parents are ranges too.

**Comment by EricGrange** [comment]
At the moment I have to set it for all SubRules, so this could be a property of the SubRules node, affecting all rules under it.

**Comment by bonecode** [comment]
Fixed ParentBackground default to True.
