### ISSUE TITLE
TBCEditor raises an exception

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#227]
PHP Highlighter
TBCEditor raises an exception when openning this file https://raw.githubusercontent.com/sergeche/emmet-sublime/master/emmet/emmet-app.js

File BCEditor.Editor.Base.pas
Line 3803
```pascal
LCodeFoldingRangeIndexList.Delete(LCodeFoldingRangeIndexList.Count - 1);
```
Should check 
```pascal
LCodeFoldingRangeIndexList.Count > 0
```

**Comment by bonecode** [comment]
Fixed, thanks.
