### ISSUE TITLE
TBCBaseEditor.GetWordAtMouse sensitivy

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#229]
On the following code:

    var xyz := 0;

GetWordAtMouse returns "xyz" only if the mouse is over the y or z, if it's over x, it returns nothing.

**Comment by bonecode** [comment]
Can't repeat this with the latest source. GetWordAtMouse calls GetWordAtRowColumn which was fixed. But it only had a bug with first line index...
