### ISSUE TITLE
Memory leaks from JsonDataObjects

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#23]
Highlighter's LoadFromFile & LoadColorsFromFile leak memory for strings in JsonDataObjects

FastMM log entries look like

    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseUtf8Bytes][2307]
    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseFromStream][2400]
    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseFromFile][2385]
    [BCEditor.Highlighter.JSONImporter.pas][BCEditor.Highlighter][BCEditor.Highlighter.JSONImporter.ImportColorsFromFile][616]

or

    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseUtf8Bytes][2307]
    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseFromStream][2400]
    [JsonDataObjects.pas][JsonDataObjects][JsonDataObjects.TJsonBaseObject.ParseFromFile][2385]
    [BCEditor.Highlighter.JSONImporter.pas][BCEditor.Highlighter][BCEditor.Highlighter.JSONImporter.ImportFromFile][585]

**Comment by bonecode** [comment]
Ouch, my bad. Fixed.
