### ISSUE TITLE
ParentBackground change seems to have broken parent coloring

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#230]
I am including sub-range with JSON like the following, since the latest commits, the CSS sections are no longer colored according to the Attributes.Element

					{
						"Name": "Style",
						"Type": "Tag",
						"Attributes": {
							"Element": "EditorBlue"
						},
						"TokenRange": {
							"Open": "<style",
							"Close": "/style>"
						},
						"SubRules": {
							"Range": [
								{
									"File": "CSS.json",
									"IncludeRange": "CSS"
								}
							]
						}
					},

**Comment by bonecode** [comment]
Because parent background is now True by default, you need to add "ParentBackground": false attribute for you range.

```
               {
                    "Name": "Style",
                    "Type": "Tag",
                    "Attributes": {
                        "Element": "EditorBlue",
                        "ParentBackground": false
                    },
                    "TokenRange": {
                        "Open": "<style",
                        "Close": "/style>"
                    },
                    "SubRules": {
                        "Range": [
                            {
                                "File": "CSS.json",
                                "IncludeRange": "CSS"
                            }
                        ]
                    }
                },
```
