### ISSUE TITLE
BCEditor.JsonDataObjects.pas error

### ISSUE THREAD

**Issue by andyzaharia** [bonecode/TBCEditor#233]
Hi,

There seems to be an error when trying to compile/install the package. An E2036 Variable required on line 3898.

TJsonBaseObject.StrToJSONStr(Writer.AppendIntro, FNames[0]); 

Tried to install it with Delphi XE7.

Thanks.

**Comment by bonecode** [comment]
Have you installed the update 1? 

- Delphi XE7: Update 1 required

**Comment by andyzaharia** [comment]
Awesome, thank you!
