### ISSUE TITLE
Do you plan to support Lazarus?

### ISSUE THREAD

**Issue by minias** [bonecode/TBCEditor#234]
Thank you for TBCEditor open source component .
Do you plan to support Lazarus?

**Comment by bonecode** [comment]
The answer is no as long as I have to use 8 hours a day to work for a living. These open source projects are developed in my very limited spare-time without any compensation but with pure love of programming. :) 

I check the Lazarus every now and then thou but I think it's not yet in the required level. Its code needs a lot of refactoring.

**Comment by minias** [comment]
Again more,
thank you for The open source projects without any compensation.
