### ISSUE TITLE
"Suppr" key does not update immediateley

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#235]
The "suppr" key (which deletes the character under the cursor) does not update the editor immediately (you need to hit another key for the visual feedback), it's missing a DoChange call I guess.

The "backspace" key (which delete the character left of the cursor) is not affected

**Comment by bonecode** [comment]
I can't repeat. Delete is deleting the character immediately.

**Comment by EricGrange** [comment]
Yes, still XE, I fixed it by adding a DoChange at the end of the "ecBackspace" case in TBCBaseEditor.ExecuteCommand

(ecDeleteChar case has one call to DoChange already, but ecBackspace does not)

**Comment by bonecode** [comment]
Indeed, there should be a DoChange call at line 10865.

**Comment by bonecode** [comment]
Fixed.
