### ISSUE TITLE
Paste from clipboard exception

### ISSUE THREAD

**Issue by andyzaharia** [bonecode/TBCEditor#237]
Sorry to report this, there seems to be an exception where doing a BCEditor.Clear; and a PastFromClipboard (via code or just CTRL+V) will crash in BCEditor.Lines (Line 616). 

The problem seems to be that one can actually move the caret to a line index bigger than 1 after clearing the editor. It looks like it the code tries to insert the text from the clipboard to a line index thats basically bigger than FCount which in turn triggers ListIndexOutOfBounds.

Looking right now into how to get this fixed :)

Thanks for this awesome component!

Later edit: Clearing the editor via BCEditor.Text := ''; seems to be a good workaround for this issue.

**Comment by andyzaharia** [comment]
Clearing editor via BCEditor.Text := ''; seems to be a good workaround for this issue.

**Comment by bonecode** [comment]
Can you tell how to repeat this?

**Comment by bonecode** [comment]
Fixed.
