### ISSUE TITLE
Word wrapping problem.

### ISSUE THREAD

**Issue by andyzaharia** [bonecode/TBCEditor#238]
Hi Lasse, Andy again :)

If you look at the attached screenshot you can see a problem with a few words where they do no wrap correctly and basically they end up partially on the end of the line and the entire text on the new line. 

![screenshot 2015-11-07 23 33 43](https://cloud.githubusercontent.com/assets/649034/11017475/dac8e1ce-85a8-11e5-84ed-6137378310d0.png)

To reproduce this, I basically used the demo program, I deleted all the text and did a paste from the following file:

https://dl.dropboxusercontent.com/u/9337037/sample%20codes.txt

Thank you!

**Comment by bonecode** [comment]
There seens to be a bug in the highlighter parser - tokens are not always parsed correctly and the length (Highlighter.GetTokenLength) of a token can not be trusted.

**Comment by andyzaharia** [comment]
I will drop this video screen capture here because I think this selection / scrolling issue is related to the initial bug.

https://dl.dropboxusercontent.com/u/9337037/TBCEditor-ScrollIssue.mov

I'm not sure what happens with the first line of the paragraph, but it looks like when the text is drawn the first line seems to be the wrong one.

**Comment by bonecode** [comment]
Thanks, I need to fix the parser first and see what happens after that. It now creates a lot of unnecessary objects and there are partial tokens. Painting is fixing this quite well because partial tokens are combined together but word wrap will tell the ugly truth...

**Comment by bonecode** [comment]
Fixed but needs more testing. Too tired today.

**Comment by andyzaharia** [comment]
Hi Lasse, I will grab the code and run some tests and I will let you know how it goes!
Thank you again!

**Comment by bonecode** [comment]
Sorry, the bug is back. :) I need to figure out how to fix it properly.

**Comment by bonecode** [comment]
Fixed.

**Comment by andyzaharia** [comment]
You are the master! :+1:
