### ISSUE TITLE
AV when pasting

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#241]
PHP highlighter
1. Open this file https://dropfile.to/MdgZp
2. Press Ctrl+A
3. Paste this text http://pastebin.com/wguwhwAL
=> Error

**Comment by bonecode** [comment]
Can't get repeated. Are you using the latest source or running the demo? Demo isn't build with the latest source.

**Comment by noname00-pas** [comment]
Tested with EditBone editor. Works properly. Closing.
