### ISSUE TITLE
Matchingpair highlighting error

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#243]
HTML with Scripts highlighter
Video: https://dropfile.to/7yt6C
Test file: http://pastebin.com/wguwhwAL

**Comment by bonecode** [comment]
Can't get repeated. Try with my EditBone editor.

**Comment by noname00-pas** [comment]
Tested with EditBone editor. The issue is still there.

**Comment by bonecode** [comment]
The bug seems to be caused by tabulator characters.

**Comment by bonecode** [comment]
Fixed.
