### ISSUE TITLE
Default search engine is not properly initialize

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#25]
By default search engine is set to seNormal but FSearchEngine is nil.

Can be worked around by setting another search engine

      editor.Search.Engine:=seWildCard;
      editor.Search.Engine:=seNormal;

**Comment by bonecode** [comment]
It should be assigned when the control is loaded:

6438: procedure TBCBaseEditor.Loaded;
6439: begin
...
6443:  SearchChanged(scEngineUpdate);

SearchChanged will call the AssignSearchEngine procedure. Try to set a break point there.

**Comment by EricGrange** [comment]
I am creating the component directly in code, so Loaded is never going to be called, since there is no DFM.

I am almost never using the form designer for complex components, as streaming from the DFM will not properly detect incompatible/changed property and event signatures (you need to manually open and change every form where the component is used), while the compiler will detect 100% of issues when everything is done in code.

**Comment by bonecode** [comment]
Ok, makes sense, kind of. I will try to get rid of this Loaded procedure.

**Comment by bonecode** [comment]
Fixed.
