### ISSUE TITLE
Minimap Paint

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#252]
unit BCEditor.Editor.Base;

procedure TBCBaseEditor.PaintTextLines(AClipRect: TRect; AFirstRow, ALastRow: Integer; AMinimap: Boolean);
....
begin
  ...
  { If there is anything visible below the last line, then fill this as well }
  LTokenRect := AClipRect;
  if AMinimap then
    //LTokenRect.Top := Min(FMinimap.VisibleLines, FLines.Count) * FMinimap.CharHeight
    LTokenRect.Top := Min(FMinimap.VisibleLines, FLineNumbersCount) * FMinimap.CharHeight
  else
    LTokenRect.Top := (ALastRow - TopLine + 1) * FLineHeight;

  if LTokenRect.Top < LTokenRect.Bottom then
  begin
    LBackgroundColor := FBackgroundColor;
    SetDrawingColors(False);
    Canvas.FillRect(LTokenRect);
  end;

  if not AMinimap then
    if FRightMargin.Visible then
    begin
      LRightMarginPosition := FTextOffset + FRightMargin.Position * FTextDrawer.CharWidth;
      if (LRightMarginPosition >= AClipRect.Left) and (LRightMarginPosition <= AClipRect.Right) then
      begin
        Canvas.Pen.Color := FRightMargin.Colors.Edge;
        Canvas.MoveTo(LRightMarginPosition, 0);
        Canvas.LineTo(LRightMarginPosition, Height);
      end;
    end;
end;

![fixed_minimap](https://cloud.githubusercontent.com/assets/6913934/11360560/a7182e8c-92c0-11e5-8e0a-bb75d2b86227.png)

**Comment by bonecode** [comment]
Can you explain what you are trying to fix?

**Comment by bamlan** [comment]
I'm sorry, I found this code by procedure PaintTextLines,but it has an error,please see the current issue.

**Comment by bonecode** [comment]
Ok, thanks. I will check that when I get home.

**Comment by bamlan** [comment]
:),Thanks for your good job.

**Comment by bonecode** [comment]
Fixed.
