### ISSUE TITLE
Text Insert

### ISSUE THREAD

**Issue by andyzaharia** [bonecode/TBCEditor#253]
Hi Lasse, sorry to create a new issue, but I wanted to ask whats the best way of inserting text at the current caret position. Basically right now I'm using the InsertBlock procedure but I get a lot of intermittent access violation exceptions and I wanted to ask if there is another way of inserting text at the current position. 

I'm a little bit rusty after getting back to Delphi from 6 years of iOS development :)

Thank you!

**Comment by bonecode** [comment]
No worries, the easiest way is to use SelectedText property. If there isn't a selection, then it is inserting text at the current caret position.

I will test that InsertBlock...

**Comment by andyzaharia** [comment]
Awesome, I will give that a try! 

Have an awesome day!

**Comment by bonecode** [comment]
This was also working:

Editor.InsertBlock(Editor.TextCaretPosition, Editor.TextCaretPosition, 'Test', False);

How did you call the InsertBlock?

**Comment by andyzaharia** [comment]
Oh, I was changing the end caret position. Basically adding the length of the string to the end position so that the end position will match the newly inserted string.

**Comment by bonecode** [comment]
That works also. It will replace the block with the text.

**Comment by andyzaharia** [comment]
Yes, using SelectedText fixed all my problems :) wondering where I was looking before using InsertBlock :D Thanks a lot and I owe you quite some :beers: :)
