### ISSUE TITLE
Minimap drag, scroll and focus

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#26]
Currently when clicking on the minimap, the clicked line is brought into view, but the minimap scroll position is always with the visible area in the middle.

Also when you attempt to drag-drop, this becomes a "scroll to top or bottom" operation, as the mouse will stay above the highlighted area, which will trigger another scroll, etc.

Ideally the highlighted area in the minimap should not always be dead-center, but where you dragged it, so you can use it as more than pretty scroll up/down button (check the drag behavior in SublimeText f.i.)

**Comment by bonecode** [comment]
Damn, I didn't test it properly with a large file. I see the problem and will fix it asap.

**Comment by bonecode** [comment]
Fixed. Much better but still needs a little adjustment. This is on my todolist and I'll get back to this later.
