### ISSUE TITLE
Invalid property value in XE4 IDE

### ISSUE THREAD

**Issue by raelb** [bonecode/TBCEditor#264]
I get an error with some components that have a property of Word type. E.g. Indy TIdSSLIOHandlerSocketOpenSSL, DefaultPort property, in dfm gets stored as:

  object IdSSLIOHandler: TIdSSLIOHandlerSocketOpenSSL
    MaxLineAction = maException
    Port = 0
    DefaultPort = ecNone
    SSLOptions.Mode = sslmUnassigned
    SSLOptions.VerifyMode = []
    SSLOptions.VerifyDepth = 0
    Left = 40
    Top = 88
  end

DefaultPort = ecNone, instead of 0. I traced this to BCEditor.Editor.KeyCommands.pas

type
  TBCEditorCommand = Word;

if I change to 
type
  TBCEditorCommand = type Word; // as in original SynEdit unit

This seems to solve the problem.

-Rael

**Comment by bonecode** [comment]
Ah, thanks, fixed.
