### ISSUE TITLE
Any shortcut keys will also open the CompletionProposal

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#265]
First, thank you very much for your TBEditor, which is best one I think:-).
I ever tried SyntexEdit, SynEdit, but your TBCEditor is really cool, 

When open BCEditor1.CompletionProposal.Options :=BCEditor1.CompletionProposal.Options + [cpoAutoInvoke]; 
Any shortcut keys Will open CompletionProposal window, for example Ctrl+C Ctrl+V

**Comment by bonecode** [comment]
Thanks, this is already fixed. 

https://github.com/bonecode/TBCEditor/commit/84247d172efef2e94524647d4ca0664de819bd39
