### ISSUE TITLE
BCEditor1.FindPrevious() should be called twice to search the previous text

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#266]
First, thank you very much for your TBEditor, which is best one I think:-).
I ever tried SyntexEdit, SynEdit, but your TBCEditor is really cool, 

For example FindText:
1. Hello aaaa
2. Hello bbbb
3. Hello cccc
When BCEditor1.Search.SearchText := 'Hello', it search the 1st line, and BCEditor1.FindNext()  search 2nd lines, 
the problem is when i wanna search back to 1st line, i called BCEditor1.FindPrevious() once, 
it still stays at the 2nd line, and the i call the BCEditor1.FindPrevious() again, it searches back to 1st line, 
I mean I should call BCEditor1.FindPrevious() twice to search back to previous text.

**Comment by bonecode** [comment]
Indeed, I need to refactor this.

**Comment by bonecode** [comment]
Ah, only minor bug. Fixed.

**Comment by hksoobe** [comment]
Thank you for your code, you are so so so fast




在 2015-12-18 23:55:14，"Lasse Rautiainen" <notifications@github.com> 写道：


Closed #266.
