### ISSUE TITLE
CodeFolding error

### ISSUE THREAD

**Issue by bamlan** [bonecode/TBCEditor#268]
Highlighter use "Object Pascal.json", Copy "BCEditor.Editor.Base.pas" all content to BCEditor, CodeFolding error on line 2244.
![bceditor_bug_codefolding](https://cloud.githubusercontent.com/assets/6913934/11974288/b8df79c4-a99d-11e5-92f0-169c4efa8b38.png)

**Comment by bonecode** [comment]
I tried that with my editor and no problem:

![image](https://cloud.githubusercontent.com/assets/11475177/11975353/9a656ce2-a975-11e5-8c41-6f8566719c64.png)

**Comment by bonecode** [comment]
Do you have the latest source and highlighters?

**Comment by bamlan** [comment]
I use git source latest version, In Delphi10S, Win10 x64 Chinese OS.

**Comment by bamlan** [comment]
I think this is `'` and `{}` conflicts, I delete `'` or add `'` or replace `{}` as a single line comment, code folding is correct.

**Comment by bamlan** [comment]
I found this because BCEditor.Options include [cfoFoldMultilineComments].

**Comment by bonecode** [comment]
Fixed.
