### ISSUE TITLE
soFromEndOfLine and soToEndOfLine do not work together

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#270]
When both options are set, alongside soPastEndOfLine, the editor should behave as Delphi's but does not.

When only soFromEndOfLine or soToEndOfLine is used, they work, but together the selection start is "weird": it will visually highlight from the end of the line to where the caret was at the time the selection was started.

**Comment by bonecode** [comment]
When both options are set, it works like the Sublime editor does. So, there must be an option soToEndOfLastLine.

**Comment by EricGrange** [comment]
I mean the weird selection highlight, for instance in:

![image](https://cloud.githubusercontent.com/assets/2197210/11990985/3405c000-aa15-11e5-8a89-7415b595c9d4.png)

there is a selection highlight that goes from the ';' to where the selection was started, instead of filling the whole width like it usually does.

Come to think of it the issue might actually be that soToEndOfLine affects two different things:
- that the selection stops at the end of the line where the mouse cursor is dragged
- that the selection *highlight* stops at the end of the lines rather than filling the width

**Comment by bonecode** [comment]
In Sublime that would look like:

![image](https://cloud.githubusercontent.com/assets/11475177/11993019/4d980648-aa35-11e5-98be-25d1d38024c3.png)

Like said, soToEndOfLine needs a little fix and there must be another option (for example soToEndOfLastLine) that means that the selection is done with the whole width until the end of it. Those options are mutually exclusive.

**Comment by bonecode** [comment]
Fixed.
