### ISSUE TITLE
Assigning SelectedText creates two undo entries

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#271]
When assigning something to SelectedText, a "blank" entry is add in the undo list.

For instance starting with "Hello" selected in

    Hello World

if you do a SelectText := "Byebye" the editor will change directly to 

    Byebye World

but if you do a ctrl+z, it will first  return to

     World

and then after a second ctrl+d you get back to "Hello World"

**Comment by bonecode** [comment]
Fixed.
