### ISSUE TITLE
Performance issues in TBCEditorHighlighter.GetTokenKind

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#272]
When working on a largish file (like BCEditor.Editor.Base), I am seeing rather high CPU usage that can be traced back to GetTokenKindTBCEditorHighlighter.GetTokenKind

* the GetToken call allocates a new String each time per token
* "if FCurrentRange.KeyList[i].KeyList[j]=LToken then" performs a double indirection and a string copy each time, in addition to a string comparison

The double indirection can be solved and the code clarified by using a variable for "FCurrentRange.KeyList[i]".

The inner loop may be simplified by setting the inner KeyList's Sorted property to true and using IndexOf (which will then perform a binary search).

The GetToken allocation can be alleviated in several ways, most efficient would be to return a record with a PChar & length, but then TStringList can no longer be used directly and has to be replaced with something else.
A less effective but simpler solution would be to use a GetToken procedure rather than a function (as in "procedure GetToken(var result : String)") and adjusting the passed string's length rather than reallocating anew. The LToken variable would have to be replaced by a Field. Since tokens are typically of similar short length, this should effectively simplify most of the re-allocations.

**Comment by bonecode** [comment]
Thanks, I agree in both cases. I did already fix the GetTokenKind.

**Comment by bonecode** [comment]
Fixed.

**Comment by EricGrange** [comment]
GetTokenKind does not compile, maybe

      for j := 0 to LCurrentRangeKeyList.KeyList.Count - 1 do
      if LCurrentRangeKeyList.KeyList[j].IndexOf(LToken) <> -1 then

should be

      if LCurrentRangeKeyList.KeyList.IndexOf(LToken) <> -1 then

?

**Comment by bonecode** [comment]
Nope, something else is wrong. Just tested and works like it should.

**Comment by bonecode** [comment]
Ah, I am blind, you're correct. Fixed.
