### ISSUE TITLE
Manually highlight/paint any part of text

### ISSUE THREAD

**Issue by int0h** [bonecode/TBCEditor#274]
Is there an opportunity to paint text with some styles (such as color, background, bold/italic etc.) somehow like this:
```Delphi
BCEditor1.SetTextAttributes(fromPos, toPos, color, bgcolor...);
// or even better
keyword := AddHighlightingClass(color, bgcolor... etc);
BCEditor1.SetTextClass(fromPos, toPos, keyword);
```
In other words I'd like to use the power of your project as text render, but also I'd like to have more freedom in choosing what to highlight and how. So I'd like to have a way to manually highlight text.

**Comment by bonecode** [comment]
You have total freedom to create any kind of highlighter and read it from a file or stream. Check out the JSON importer (BCEditor.Highlighter.JSONImporter.pas) and you get the idea how to add highlighter ranges in the code, if necessary.

**Comment by int0h** [comment]
I'm sorry I still cannot get it :( 

I'm going to describe my case in detail: I have a form with BCEditor and a Button for example.
And the BCEditor contains some code, let it be "Begin fun":
```javascript
Begin fun
```
And then by pressing the button I'd like to get part of that code painted red

```Delphi
Begin fun
```

Function for that can be smth like: 
```Delphi
// 0 - start of code fragment to paint
// 5 - length
// clRed - color
paint(0, 5, clRed);
```
Is it possible? I'd be happy if you gave me a little sample of code, that can do this thing.

**Comment by bonecode** [comment]
I added OnCustomTokenAttribute event for the control. Check, if that helps.

**Comment by int0h** [comment]
It's seems to be a solution for me! Thank you a lot!
