### ISSUE TITLE
Undo bug (with probable memory corruption)

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#276]
Start from the following content

    toto
    titi
    tata

select "titi", copy with ctrl+c, hit "end" to go to the end of the line, then space and paste with ctrl+v, the new content should be

    toto
    titi titi
    tata

no hit ctrl+z, all the content will be deleted, and sometimes the application will crash immediately or after a few other actions.

**Comment by bonecode** [comment]
Fixed undo/redo. Memory corruption I didn't get.
