### ISSUE TITLE
UndoBlock for many direct line modifications?

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#277]
What is the best way to have a "global undo block" for many direct line modifications?

I have some higher level editor functions for renaming/normalizing symbols, auto-formatting, template injections etc. which affect potentially many lines throughout the whole editor content, and I would like to have a way to place all those changes in an undo block automatically.

**Comment by bonecode** [comment]
BeginUndoBlock and EndUndoBlock should do the trick.

**Comment by EricGrange** [comment]
Already have them, but they have no impact AFAICT, neither for

    ed.BeginUndoBlock;
    ed.Lines[10] := 'hello';
    ed.Lines[11] := 'world';
    ed.EndUndoBlock;

nor 

   ed.BeginUndoBlock;
   ed.Lines.DeleteLines(15, 2);
   ed.Lines.Insert(15, 'hello');
   ed.Lines.Insert(16, 'hello');
   ed.EndUndoBlock;

**Comment by bonecode** [comment]
Ah, that is quite obvious because Lines do not add changes into the undo list. You must add the changes by yourself. Call UndoList.AddChange(...

**Comment by EricGrange** [comment]
An helper would be welcome, that AddChange call has a bit of scary list of parameters :)

Simple helpers to record changes for whole lines would be welcome (insert whole line, delete whole line & replace whole line).

**Comment by bonecode** [comment]
Added DeleteLines, InsertLine, and ReplaceLine helpers.

**Comment by EricGrange** [comment]
The helpers (at least ReplaceLine) do affect caret position.

For instance I have a refactor that goes from:

    var abc : Integer;
    ...
    abc := 1;

to 

    var aBc : Integer;
    ...
    aBc := 1;

the idea is that you change the declaration (on the first line), and the reference (on the last line) gets update automatically.

With UndoBlock & ReplaceLine, the undo now works, but the caret ends up on the last line when you perform an undo (while the user stayed on the first line when editing, and invoked the refactor with the caret on the first line).

Is there a way for an undo block or the helpers to preserve the caret position?

**Comment by bonecode** [comment]
Sure, UndoList.AddChange has a parameter for the caret position. I will check it...
