### ISSUE TITLE
Navigation to bookmark is dependent on origin location

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#279]
When navigating to a bookmark, the content displayed is dependent on where you called the bookmark from:
* when you start from many lines before the bookmark, it navigates to the bookmark centered in the editor.
* when you start from many lines after the bookmark, it navigates to the bookmark as the first line of the editor.

Ideally it should center on the bookmark all the time.

**Comment by bonecode** [comment]
Fixed.
