### ISSUE TITLE
Pairs matching bug

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#28]
Pairs matching fails to match the parenthesis in the following snippet

      if ((ACommand >= ecDeleteLastChar) and (ACommand < ecUndo)) or

Snippet is taken from line 10491 in BCEditor.Editor.Base which I used for testing, it also happens in other places in the same file, this is with the "Object Pascal.json" highlighter.

**Comment by bonecode** [comment]
Fixed.
