### ISSUE TITLE
soEntireScope does not seem to be honoured

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#282]
With soEntireScope set in the search options, the search does not seem to be able to find an occurence before the caret position.

Also soWraparound search option would be desirable (I was trying to use soEntireScope to mimic a wrap-around search)

Also having an explicit method "StartSearch" would be nice (it is not clear to me right now how to start, abort or restart a search, and when/how option changes are taken into account)

**Comment by bonecode** [comment]
Fixed.  

Search will start when you set the Search.SearchText.
