### ISSUE TITLE
Cosmetic bug in tab-to-indent

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#283]
When indenting the selection with tab, the first lines selection does not extend to the next line.

Starting from

![image](https://cloud.githubusercontent.com/assets/2197210/12117723/dc710982-b3c2-11e5-9982-e79a5e171e0c.png)

then after hitting tab

![image](https://cloud.githubusercontent.com/assets/2197210/12117734/ec53b9ee-b3c2-11e5-9f09-85e2f09e9910.png)

the rest of the line after "begin" should still be highlighted

**Comment by bonecode** [comment]
Note to myself: This happens when soToEndOfLastLine included in Selection.Options.

**Comment by bonecode** [comment]
Fixed.
