### ISSUE TITLE
Redo is not symmetric with undo for tab-to-indent

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#284]
If you tab to indent several times the same selection, then ctrl+z will undo tabs one at a time.
However if you redo ctrl+shift+z will re-indent all the tabs at once.

(I think undo is correct: tab to indent should not be grouped wrt undo)

**Comment by bonecode** [comment]
I can't repeat this. Are you using tabulator or Ctrl+U for indention?

**Comment by EricGrange** [comment]
I am using the tab key

Le 6 janv. 2016 4:52 PM, "Lasse Rautiainen" <notifications@github.com> a
écrit :

**Comment by bonecode** [comment]
Nope, can't repeat.

**Comment by EricGrange** [comment]
With your precompiled binaries:

- click on the line with "program HelloWorld;"
- hit home key
- hit tab key three times
- ctrl+z needs to be hit three times to bring back the original situation
- hit ctrl+shift+z once, the 3 tabs are regenerated

**Comment by bonecode** [comment]
Ah, ok, thanks. I tried with a selection and it works with that.

**Comment by EricGrange** [comment]
Ah sorry :(
Le 6 janv. 2016 6:07 PM, "Lasse Rautiainen" <notifications@github.com> a
écrit :

**Comment by bonecode** [comment]
Fixed.
