### ISSUE TITLE
Coloring of search highlight in the minimap is affected by visible lines 

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#285]
The color of search highlights in the minimap differs whether it's in the "visible lines" or not (the selection highlight does not).

Below are screenshots pf the minimap with a search, the only difference is a small scroll that moved the found occurence out of the visible lines.

While the difference is slight in screenshots, in practice it make a "pop effect" on the minimap when scrolling.

![image](https://cloud.githubusercontent.com/assets/2197210/12165449/5449d914-b51e-11e5-87e2-a7c6ff79a640.png)

![image](https://cloud.githubusercontent.com/assets/2197210/12165450/58faf24a-b51e-11e5-80d7-a1da9a102c66.png)

**Comment by bonecode** [comment]
Yes, this is a feature, looks better. The minimap indicator is now blended instead of setting background color. You can set the AlphaBlending value from Minimap.Indicator.AlphaBlending (by default it is 96).

See Sublime, it does exactly same.
