### ISSUE TITLE
Change request about Ctrl+Left/Right

### ISSUE THREAD

**Issue by FeelAirSlow** [bonecode/TBCEditor#286]
Hello.
I'm a regular user of Ctrl+Left/Right to navigate inside lines of code and Shift+Ctrl+Left/Right to select code portions for copy/replacement/deletion.
But I found difficult to use your convention (both for navigation & selection, Ctrl+Right moves the caret to the end of words, and Ctrl+Left moves the caret to the beginning of words).

May I suggest a modification ?
Don't change the selection : it's easy to select whole words.
But make the opposite for navigation (when Shift is not pressed, Ctrl+Right moves the caret to the beginning of words, and Ctrl+Left moves the caret to the end of words) : that's easy to go to beginning of words (more intuitive).

Thank you in advance.

**Comment by bonecode** [comment]
Fixed.
