### ISSUE TITLE
Clicking on search indicator

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#288]
When doing a search, there is a search indicator (between the minimap and the scrollbar), which shows the lines where occurrences have been found.

It would be nice that when clicking on it, the editor would go to the location, currently clicks are handled as if on the mini-map, which has a different scale.

Alternatively, having this indicator be moved to an overlay of the scrollbar would be even better (as Chrome does), this way it could be more visible without taking screen real-estate.

**Comment by bonecode** [comment]
That Chrome style scrollbar overlay was my first choice but there were problems with styles and skins because obviously those are also painting it over. But I will check, if I now know something I didn't back then... Learning - it is quite common when doing a lot of things. :)

**Comment by bonecode** [comment]
The Chrome scrollbar does now work well with large files.

![image](https://cloud.githubusercontent.com/assets/11475177/12357387/37302908-bbb0-11e5-8185-6cead71825b5.png)

**Comment by bonecode** [comment]
Fixed current solution. 

Search map could easily act like a scroll bar by adding buttons in both ends and the thumb moving. Maybe someday....
