### ISSUE TITLE
Support for synchronous edit

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#289]
This is a feature request to have a "synchronous edit" mode, somewhat like in Delphi, but possibly with a twist:
- either like Delphi you mark and area, and enter synchronous edit with the terms auto-detected
- or like an extension of the "similar terms" highlighter: you select a word, enter synchronous edit, and then the highlighted section behaves like an edit box, and changes to it get replicated

**Comment by EricGrange** [comment]
Nice work in progress :+1: 

Just a quick note about the ESC key which should exit syncedit.

**Comment by bonecode** [comment]
Good point. Undo is my current head ache... I was already close to refactor the whole undo system but took a deep breath instead. Sooner or later it has to be done thou...

**Comment by bonecode** [comment]
Esc and undo fixed. One line paste not working yet.

**Comment by bonecode** [comment]
There also seems to be a problem with synchronized words on the same line...

**Comment by bonecode** [comment]
Fixed.
