### ISSUE TITLE
ExecuteCommand within a BeginUndoBlock

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#293]
Multiple ExecuteCommand calls within a BeginUndoBlock do not seem to be grouped as one

**Comment by bonecode** [comment]
That is because there are undo blocks inside the ExecuteCommand. This procedure needs some refactoring.

**Comment by bonecode** [comment]
What were the commands you were calling? I tried a few and it works.

**Comment by EricGrange** [comment]
Commands are ecWordLeft, ecDeleteChar & ecChar

**Comment by bonecode** [comment]
Fixed.
