### ISSUE TITLE
Divide by zero in SetTopLine with Minimap

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#294]
When minimap is visible, SetTopLine does a division by zero when LDisplayLineCount = FVisibleLines

       if FMinimap.Visible and not FMinimap.Dragging then
          FMinimap.TopLine := Max(FTopLine - Abs(Trunc((FMinimap.VisibleLines - FVisibleLines) * (FTopLine / (LDisplayLineCount - FVisibleLines)))), 1);

**Comment by bonecode** [comment]
Fixed.
