### ISSUE TITLE
Key commands for toggling line comments and toggling block comments on a selection

### ISSUE THREAD

**Issue by beNative** [bonecode/TBCEditor#295]
Commenting/uncommenting could be done based on the single/multiline comment block settings in the highlighter definition.

**Comment by bonecode** [comment]
In Delphi and C++ Builder there is single line toggle with Ctrl + /. In Finnish layout it is Ctrl + ', in German layout it is Ctrl + #, in Italian it is Ctrl + ù etc. Hmm...

**Comment by EricGrange** [comment]
In SublimeText "ctrl+/" applies or removes single-line comments to the line selected (or caret), just like in Delphi and other editors.

"ctrl+shift+/" applies a block-comment to the selection.

The editor could use the comment style of the first multiline-comment-block rules it finds in the highlighter definition (to choose between {} & (* *) in Pascal f.i.), and ideally in the active highlighter for the current block.

For instance in a combined html+css highlighter definition a block comment in the html would generate a  but a block comment in the css would generate a /* */

**Comment by bonecode** [comment]
I will use Ctrl + / (for single-line) and Ctrl + Shift + / (for block). Using the current block highlighter in multi-highlighters requires too much time and effort which I don't have at the moment...

**Comment by beNative** [comment]
Awesome!
Thx

**Comment by bonecode** [comment]
Fixed. I hope the VK_OEM_2 is the correct virtual key for this. Atleast in Finnish keyboard layout it is.

**Comment by EricGrange** [comment]
Rather than hard-code the VK, you can use something like (VkKeyScan('/') and $FF) to grab the actual keycode for '/'

**Comment by bonecode** [comment]
Nope, does not work. Result is 55 and should be 191 with my layout.
