### ISSUE TITLE
HTML export for the highlighters

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#296]
Having a way to export highlighted code to HTML would be a nice feature, ideally exporting the syntax-highlighted code to HTML in one file, and the colors into a matching CSS.

The goal would be to generate snippets for documentation purposes, using just one set of highlighting rules (BCEDitor's) rather than have to mimic it (which is time consuming and error-prone)

Additionally, you could use the HTML export as a way of implementing automated testing for the syntax highlighters rules & parser (a test would be comprised of some code, a highlighter, and the HTML output as expected result)

**Comment by bonecode** [comment]
Added ExportToHTML procedure. CSS is internal because it can be also saved into a stream.

**Comment by EricGrange** [comment]
Awesome!
