### ISSUE TITLE
CodeFolding and multiline strings

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#297]
CodeFolding SkipRegion has a RegionType, which can be "String" or "MultiLine".

However I have multiline stings... which one should be used? I have tried both, but both had some glitches (foldable regions being detected or not, cleared or not, depending on the sequence of keystrokes and editor content, I guess there is some interaction with the highlighter)

**Comment by bonecode** [comment]
TBCEditorSkipRegionItemTypes are ritUnspecified, ritString, ritMultiLineComment, and ritSingleLineComment.

Actually ritSingleLineComment is the only one that matters at the moment. It skips a single line. Other types will add an open token into skip list. 

Give an example of the case, I can check if there's a bug.

**Comment by EricGrange** [comment]
For instance with the following code using the DWScript highlighter (https://bitbucket.org/egrange/tbceditorxe/src/26215fd65d465b04f886bf2ea63328bac6652efe/Highlighters/DWScript.json?at=master&fileviewer=file-view-default)

    var a := "
        begin
          // whatever
        end;
        ";

it will initially appear correctly with no folding for the begin/end in the multiline string.

Add a second quote " to close the string on the first line so you have

    var a :=  ""

the begin/end will get a folding (as expected), and will no longer be highlighted as a string, but if you now remove that quote, the highlight will revert to a string, but the folding will still be there (while it should not)

**Comment by bonecode** [comment]
Ah, seems to be code fodling rescanning issue.

**Comment by bonecode** [comment]
Should be fixed.
