### ISSUE TITLE
Undo/Redo triggers an OnChange

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#298]
Actions that result in an undo/redo (like navigating with the keyboard) will trigger an OnChange

It should ideally only trigger if the Editor content was actually changed, Undo/Redo change notification could get their own events (though usually that's not necessary, corresponding actions need to update through ActionList OnUpdate or similar events, as undo/redo capability is affected by focused components, as well as a variety of other things like ReadOnly statuses, etc.)

**Comment by bonecode** [comment]
I think, I fixed this yesterday but I will check.

**Comment by EricGrange** [comment]
Indeed, I was behind the latest commits :)
