### ISSUE TITLE
Expose GetWordAtRowColumn

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#30]
Currently only WordAtCursor & WordAtPointer are available.

Ideally a GetWordAtPixels would be nice (could also come through Issue #29 and GetWordAtRowColumn)

**Comment by bonecode** [comment]
Fixed.

**Comment by EricGrange** [comment]
Thanks for GetWordAtPixels!

But GetWordAtRowColumn is still private.

I use it for a "fuzzy" lookup, that picks the nearest word left of the cursor that may be after non-identifiers chars.
