### ISSUE TITLE
FoldRegion multiple CloseToken

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#301]
Would it be possible to have an option for a fold region to have multiple possible close tokens?

("multiple" as in "alternative")

**Comment by bonecode** [comment]
Everything is possible but where it is needed? Maybe there is an alternative solution.

**Comment by EricGrange** [comment]
Got two use case right now:

* a lambda syntax which optionally aborts with an  "=>" or ends with an "end"
* SQL which matches start transaction with either commit or savepoint (or rollback)

**Comment by bonecode** [comment]
Use AlternativeClose property. See for example Object Pascal highlighter:

```
{
  "Type": "Method",
  "Attributes": {
     "Element": "MethodName"
  },
  "Properties": {
     "AlternativeClose": [
        "(",
        "'",
        "/",
        "{"
     ]
  },
  "TokenRange": {
     "Open": "procedure",
     "Close": ";"
  },
...
},
```

**Comment by EricGrange** [comment]
Hmm, I was meaning for CodeFolding / Ranges / FoldRegion

**Comment by bonecode** [comment]
Aah, indeed. :D Not the first time to mix highlighter and code folding together...

Well, you need to 

- add another CloseToken into TBCEditorCodeFoldingRegion
- add import into TBCEditorHighlighterJSONImporter.ImportCodeFoldingFoldRegion
- fix RegionItemsClose procedure in ScanCodeFoldingRanges 

I try to keep the control as common as possible, there is no need for this at the moment.
