### ISSUE TITLE
Report line number on JSON parsing error

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#303]
Currently there is just an exception, without any details.

If the error is at the JSON level, one can use JSONLint (though it's not too convenient), but when the error is in the structure, it requires stepping through the Delphi debugger...

**Comment by bonecode** [comment]
Well, I wash my hands of this issue. :) You can ask Andy to fix exceptions in JsonDataObjects.

https://github.com/ahausladen/JsonDataObjects

**Comment by EricGrange** [comment]
Andy's side is the one for JSON errors (those that JSONLint can be used for), but the other Delphi errors are on your side, and something could be provided (like the hierarchy)
