### ISSUE TITLE
Error when doing undo after toggling comment

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#307]
Please see the GIF:
![2016-01-30_19-39-58](https://cloud.githubusercontent.com/assets/7973218/12695721/9bf150ee-c789-11e5-99eb-12b1964227da.gif)
Please upload the BCEditor.Highlighter.Comments.pas file.

Thx

**Comment by bonecode** [comment]
Fixed a few bugs.

I don't agree with this:
```
//// Hello World in Pascal <= wrong
```
Does not make a sense to comment comments.
