### ISSUE TITLE
Undo corrupting content

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#309]
While I do not yet have a reproduce-able case, there have been several occurrences (reported by users, or that happened to me) where the undo would would end up corrupting content, typically by reverting changes on the wrong line.

This is after regular editing though a lot of it (typing, select, copy-paste... no special stuff like SyncEdit, line comments or code folding).

**Comment by EricGrange** [comment]
This seems to be related to undo depth somehow, while not corrupting anything here is a reproduceable odd behavior: starting from a newly opened editor with a loaded file, if you click somewhere, then hit undo, nothing happens.
But if you click somewhere (location 1), move the arrow right, then click somewhere else, then undo will return to location 1.

**Comment by EricGrange** [comment]
Another odd behavior, starting from a newly opened editor with a loaded file, click somewhere, move the arrow, then select (with the mouse) another location, hit undo, nothing happens.

**Comment by bonecode** [comment]
I don't doubt at all that in some cases there might be a problem with the current undo system. It is painful to use. Needs refactoring for sure.

I added crCaret undo event into mouse down.

**Comment by bonecode** [comment]
Now it seems to be better.

**Comment by bonecode** [comment]
Artificial respiration done. :)
