### ISSUE TITLE
Expose SearchText method

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#31]
Required so that a search UI can display how many items were found (and display a visual cue if none were found)

Ideally FindNext/FindPrevious should also return a boolean depending on whether something was found or not (rather than just an optional beep).

**Comment by bonecode** [comment]
I think there already is property SearchCount because I am using it in the demo... maybe SearchResultCount could be a specific name. 

I have time tonight to fix these things...

**Comment by EricGrange** [comment]
Ok, seen it, I was not sure what it was for since the SearchString property alongside it does nothing.

Using a set of search properties to control search does not work too well, for instance if you search for "dummy" with a given set of options, change the options (f.i. to extend scope, sensitivity...), then updating the search is a bit convoluted: changing the search options will not restart the search (and should not), and assignin SearchText will do nothing since the text did not change, so you have to clear the SearchText then re-assign the old one.

It might be simpler (in terms of use) to have SearchText as read-only property, and set be able to set it through a method that always initiates a search. An overload could be used to pass a new SearchOptions set alongside.

Maybe having the SearchOptions readonly would be preferable as well, as it would avoid any discrepency between the current search result sets and the search options?

**Comment by bonecode** [comment]
Fixed. No damage done if the SearchText can be set even it has not changed. I will be using this property in my editor.

![image](https://cloud.githubusercontent.com/assets/11475177/7591742/341a3e52-f8d8-11e4-8820-a34f1469f119.png)
