### ISSUE TITLE
Select, click then undo

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#311]
New editor, file loaded, select something, click elsewhere, then undo.

It goes back to the selection, but no further (should be able to go back to the initial state with nothing selected)

**Comment by bonecode** [comment]
Ah, fu... it does something really stupid now, if selection is done by moving mouse button down. Undo event adding in the mouse events was a bad idea. :/ I will check this when I get home.

**Comment by bonecode** [comment]
Now it is better but not perfect. I will test this more.

**Comment by bonecode** [comment]
I added undo (top) and redo (bottom) lists into my demo and I see where problems are... I did write 'test' and undo it. Undo list is actually almost empty at that point but I didn't refresh the list.

![image](https://cloud.githubusercontent.com/assets/11475177/12786376/7a89d31e-ca99-11e5-8a8a-e7c1081f5e06.png)

**Comment by bonecode** [comment]
I think I got this. Let me know, if there is anything weird.

**Comment by EricGrange** [comment]
That particular case is fixed, but I just got a massive memory corruption after doing an undo (editor displayed messed up text, then app crashed), it was after a bunch of editing... so no way to reproduce, but the undo action is still quite "dangerous"

**Comment by bonecode** [comment]
I haven't got such but I was wondering if you're using these InsertLine, DeleteLines, and ReplaceLine procedures? I need to test those (and all commands) with my demo project.

**Comment by EricGrange** [comment]
No I was not in that particular case, it was lots of keyboard input, arrow
key navigation, mouse selection, cut and paste, delete blocks with delete
key (I was reorganizing stuff in a source file)
Le 5 févr. 2016 6:20 PM, "Lasse Rautiainen" <notifications@github.com> a
écrit :

**Comment by EricGrange** [comment]
I will try to make a "Monkey test" today, sending random commands to the editor, hopefully, monkey will succeed at providing a reproduceable test case where human failed :)

**Comment by EricGrange** [comment]
Ok, Monkey just succeeded, opening new ticket
