### ISSUE TITLE
Make a list of associated file extensions a property of a highlighter definition

### ISSUE THREAD

**Issue by beNative** [bonecode/TBCEditor#312]
A nice feature would be if you could specify one or more common file extensions in the highlighter definition file. This information can be used to propose a list of file extensions when you want to save the editor content if it has a highlighter associated with it.

**Comment by bonecode** [comment]
I thought about this carefully about a year ago and I chose not to add file extensions into highlighter files. I think it is not the right place for several reasons - speed (when you use many or all of them), customization, maintenance, etc. But you can always add those by yourself, if you need.
