### ISSUE TITLE
Breakpoints and executable lines

### ISSUE THREAD

**Issue by CristianPeta** [bonecode/TBCEditor#313]
I need to mark executable lines with blue dots and breakpoints with red.
What are the options?

**Comment by bonecode** [comment]
Check these events:

- OnCustomLineColors
- OnAfterBookmarkPanelPaint
- OnBeforeBookmarkPanelPaint
- OnBookmarkPanelLinePaint
- etc.

I think there should be everything you need for it. Check also PaintLeftMargin procedure and you get the idea in which order it is painted. You can also use your own bookmarks.
