### ISSUE TITLE
Beware auto formater

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#314]
While merging your latest commits, it looks like you used an auto-formater which made the code quite less readable by moving line comments on the next line (so the comment is now after what it's supposed to comment), or by adding new lines in long expressions in the wrong places.

For instance, before, semantic and easy to follow

    if FMinimap.Visible and (
      (FMinimap.Align = maRight) and (LCursorPoint.X > ClientRect.Right-ClientRect.Left - FMinimap.GetWidth - FSearch.Map.GetWidth) or
      (FMinimap.Align = maLeft) and (LCursorPoint.X < FMinimap.GetWidth) ) then

after, it's just messy

    if FMinimap.Visible and ((FMinimap.Align = maRight) and (LCursorPoint.X > ClientRect.Width - FMinimap.GetWidth
      - FSearch.Map.GetWidth) or (FMinimap.Align = maLeft) and (LCursorPoint.X < FMinimap.GetWidth)) then

**Comment by bonecode** [comment]
I know, it was accident. Fixed.
