### ISSUE TITLE
Fail dcc TBCEditorDemo.dpr: sSkinProvider File not found

### ISSUE THREAD

**Issue by pult** [bonecode/TBCEditor#320]
...>dcc TBCEditorDemo.dpr
...
...BCComponents\Source\BCComponent.SkinProvider.pas(6) Fatal: F1026 File not found: 'sSkinProvider.dcu'

**Comment by bonecode** [comment]
Demo source build requires <a href="http://www.alphaskins.com/">AlphaSkins</a> and <a href="http://www.ehlib.com/">EhLib</a>.
