### ISSUE TITLE
TBCEditor XE3 modified files

### ISSUE THREAD

**Issue by pult** [bonecode/TBCEditor#321]
TBCEditor-master-2016-02-10_for_XE3.7z
http://rghost.ru/7TLMFKdrv

**Comment by bonecode** [comment]
* Delphi versions XE4, XE5, XE6, XE7, XE8, and Seattle are supported 
* Delphi XE7: Update 1 required
* C++ Builder XE7, XE8, and Seattle are supported

I am not interested in any other versions.
