### ISSUE TITLE
Another Monkey workload

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#329]
Fails at RandSeed = 683

```
   cCommands : array [0..11] of Integer = (
      ecLeft, ecRight, ecUp, ecDown,
      ecChar,
      ecCopy, ecCut, ecPaste,
      ecDeleteChar, ecBackspace, ecUndo, ecRedo
      );
   cNBActions = 5;
```

**Comment by EricGrange** [comment]
and yet another workload without clipboard but more actions, fails at seed = 241

   cCommands : array [0..8] of Integer = (
      ecLeft, ecRight, ecUp, ecDown,
      ecChar,
      ecDeleteChar, ecBackspace, ecUndo, ecRedo
      );
   cNBActions = 10;

**Comment by bonecode** [comment]
Fixed both issues.
