### ISSUE TITLE
Avoid opening the clipboard multiple times

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#331]
Currently BCEditor clipboard methods open the clipboard many times during the course of cut/copy/paste, which increases the risk of locks (Issue #330), and also it opens the risk of inconsistencies as the clipboard may have changed between the locks.

Ideally the clipboard should be opened (aka locked) only once during a cut/copy/paste. Some functions also perform implicit locks (like Clipboard.HasFormat), so TBCBaseEditor.DoPasteFromClipboard effectively does half a dozen locks (two in CanPaste, three for HasFormat calls, a couple explicit Open, plus GetClipboardText)

All clipboard methods are affected to some degree AFAICT.

Should probably be solved alongside with Issue #330 by having some unified method to open/lock the clipboard, and making all the other methods aware of that lock, so that f.i. GetClipboardText will not re-open the clipboard if it's already open.

**Comment by bonecode** [comment]
Duplicate https://github.com/bonecode/TBCEditor/issues/331
