### ISSUE TITLE
Find and Replace can go very wrong when tabs are used

### ISSUE THREAD

**Issue by kurrat** [bonecode/TBCEditor#332]
Find and Replace (both in the TBCEditor component and in the BoneCode standalone editor) can screw up the text during a replace action. To reproduce the situation create a text containing the following where space and tab stand for the respective characters

**one** _space_ **one** _space_ **one**
_tab_ **one** _tab_ **one** _tab_ **one**

Then use find and replace with the option to replace all without confirmation and replace "one" with "two"
The result of this operation is:

two two two
	two	otwoonetwo

**Comment by bonecode** [comment]
Fixed.
