### ISSUE TITLE
Find and Replace broken after fix for #332

### ISSUE THREAD

**Issue by kurrat** [bonecode/TBCEditor#333]
Find and Replace still not working properly

**one** _space_ **one** _space_ **one**
_tab_ **one** _tab_ **one** _tab_ **one**

Then use find and replace with the option to replace all without confirmation and replace "one" with "three"
The result of this operation is:

threthrethree one
	threthrethree	one

or replace "one" with "x" to get

x onxnex
	x	onxnex

**Comment by bonecode** [comment]
Daaaamn, should not code when tired. :)

**Comment by bonecode** [comment]
Fixed.
