### ISSUE TITLE
GetWordAtCursor interferes with upward selection

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#34]
How to reproduce: use a TTimer, and in the timer event, call Editor.GetWordAtCursor
Now you are extending the selection "upward" (either with the mouse or with the keyboard sfhit + arrow up), whenever the timer is triggered it will reset the selection.

The issue does not happen when selecting "downward"

I suspect the issue is that GetSelectionBeginPosition/EndPosition do some "normalization", which is lost when assigning back the selection.

A fix & improvement would be to extract the inner function 'DoGetSelectedText' into a method that would get text between begin/end positions (rather than just those of the selection), this way GetWordAtCursor (and other methods) could use it to extract text without having to involve the selection mechanism.

**Comment by bonecode** [comment]
Fixed GetWordAtCursor.
