### ISSUE TITLE
Does anyone really need line selection mode?

### ISSUE THREAD

**Issue by bonecode** [bonecode/TBCEditor#344]
I am close to drop this feature. I don't need it and it is quite tricky to make it work with certain commands.

**Comment by EricGrange** [comment]
It's a mode that selects line as a whole?

I currently do not need or use it.

I guess it could come in handy for some cherry-picking and merge UI, but it should be possible to emulate it in applications, so it does not need to exist as a built-in feature of the editor IMHO.

**Comment by bonecode** [comment]
I agree, I will remove it.

**Comment by bonecode** [comment]
Done.
