### ISSUE TITLE
Tabulator behaviour

### ISSUE THREAD

**Issue by kurrat** [bonecode/TBCEditor#346]
TBCEditor currently has an unusual behaviour when using tabs.
In about every plain text editor I know a tab goes to the next column as per tab width.
This way when using tabs you get some text alignment.
Here a sample with tab width = 4 (UltraEdit)
![snapcrab_noname_2016-2-21_11-39-1_no-00](https://cloud.githubusercontent.com/assets/17256325/13202163/76527292-d890-11e5-864a-ab3f29b1954a.png)

and the same text in TBCEditor
![snapcrab_noname_2016-2-21_11-38-42_no-00](https://cloud.githubusercontent.com/assets/17256325/13202169/9f8504c2-d890-11e5-8d89-477f50ede72f.png)

As long as tabs are only used for indenting lines it makes no difference but as soon as tabs are used within the text all the "formatting" is gone. Sure one can use spaces instead of tabs but it would still be nice if the tabs in TBCEditor would feature the "common tab behaviour".

**Comment by bonecode** [comment]
Note to myself: Add toColumns option into Tabs.Options

**Comment by bonecode** [comment]
Fixed.
