### ISSUE TITLE
Use AntiAliased Font Quality for MiniMap 

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#35]
Use fqAntialiased by default 

     Minimap.Font.Quality := fqAntialiased;

By default MiniMap looks like

![image](https://cloud.githubusercontent.com/assets/2197210/7587586/b5d86516-f8b7-11e4-94c7-4cec3b724382.png)

And with fqAntiAliased it's like SublimeText

![image](https://cloud.githubusercontent.com/assets/2197210/7587623/f8b5e426-f8b7-11e4-80fe-1f5ce1a94d83.png)

To facilitate use, it might be practical to surface the Font Quality property independently from the TFont object (this way it's still practical to assign the Main Editor Font to the MiniMap Font directly)

**Comment by bonecode** [comment]
This I must disagree. Antialiased looks horrible with the white background. If someone likes antialiased, he can easily change it, but the default is what it is now.
