### ISSUE TITLE
Add 'EnhanceHomeKey" and 'EnhanceEndKey' to editor options

### ISSUE THREAD

**Issue by beNative** [bonecode/TBCEditor#350]
**EnhanceHomeKey**: Toggles behaviour of <Home> key on line with leading spaces. If turned on, key will jump to first non-spacing char, if it's nearer to caret position. 

**EnhanceEndKey**: Toggles behaviour of <End> key on line with trailing spaces. If turned on, key will jump to last non-spacing char, if it's nearer to caret position.

**Comment by bonecode** [comment]
I made this a feature. Those kind of "enhance", "smart", etc. named options must be avoided.
