### ISSUE TITLE
Make 'CharIndex' a property

### ISSUE THREAD

**Issue by beNative** [bonecode/TBCEditor#351]
I noticed you made a method `RowColumnToCharIndex` that calculates the ordinal position of a character based on its textposition.
This property could be used as an alternative to set the cursor to a specified postion. Similarly 2 integer properties to specify a block selection based on these _character indexes_ could be a good alternative to the existing properties.

**Comment by bonecode** [comment]
I don't think there is any need for this. You can set the text position by using TextCaretPosition and display position by using DisplayCaretPosition.
