### ISSUE TITLE
Tabulator

### ISSUE THREAD

**Issue by bonecode** [bonecode/TBCEditor#356]
I noticed several issues with different tab sizes. For example infinite loop when deleting it. Already fixed, will be in next commit.

**Comment by EricGrange** [comment]
I do not know if it's in your list, but the tabulator is currently affected by the previous actions, for instance with a tab size of 3, if you type 'enter' then tab, the tabulation will be of 2, same if you hit the home key (to go at line start).
However if you are at line start, hit arrow right, the go back to start with arrow left, it is size 3.

**Comment by bonecode** [comment]
I did fix this quite a lot. Test now again.

**Comment by EricGrange** [comment]
That particular issue seems fixed!

However there are still a couple of bugs:
- in overwrite mode tab does not overwrite anything
- with a block selected, tab always indents the line, but it should not indent the line if the selection is just part of a line (it should replace in that case)

**Comment by bonecode** [comment]
I think tab works exactly like it should when InsertMode is False - it just moves the caret and does not insert anything. The other is an issue indeed.

**Comment by EricGrange** [comment]
When a block is selected within a line, it should replace the block to be coherent with other keystrokes, though other editors have varying behaviors on that, so it's not critical (notepad++ ignores it, Delphi tabs through, SublimeText goes banana)

**Comment by bonecode** [comment]
Sure, that is a bug, it was the second issue.

**Comment by bonecode** [comment]
Fixed.
