### ISSUE TITLE
Support SynWrite lexers

### ISSUE THREAD

**Issue by Alexey-T** [bonecode/TBCEditor#357]
Hi.See my github, EControl code. It allows to use SynWrite lexers in open src projects. Now i have 160+ lexers.  They more powerful than BCEditor json lexers. nested lexers exist. (html with css, php, js).

Can u add support for Synw lexers?
https://sourceforge.net/p/synwrite/wiki/Lexers%20list/

**Comment by bonecode** [comment]
Interesting offer but can you show some examples of your highlighter files? I did look at the source but I didn't get into the point right away and that usually means the code needs a lot of refactoring and renaming. I see there ACP files which contain keywords, is that all?

**Comment by Alexey-T** [comment]
Yes, see https://sourceforge.net/projects/synwrite-addons/files/Lexers/
see any .Lcf file. This file is Delphi resource. it has

- list of styles (style is color of fore, back, bold/italic, frame)
- list of parsers (Names have parser 'id', numbers have parser 'number', strings have parser 'string', comments....., hex digits....., preprocessor.....). parsers have styles, e.g. parser 'nmber' has style 'number'.
- list of rules for getting folded blocks (folded blocks are `{.........}`, `begin ....end`, `function ..... endfunc`). This allows to set folding. and set syntax tree items. (Syntax tree at left of Synwrite)

**Comment by Alexey-T** [comment]
To see this list of parsers, you need open Synwrite, call "Options- Customize lexer library"- select lexer- call Customize

**Comment by bonecode** [comment]
I tried to use regex first but it was way too slow. My current solution is 10 times faster than that. Maybe I didn't do it right or maybe I used a wrong implementation of regex (see http://www.regular-expressions.info/). 

I tried your editor (with VirtualTrees.pas) and it goes very slow when scrolling it down. Maybe it is initializing code folding or something, I don't know. But anyway, this is interesting and I will investigate it further later.

**Comment by Alexey-T** [comment]
hm, can you try 2 editors, they based on EControl parser?

- Synwrite
- CudaText

maybe one goes scrolls slow, other not? Parser same, editor controls not same 
Also: my users very rare tell that scrolling is slow

**Comment by bonecode** [comment]
SynWrite was the editor what I already tried with the VirtualTrees.pas file. I tried CudaText with the same file and it was faster but there wasn't code folding. I rather read the code and see how things are done than try things. Give me a black box and I break it. :)

**Comment by Alexey-T** [comment]
Cuda is new one.I made it my own engine... it _has_ foldin (eg open HTML)

**Comment by Alexey-T** [comment]
folding

![vt](https://cloud.githubusercontent.com/assets/4154978/13374641/b01ce9ac-dd9b-11e5-86df-db32d88b2667.png)

**Comment by Alexey-T** [comment]
(It is Cuda issue: you open Virtualtree.pas, it parses it in backgnd, and until parsing done, fold not shown. sorry)

**Comment by bonecode** [comment]
Why the code folding is done in the background? It can be done very fast with pointer going thru once. Maybe you're using regex...

**Comment by Alexey-T** [comment]
It is Cuda issue: if u use EControl, you can get folding as you want (it is collection of special range class)

**Comment by bonecode** [comment]
Oh, I see EControl (http://econtrol.ru/) is a commercial product. That kind of seals the deal. I can't be part of this.

**Comment by Alexey-T** [comment]
No it's free for opensource--
https://github.com/Alexey-T/EControl/blob/master/readme.txt

LICENSE
EControl author [Michael Zakharov] gave permission to use this code (modified for ATSynEdit) only inside **open source** projects. It's NOT ALLOWED to use this code in closed source. For usage in closed source, you must buy license from EControl (for full code).

**Comment by bonecode** [comment]
Ok, but I still prefer to optimize my current solution than implementing a new one. There isn't much to win here. And I need to use more time for other projects soon after my annual holiday (april). This project has taken already a way too much my time and resources. Fun it has certainly been and I have learnt a lot but it is time to move on my Android projects (maybe I get paid someday). Issues are still fixed but not as fast as before. I will carefully consider any big changes and also I try to say "no" as much as possible. :)
