### ISSUE TITLE
Jump to next/previous identifier (or word) reference

### ISSUE THREAD

**Issue by beNative** [bonecode/TBCEditor#358]
Extra search commands that work similarly like GExperts to jump to next/previous identifier (or word at cursor position) reference would be very useful.

In GExperts both are named like this:
- Previous Identifier Reference (CTRL-ALT-UP)
- Next Identifier Reference (CTRL-ALT-DOWN)

**Comment by bonecode** [comment]
There already are Ctrl+Left and Ctrl+Right for jumping next/previous word.

**Comment by beNative** [comment]
Hi, I mean like a search feature to set the position to the next identical identifier in the file.

**Comment by bonecode** [comment]
So, you mean like search F3 and Shift+F3 but without searhing...

**Comment by beNative** [comment]
exactly!

**Comment by bonecode** [comment]
Fixed.
