### ISSUE TITLE
Drawing error

### ISSUE THREAD

**Issue by noname00-pas** [bonecode/TBCEditor#361]
Please see the GIF
![2016-02-29_08-46-22](https://cloud.githubusercontent.com/assets/7973218/13383779/1b9e3d54-dec1-11e5-8f1c-d77beda10e8a.gif)

Also, Tabs to spaces works even if I removed toTabsToSpaces from the Tabs options.

**Comment by bonecode** [comment]
Fixed. That tabs to spaces works like it should. It does not convert the whole document.
