### ISSUE TITLE
Tab key behavior still not as usual

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#362]
With tab with of 3, starting with the following content
```
hello
   world
q   
```
If you have the cursor just to the right of 'q' on the last line, if you type tab then "a", BCEditor gives
```
hello
   world
q   a   
```
while other editors preserve the tab alignment
```
hello
   world
q  a  
```

**Comment by bonecode** [comment]
Use SpecialChars.Visible = True and take small screen shots. Much easier to see what is wrong. Did you enable Columns from Tab.Options?

**Comment by EricGrange** [comment]
Indeed, I had not set that option, with it, it works as expected! thanks!

**Comment by thachngopl** [comment]
The TBCEditor still is wrong. The left on is TBCEditor:
![capture](https://cloud.githubusercontent.com/assets/16706272/13415118/bd8c1e6e-df8a-11e5-8534-583df1755714.PNG)

**Comment by thachngopl** [comment]
Matching pair highlight is wrong with Tabs char:

![2016-03-01_08-55-30](https://cloud.githubusercontent.com/assets/16706272/13415188/757e0712-df8b-11e5-9065-cdc18b1aca69.gif)

**Comment by bonecode** [comment]
Obviously at the first image there isn't toColumns True in Tabs.Options.

![image](https://cloud.githubusercontent.com/assets/11475177/13418022/dbecbfa0-df79-11e5-8ed3-c17a2981563d.png)

**Comment by thachngopl** [comment]
I made another GIF:
![2016-03-01_14-14-57](https://cloud.githubusercontent.com/assets/16706272/13420360/20e0ac78-dfb8-11e5-903f-c301ebfab1ca.gif)

**Comment by bonecode** [comment]
I see, this is a rendering issue. Tabulator should always be painted as a tabulator... I will reopen this.

**Comment by bonecode** [comment]
I think this is fixed. I will test this more.
