### ISSUE TITLE
SpecialChars color option

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#364]
Currently the special chars colors is set independently from the highlighting, which leads to issue when the background is not white.

This is a request for an option to have a "half way" color, for instance if foreground is black (0,0,0) and background is white (255,255,255), or vice-versa, it would pick gray (128,128,128).
But if background is gray (128,128,128) and text is black (0, 0, 0), it would pick a dark gray (64,64,64).

**Comment by bonecode** [comment]
There already is scoUseTextColor option but I also like idea of that half color.

**Comment by EricGrange** [comment]
Yes, I saw UseTextColor, but then the special chars do not stand out, or rather, they stand out too much :)

**Comment by bonecode** [comment]
Fixed.
