### ISSUE TITLE
Add OnMarginPre & PostPaintEvents

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#37]
The Pre would be after the background has been painted, but before anything else (so to apply custom background)

The Post would be once the margin has been painted.

Purpose: breakpoints & blue dots lines.

For the blue dots I tried using the Marks, but this results in thousandths of bookmarks, and the TBCEditorBookmarkList class is just not capabale of handling them efficiently, as it means adding/removing thousandths of bookmarks almost interactively, and searching though thousands of bookmarks for GetMarksForLine and PaintLeftMargin (which actually goes through the list twice)

**Comment by bonecode** [comment]
Added OnBookmarkPanelBeforePaint and OnBookmarkPanelAfterPaint properties.
