### ISSUE TITLE
Problematic call location for DoChange

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#376]
in TBCBaseEditor.SetSelectedTextEmpty the DoChange is invoked from withing the undo block, which means that user code in OnChange can trigger various issues because the editor is in an intermediate state (found it because merely accessing Lines[] triggered an AV in an edge case).

Two possible solutions:
- move all DoChange to outside of internal manipulation sections (but there are many of them, SetSelectedTextEmpty is not an isolated case)
- do not call OnChange from DoChange, but defer it to an asynchronous call, once the internal manipulations have ended

**Comment by bonecode** [comment]
I agree, I have also come across this.

**Comment by EricGrange** [comment]
For the moment I am rerouting the OnXxxChange events through TTimers, as a poor man's asynchronous mechanism :)

**Comment by bonecode** [comment]
Fixed.
