### ISSUE TITLE
Memory leak and corruption related to codefolding & deletions

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#377]
This is a weird one, I can reproduce it "semi-consistently":

- have FastMM in full debug mode
- have Editor.CodeFolding.Visible set to False (if True, the issue does not show up)
- edit BCEditor.Editor.Base.pas with Object Pascal highlighter
- scroll down a bit, select multiple lines, hit delete or suppr
- scroll down a bit, select multiple lines, hit delete or suppr

This is usually enough to trigger a memory corruption. If not repeat the last step.

Again this happens only if CodeFolding is not Visible.

**Comment by bonecode** [comment]
I got this repeated easily.

**Comment by bonecode** [comment]
Fixed, it is not necessary to update code folding caches when the code folding is not visible.
