### ISSUE TITLE
CodeFolding Scan

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#378]
Use the highlighter json from here:
[C++.zip](https://github.com/bonecode/TBCEditor/files/168412/C.zip)
Result:
![2016-03-11_10-29-51](https://cloud.githubusercontent.com/assets/16706272/13692452/4053e4f8-e774-11e5-8d3b-3cad8c8e5687.gif)

**Comment by bonecode** [comment]
Remove the following from your highlighter:

```
"FoldRegion": [
{
  "OpenToken": ")",
  "CloseToken": "}",
  "Properties": {
      "BreakIfNotFoundBeforeNextRegion": "{"
   }
},
```

**Comment by thachngopl** [comment]
Another GIF (Everything from here http://www.bonecode.com/downloads/BCEditorComponentDemo64.zip, not modify any files)

![2016-03-11_14-31-00](https://cloud.githubusercontent.com/assets/16706272/13695987/fbee330a-e795-11e5-93d2-783b75bd2d45.gif)
