### ISSUE TITLE
OnLeftMarginClick should allow prevention of default behavior

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#38]
By default a left margin click sets a bookmark, I want it to set a breakpoint.

However OnLeftMarginClick fires after the default behavior of toggling the bookmark (which is earlier MouseDown), which thus ends up setting both bookmark & breakpoint.

**Comment by bonecode** [comment]
Fixed. Added bpoToggleBookmarkByClick option for the left margin bookmark panel.
