### ISSUE TITLE
SearchMap incorrectfly offseting IndentGuides ?

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#385]
I have somehow gotten a combination of properties that result in the indent guid no longer being aligned with characters

![image](https://cloud.githubusercontent.com/assets/2197210/13812710/fcf8387c-eb7d-11e5-9f74-64a005bdd1dd.png)

the dotted line for the "writeln" is halfway in the previous character.

I think this is caused by an incorrect search map offset code in TBCBaseEditor.PaintGuides, which is written as 

              if FSearch.Map.Align = saRight then
                Dec(X, FSearch.Map.GetWidth);

while it should be 

              if FSearch.Map.Align = saLeft then
                Inc(X, FSearch.Map.GetWidth);

**Comment by bonecode** [comment]
Fixed.
