### ISSUE TITLE
Code Folding behavior

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#387]
Please see the GIF

![2016-03-17_15-35-35](https://cloud.githubusercontent.com/assets/16706272/13840597/02944dc4-ec56-11e5-9b72-6999b21f6ed7.gif)

RAD can fold from INTERFACE keyword to the non-empty line right before IMPLEMENTATION keyword.

**Comment by bonecode** [comment]
Fixed Object Pascal highlighter and painting.
