### ISSUE TITLE
Middle mouse button drag does not deactivate

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#390]
Clicking the middle (or wheel) mouse button activates the drag mode, but clicking it again does not seem to deactivate it

**Comment by bonecode** [comment]
Can't repeat, did you try the demo?

**Comment by bonecode** [comment]
Ah, "clicking it"... Indeed, clicking the middle mouse button does not deactivate it. It activates it again.

**Comment by bonecode** [comment]
Fixed.
