### ISSUE TITLE
GClipboardFormatBCEditor broken & unstable

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#392]
When copying across BCEditor and the GClipboardFormatBCEditor format is used, the content of the destination BCEditor is broken, and there are evidences of memory corruption.

Problem was initially detected when copy-pasting between executables compiled with different versions of BCEditor, from an older BCEditor to latest BCEditor, it resulted in a crash with AV.

However issue is also present when copying from latest BCEditor to latest BCEditor, it did not crash but there were memory leaks and undo is not fully operational.

When the copy is made through notepad, copy from old BCEditor, paste in notepad, then copy from notepad, paste into new BCEditor, everything is fine.

Given that all editors properly specify clipboard text data anyway, is there any point to GClipboardFormatBCEditor? (and GClipboardFormatBorland and GClipboardFormatMSDev)

**Comment by bonecode** [comment]
Good question, that is a legacy code from my old SynEdit fork and then this was added by some guy from Asia. I did also notice some odd behavior when copying SQL from IBQ (it is using TBCEditor). Maybe I will do what I like the most and remove the code. :D

**Comment by bonecode** [comment]
Gone.
