### ISSUE TITLE
Indent guide line painting and code folding rescan

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#393]
Please see the GIF:

![2016-03-18_08-54-40](https://cloud.githubusercontent.com/assets/16706272/13866367/43b9c61c-ece7-11e5-9276-835ce84d7257.gif)

**Comment by thachngopl** [comment]
Code folding does not work properly:

![2016-03-18_09-05-53](https://cloud.githubusercontent.com/assets/16706272/13866517/b4082066-ece8-11e5-9e9c-a40034d12eae.gif)

**Comment by thachngopl** [comment]
Another issue:

![2016-03-18_09-19-40](https://cloud.githubusercontent.com/assets/16706272/13866675/993dc770-ecea-11e5-9c8a-65ceafb10249.gif)

**Comment by bonecode** [comment]
I see, code folding TokenEndIsPreviousLine property has a bug.

**Comment by bonecode** [comment]
Fixed.
