### ISSUE TITLE
Wave line under a token

### ISSUE THREAD

**Issue by chinshou** [bonecode/TBCEditor#396]
such as draw some wave line under the spell error?

best regards

**Comment by bonecode** [comment]
Everything is possible, if it makes sense. I won't make a spell check feature because that would take a lot of time and there already are some pretty good ones which can be integrated. Custom drawing is possible even now but sure I could make that wave line drawing under a token easier...

**Comment by chinshou** [comment]
Thank you for your quick response.

custom draw is good enough for me , as far as it is possible to do custom drawing , I can implement the spell check of a token by myself.

**Comment by bonecode** [comment]
Now it is possible to write code like:

```
procedure TMainForm.EditorCustomTokenAttribute(ASender: TObject; const AText: string; const ALine, APosition: Integer;
  var AForegroundColor, ABackgroundColor: TColor; var AStyles: TFontStyles;
  var ATokenAdditionalFeature: TBCEditorTokenAdditionalFeature; var ATokenAdditionalFeatureColor: TColor);
begin
  inherited;
  if AText = 'begin' then
  begin
    ATokenAdditionalFeature := tafWaveLine;
    ATokenAdditionalFeatureColor := clRed;
  end;
end;
```

and it looks like:

![image](https://cloud.githubusercontent.com/assets/11475177/21693746/c8d1d792-d38a-11e6-8e67-89e24f7dcd2b.png)
