### ISSUE TITLE
Create another demo without any third party controls

### ISSUE THREAD

**Issue by DelphiMan68** [bonecode/TBCEditor#399]
Hi, 
Please make another demo without any of third party controls. also notice that demo not works with this version because some units not exists in component source code. maybe unit names was changed.

**Comment by bonecode** [comment]
Making extra demos is a waste of time. 

Simplest demo is to just drop the TBCEditor into a form and add the following code:

```
with BCEditor1 do 
begin
  Highlighter.LoadFromFile('JSON.json');
  Highlighter.Colors.LoadFromFile('Default.json'); 
  Lines.Text := Highlighter.Info.General.Sample; 
end;
```

I updated current demo source. Build requires 

- <a href="http://www.alphaskins.com/">AlphaSkins</a>  
- <a href="http://www.ehlib.com/">EhLib</a>
- <a href="https://github.com/bonecode/Common">Common</a>
