### ISSUE TITLE
Fix for XE7 compilation error

### ISSUE THREAD

**Issue by WouterVanNifterick** [bonecode/TBCEditor#400]
Hi, the current code doesn't compile under XE7, unless you install update1. 

`StrToJSONStr()` expects a function pointer, but the compiler insists on treating it as a function call.

The fix to make it compile without any negative side effects that I can think of, is to change BCEditor.JsonDataObjects, line 219. Remove `overload` for `TJsonStringBuilder.AppendIntro`, and then everything works fine under vanilla XE7. That overload directive is useless anyway...

**Comment by bonecode** [comment]
This is a known issue. Delphi XE7: Update 1 required.

You can ask Andreas to fix (maybe to use ifdef) this.

https://github.com/ahausladen/JsonDataObjects/issues

I rather don't do any changes for BCEditor.JsonDataObjects.pas file. In fact I could remove that from the project...

**Comment by WouterVanNifterick** [comment]
Ok, reported it:

https://github.com/ahausladen/JsonDataObjects/issues/27
