### ISSUE TITLE
Multi-edit undo

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#402]
1. Open TBCEditor Demo
2. Click on "program" key word (any position of this word)
3. Hold Ctrl key and click on writeln (any position of this word) => need add a new caret here
4. Press any key to insert a character
5. Press Ctrl-Z to undo => can't undo

**Comment by bonecode** [comment]
You can undo/redo after you click away from the multi-caret editing mode. But sure, it should work in the mode.

**Comment by thachngopl** [comment]
Another question: do you have any plan to support multi-selection?
Thanks.

**Comment by bonecode** [comment]
Do you have an example about that? I don't have any idea how it actually works and for what it is needed. I have never used it.

**Comment by thachngopl** [comment]
Here you are: http://wiki.freepascal.org/CudaText#Multi-selections

**Comment by bonecode** [comment]
Very rare case when you need that. I will put that on my todolist. Maybe someday I am bored...

**Comment by thachngopl** [comment]
This is a useful functionality.
For example: 
I want to enter this

``` html
<ul>
  <li id="the-first-paragraph">The first paragraph</li>
  <li id="the-second-paragraph">The second paragraph</li>
</ul>
```
I can do this by these steps:
1. Enter 
``` html
<ul>
  <li id="The first paragraph
  <li id="The second paragraph
</ul>
```
2. Use multi-selection to copy "The first paragraph" and "The second paragraph"
``` html
<ul>
  <li id="The first paragraph
  <li id="The second paragraph
</ul>
```
3. Enter "> and paste, then enter </li>

``` html
<ul>
  <li id="The first paragraph">The first paragraph</li>
  <li id="The second paragraph">The second paragraph</li>
</ul>
```
4. Select id="The first paragraph" and id="The second paragraph" by using multi-selection
5. Use ToLowserCase for 2 selections, then use replace(' ', '-') for 2 selection
=> Done

**Comment by bonecode** [comment]
Fixed undo.
