### ISSUE TITLE
Not much of an issue but..

### ISSUE THREAD

**Issue by adem0x** [bonecode/TBCEditor#412]
I haven't yet compiled any of this code (I am on XE2) but when I started playing with the demo (BCEditorComponentDemo64), I tried changing the font to 'Consolas' but being lazy I typed 'consolas' (all lower case).

When I did this, the text displayed became, how shall I put it, a display of all fixed-with characters. Much like a hex editor in text mode.

When I then typed in 'Consolas', things became as expected.

It really shouldn't be picky about case-sensitivity of font name (Delphi's code editor doesn't.)

One final thing, off-topic here though: Every component this project uses is compatible with XE2. I wonder what is there in the TBCEditor sources that dictate higher versions.

**Comment by bonecode** [comment]
I can't repeat that font issue.

![image](https://cloud.githubusercontent.com/assets/11475177/16295755/43b32a82-3931-11e6-997c-f090860a8116.png)

I just had to draw the line somewhere and I decide to draw it XE4. I don't have older versions installed.
