### ISSUE TITLE
Selecting non existant text in an empty BCEditor raises exception access violation

### ISSUE THREAD

**Issue by vhanla** [bonecode/TBCEditor#414]
If BCEditor is empty (`BCEditor1.Lines.Clear;`) and try to select text with mouse click-dragging or Shift+arrow keys it will raise an access violation error, since it is not considering the FCharCountArray:

`function GetTextWidth(AIndex: Integer; AMinimap: Boolean = False): Integer;`
...
`for i := 1 to AIndex - 1 do`
    `      Result := Result + FTextDrawer.CharWidth * FCharCountArray[i - 1];` <- line 10446 BCEditor.Editor.Base.pas

To fix that I just added `if FCharCountArrayLength > 0 then` before the `FOR LOOP`

**Comment by bonecode** [comment]
The fix is not that simple. I uploaded the fix for this. Note that the current trunk is not a stable version.
