### ISSUE TITLE
TBCEditor Subcomponentstructure is very static

### ISSUE THREAD

**Issue by Memnarch** [bonecode/TBCEditor#419]
Currently everything like Completionproposal, Minimap, SearchEngine etc is a part of the Editor.

For example the CompletionProposal (except from OnBeforeExecute) has no events. Neither can i derive from the existing one to extend it. For example how am i supposed to add icons to each entry? Instead of everything being baked into one thing i'd expect components you can put together.

**Comment by bonecode** [comment]
That is my considered choice. I don't want to mess up with multiple components like SynEdit does. But the source is completely free and anyone can do whatever they want with it. Because this is my hobby, I can do also whatever I want with it and believe me I will. :)
