### ISSUE TITLE
Code Folding Region description / comment

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#42]
A code folding region can include a description/comment 

   {$REGION 'test'}
   bla bla bla
   blah blah
   {$ENDREGION}

when collapsed it should show a just 'test', currently it shows up as '{$REGION..{$ENDREGION}'

**Comment by ngthach** [comment]
This is my suggestion for Grammar Parser for this case:
{
	"OpenToken": "$REGION",
	"CloseToken": "$ENDREGION",
	"FoldedDrawing": "$1",
	"RegularExpression": "\$REGION\s+'([^']+)'" // Turn into regular expression parser for this case only	
}

**Comment by bonecode** [comment]
RegularExpressions are nonono when parsing text fast. I already have a simpler solution:

"OpenTokenEnd": "}"

**Comment by bonecode** [comment]
Fixed.
