### ISSUE TITLE
Modified := False does not clear UndoList

### ISSUE THREAD

**Issue by paresy** [bonecode/TBCEditor#420]
```
 BCEditor1.Text := 'Nice!'; //modified is now TRUE
 BCEditor1.Modified := False; //reset it (e.g. we saved everything)

 if BCEditor1.Modified then
  ShowMessage('Check #1: now modified');  //will not fire

 //move the caret with the mouse. just click in the editor

 if BCEditor1.Modified then
  ShowMessage('Check #2: now modified');  //will fire because modified := false does not reset the undolist count which is checked in UpdateModifiedStatus
```

I don't know if this is intended behavior. If yes, just close the issue.

The workaround is as simple as adding the following line.

> BCEditor1.UndoList.Clear;

**Comment by bonecode** [comment]
I think there is a bug because I've noticed some not so intended behavior in my editor sometimes. I will check this after I get the painting done.

**Comment by bonecode** [comment]
I have thought about when it is really needed to set the modified property? I think it should not be even possible. Modified is an inner status of the editor and you can use its value for example to enable/disable save action. It is set by the editor itself during undo operations or when saved or lines are cleared. So, I think I will make it read only property...

**Comment by bonecode** [comment]
But... there is always but... if you check whether a file has changed, then you need to set it modified...

**Comment by bonecode** [comment]
Hmm, are you sure, you didn't do anything else than move the caret by mouse? It should not be modified.

**Comment by paresy** [comment]
The real problem is that setting the Text property sets modified to TRUE. How am i supposed to load my content without getting the modified flag set to TRUE?

For BoneCode that means that i already have something in the UndoList, which after a click (another UndoItem) sets the Modified to TRUE.

Maybe i just should load my content through a TStringStream and LoadFromStream?
What is the Text property good for?

**Comment by bonecode** [comment]
That is not a problem. Use Editor.Lines.Text, if you don't load the content from file.  Editor.Text will add the text you're replacing into undo list.
