### ISSUE TITLE
Text selection bug (trunk version)

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#426]
Sample 1
![bandicam_2016-07-26_08-38-46-172](https://cloud.githubusercontent.com/assets/11677236/17127322/6c171358-530d-11e6-9e6c-e4cee20330d9.gif)

Sample 2
![bandicam_2016-07-26_08-40-19-975](https://cloud.githubusercontent.com/assets/11677236/17127326/708cdf08-530d-11e6-8873-e1a7cac51de7.gif)

**Comment by bonecode** [comment]
I tried in my editor but I can't repeat. Can you post the editor properties you're using?

**Comment by piker00** [comment]
To reproduce this problem just drop on the form BCEditor and clear it's lines. 
No other properties changes required.

**Comment by bonecode** [comment]
So, you're not loading a highlighter and color? I think that is the problem but I will check that later.

**Comment by piker00** [comment]
Yes, as you say, no colors no highlighters.

To reproduce second sample pleas check this code below, I don't know which property I changed that causes this problem: 
[Sample2.zip](https://github.com/bonecode/TBCEditor/files/383451/Sample2.zip)

**Comment by bonecode** [comment]
You should load Text highlighter and Default color at least. I haven't thought about the use without highlighter and color and I don't think there is much use for it without those. But I will check....

**Comment by piker00** [comment]
with my Sample2.zip that I send to you, I see the same shit even if add

> **procedure** TForm3.FormCreate(Sender: TObject);
> **begin**
> 
>  BCEditor1.Highlighter.Colors.LoadFromFile( 'C:\Components\Free\BCDEditor\TBCEditor\Colors\Default.json');
>  BCEditor1.Highlighter.LoadFromFile('C:\Components\Free\BCDEditor\TBCEditor\Highlighters\Text.json' );
> 
>   BCEditor1.Lines.Text := Memo1.Text;
> 
> **end;**

**Comment by piker00** [comment]
My investigation shows that cause of problem shown in sample 2 is that BCEditor1.Font.Charset was set to ANSI_CHARSET, but caret bug from sample 1 still remain

**Comment by bonecode** [comment]
Aah, it's all about tabulators...

**Comment by bonecode** [comment]
Should be fixed.
