### ISSUE TITLE
Caret position bug

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#427]
Trunk version, default BCEditor, no property changes.
![caret-position-bug](https://cloud.githubusercontent.com/assets/11677236/17132512/c86bf214-532a-11e6-8134-52d4e9ecb3a7.gif)

**Comment by bonecode** [comment]
It works like it should - second click goes to the last word on the row.  I don't remember if there was an option for this. I will check that... Otherwise, there is that same problem like #426.
