### ISSUE TITLE
Mouse selection should capture mouse

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#43]
Currently when extending the selection with the mouse, the mouse movements are taken into account only when the cursor is over the code area.

It should extend if the mouse is outside the code area, and even it is outside the control itself.

(cf [SetCapture](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646262%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396))

**Comment by EricGrange** [comment]
Addendum: issue is not capture by itself, but of ignoring code rect when the action is a selection extension

**Comment by EricGrange** [comment]
A side issue is that if you click & drag in the minimap then move the mouse over the code area, it will start a selection.

Generally speaking the area on which a click & drag was started on should "capture" the mouse until the click is released.

Note that dragging selected text (to move or copy it with the mouse) does not have any issue, the capture is properly handled.

**Comment by bonecode** [comment]
Fixed.
