### ISSUE TITLE
insertTag, insertDate, insertLine errors

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#433]
After insertTag or insertDate caret receives wrong position
![bandicam_2016-07-28_13-57-47-686](https://cloud.githubusercontent.com/assets/11677236/17210491/f8dca0cc-54cb-11e6-98a9-8c11c3f0770a.gif)

New line iserition causes error msg: **Error insertLine Invalidstringlist index 1** if Editor is clear
![bandicam_2016-07-28_14-01-18-299](https://cloud.githubusercontent.com/assets/11677236/17210560/5b09f0d8-54cc-11e6-859f-40583fbe22df.gif)

**Comment by bonecode** [comment]
I can't repeat in my editor. Show the code.

**Comment by piker00** [comment]
Editor1.CommandProcessor(ecInsertLine, 'N', nil);

**Comment by piker00** [comment]
Can you suggest something else ?

**Comment by piker00** [comment]
I checked last EditBone and it has same problem as shown in first gif.

**Comment by piker00** [comment]
and same problem as shown in gif 2

**Comment by bonecode** [comment]
Fixed.

**Comment by piker00** [comment]
Nothig is fixed "bcEditor.InsertLine(  0, DateTimeToStr(Now) );"
Error: Invalid liststring index -1

**Comment by bonecode** [comment]
Wrong use of index. See the code.
