### ISSUE TITLE
Scroll bug 

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#434]
after Delete Whitespace:
![bandicam_2016-07-28_14-11-15-737](https://cloud.githubusercontent.com/assets/11677236/17210799/c0beeb8a-54cd-11e6-95fb-49b36b7488d7.gif)

**Comment by bonecode** [comment]
Seems to be a bug with auto size max width scroll option.

**Comment by bonecode** [comment]
Fixed. Very very long lines need some optimizing.
