### ISSUE TITLE
Inser mode

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#437]
![insertmodebug](https://cloud.githubusercontent.com/assets/11677236/17305368/cf8766fc-5832-11e6-8931-556ee8e63471.gif)

**Comment by bonecode** [comment]
Use special chars and you will see there are probably tabulators and you're having having column mode on. Nothing wrong here.

**Comment by piker00** [comment]
Yes there are tabulators but column mode is off.
Do you want say that it's ok that we need two chars before text to move it, if space between them are tabulators ? Then I have question, how to prevent tabulators and put spaces instead of them by default?

**Comment by bonecode** [comment]
I meant tabulator option toColumns. Is that enabled?

**Comment by piker00** [comment]
Yes toColumns is enabled, and toTabsToSpaces solves the problem, thanks.
