### ISSUE TITLE
Wrong selection if BCEditor1.Scroll.MaxWidth := 1;

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#439]
![bandicam_2016-08-02_04-58-47-120](https://cloud.githubusercontent.com/assets/11677236/17314613/5fccfba6-586e-11e6-97ba-506ade658c97.gif)

**Comment by bonecode** [comment]
MaxWidth := 1 does not make much sense. I will check if I can remove this property. It should be automatic.

**Comment by bonecode** [comment]
MaxWidth is removed.
