### ISSUE TITLE
MacroRecorder crash on destruction

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#44]
Minimal test case: on a new form OnCreate, create an editor & a recorder, link them. When closing the form there is an AV

    editor := TBCEditor.Create(Self);
    editor.Align := alClient;
    editor.Parent := Self;
    TBCEditorMacroRecorder.Create(Self).Editor := editor;

If shortcuts have been registered with the recorder, there is a different crash, but it's probably the same issue

**Comment by bonecode** [comment]
Fixed.
