### ISSUE TITLE
Inser 

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#443]
Nothig is fixed "bcEditor.InsertLine( 0, DateTimeToStr(Now) );"
Error: Invalid liststring index -1

**Comment by piker00** [comment]
if you have only one line from start then error occurs.

**Comment by bonecode** [comment]
The index 0 is wrong. The parameter is ALineNumber and it is not zero based. 

Use: Editor.InsertLine(1, DateTimeToStr(Now));

**Comment by bonecode** [comment]
But the good question is should the parameter be zero based... somebody asked me to add this method. I don't use it and I haven't thought about since then.
