### ISSUE TITLE
Any shortcut keys will also open the CompletionProposal

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#445]
Any shortcut keys will also open the CompletionProposal
When open BCEditor1.CompletionProposal.Options :=BCEditor1.CompletionProposal.Options + [cpoAutoInvoke];
Any shortcut keys Will open CompletionProposal window, for example  Ctrl+F  Ctrl+S
Why not add a valid character detection?
![image](https://cloud.githubusercontent.com/assets/6091308/18028466/d631fcb2-6cb2-11e6-949b-d4ae72cc9368.png)

**Comment by bonecode** [comment]
Fixed.
