### ISSUE TITLE
When the space bar is not on the screen

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#446]
When open BCEditor1.CompletionProposal.Options :=BCEditor1.CompletionProposal.Options + [cpoAutoInvoke];
use lua.json
I need input " this is test "
![image](https://cloud.githubusercontent.com/assets/6091308/18028558/b09a7c98-6cb4-11e6-97d8-97cc9ba6f6a8.png)
Now i Press spacebar 
![image](https://cloud.githubusercontent.com/assets/6091308/18028574/2b9185a4-6cb5-11e6-8d5b-465c4259805d.png)
I think it is only on the screen when press enter.
When the space bar is not on the screen

**Comment by bonecode** [comment]
Fixed.
