### ISSUE TITLE
chinese Display error

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#447]
Chinese original content is "掉线事件检测函数"
But it is shown as
![image](https://cloud.githubusercontent.com/assets/6091308/18028807/fb727450-6cb9-11e6-8dab-e525a5db04c5.png)

-----------------------------------------------------------------------------------
But this version is normal.
The latest update: 29.05.2016 20:35, UTC+02:00
897e3077fd269abda2fe37cf2fded4534f7c1295

![image](https://cloud.githubusercontent.com/assets/6091308/18028923/4c509fbc-6cbc-11e6-810d-f99498f0c353.png)

**Comment by bonecode** [comment]
Fixed. The painting is totally refactored from the version 1.6.
