### ISSUE TITLE
English+Chinese display error

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#448]
Chinese+English+Chinese original content is "当按下Insert键为启动脚本功能"
show is right
![image](https://cloud.githubusercontent.com/assets/6091308/18031765/68ef90f0-6d21-11e6-900f-a5ad2bdc20ba.png)
Error when editing content
When the cursor is here Press 4 backspace
![image](https://cloud.githubusercontent.com/assets/6091308/18031788/2d871438-6d22-11e6-8042-cdb63c22b685.png)
Error shown as
![image](https://cloud.githubusercontent.com/assets/6091308/18031823/3ec21404-6d23-11e6-89a8-b34f39f617a0.png)

--------------------------------------------------------------------------------------------------------------
English+Chinese original content is "Insert键为启动脚本功能"
Error shown as
![image](https://cloud.githubusercontent.com/assets/6091308/18031739/a9fc8612-6d20-11e6-8d18-b7f6515e52b8.png)

**Comment by bonecode** [comment]
Fixed.
