### ISSUE TITLE
TBCEditorToken memory leak

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#45]
FastMM log shows

    A memory block has been leaked. The size is: 36

    This block was allocated by thread 0x1784, and the stack trace (return addresses) at the time was:
    40492E [System][@GetMem]
    92E6B1 [BCEditor.Highlighter.pas][BCEditor.Highlighter][TBCEditorHighlighter.Next][228]
    959C40 [BCEditor.Editor.Base.pas][BCEditor.Editor.Base][TBCBaseEditor.PaintTextLines][8462]
    955772 [BCEditor.Editor.Base.pas][BCEditor.Editor.Base][TBCBaseEditor.Paint][7001]
    48F111 [Controls][TCustomControl.PaintWindow]

**Comment by EricGrange** [comment]
Addendum: the leak is not a one-off, it's repeated during repaints

**Comment by bonecode** [comment]
I don't get the memory leak... what do you exactly do when you get it?

**Comment by EricGrange** [comment]
Hmmm, I was getting it all the time, it's with the Pascal highlighter. I
will make you a test case Friday.

On Wednesday, May 13, 2015, Lasse Rautiainen <notifications@github.com>
wrote:
> I don't get the memory leak... what do you exactly do when you get it?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/KA9Pem_VrmGD-r9awz33UOjcRU-soLAmAHGel8-Ftj7lmMnusCwAMmapqK_W1KUoi3h2wRZa8GZqqbldReGQusJIEbBJIJC_YD7K93wsOLGD1r_bzj920M7vT9cLxUderCJfhcrt516a86T8yGs0V_lDsp9AJA=s0-d-e1-ft#https://github.com/notifications/beacon/ACGG2khp3bmGF07C_R7Yzf5qymjY20hPks5oI4K9gaJpZM4EY7lL.gif
>

**Comment by bonecode** [comment]
I think I got the same small leak by moving minimap up and down for awhile. Interesting...

**Comment by bonecode** [comment]
I think I found it. Atleast I don't get leaks anymore.

**Comment by EricGrange** [comment]
I do not get it either, must have been the same leak, thanks!
