### ISSUE TITLE
Caret position error

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#450]
Test string: सिग्नल डिजिटल / एनालॉग
Keep the mouse down and move from right to left
![2016-08-30_09-13-23](https://cloud.githubusercontent.com/assets/16706272/18073703/29b66d38-6e92-11e6-8c72-6e3a7c92eb09.gif)

**Comment by bonecode** [comment]
I didn't notice anything wrong. Combined marks are causing that position "error".

**Comment by bonecode** [comment]
Fixed.
