### ISSUE TITLE
Can't load large JSON file

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#451]
Test file: http://jsonstudio.com/wp-content/uploads/2014/02/companies.zip

**Comment by bonecode** [comment]
Fixed. I will optimize the code constantly, so this should come faster. Now the loading time was 6.515 s.

I think I should show progress bar like Sublime does.

**Comment by bonecode** [comment]
Now the loading time is 5.422 s. For example Sublime loads the same file in 11 s. But I think there are still a lot of optimizations to be done.

**Comment by thachngopl** [comment]
Fantastic :+1:

**Comment by bonecode** [comment]
Now it is 2.610 s with JSON highlighter and 1.391 s with Text highlighter. Quite good. :)
