### ISSUE TITLE
Special chars paint error

### ISSUE THREAD

**Issue by paresy** [bonecode/TBCEditor#455]
Sometimes special chars are painted as black squares. This only seems to happen in the last visible line.

![specialchars](https://cloud.githubusercontent.com/assets/260376/18133583/74dfdac4-6f9b-11e6-9296-653db8e5e5f3.png)

Fixed.

**Comment by bonecode** [comment]
I also noticed that after code folding there is a special char at the last line...

![image](https://cloud.githubusercontent.com/assets/11475177/18162418/10fc1d20-703f-11e6-8a86-83f098a1e64a.png)

![image](https://cloud.githubusercontent.com/assets/11475177/18162449/30054822-703f-11e6-9b50-95180bc54d5a.png)

**Comment by paresy** [comment]
There seems to be a selection error aswell. Tab width was 5, but does not matter.

![selected](https://cloud.githubusercontent.com/assets/260376/18201959/8bf8db70-710d-11e6-8ddf-e17a96c65135.png)
![not_selected](https://cloud.githubusercontent.com/assets/260376/18201960/8c0b8630-710d-11e6-941a-00e753e7b280.png)

**Comment by paresy** [comment]
Missing tabs
![missingtabs2](https://cloud.githubusercontent.com/assets/260376/18203336/bdca17aa-7116-11e6-8412-a7c7b3c94f1d.gif)
![missingtabs](https://cloud.githubusercontent.com/assets/260376/18203337/bde52eb4-7116-11e6-9823-c8280894b3d2.gif)

**Comment by bonecode** [comment]
Fixed.
