### ISSUE TITLE
Highlighters editor (?)

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#459]
I think that Highlighters editor control (may be based on VirtualTreeView) can be good tool also for EditBone, what do you think ?

**Comment by bonecode** [comment]
What do you mean by that "Highlighters editor control"?

**Comment by bonecode** [comment]
I am not sure what this is about, so I close it. Highlighters are JSON files and making visual editor for it is not on my todolist, if that is what this is about.
