### ISSUE TITLE
TBCCustomEditor.DoOnProcessCommand hint

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#46]
[DCC Hint] BCEditor.Editor.pas(16): H2269 Overriding virtual method 'TBCCustomEditor.DoOnProcessCommand' has lower visibility (protected) than base class 'TBCBaseEditor' (public)

**Comment by bonecode** [comment]
I don't get this. DoOnProcessCommand is in the protected section of both (TBCCustomEditor and  TBCBaseEditor) classes.

**Comment by EricGrange** [comment]
Not getting it anymore either, not sure what happened :/
