### ISSUE TITLE
Click on a long line of nulls

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#463]
Open this file, then put caret at the end of text
[XXX.txt](https://github.com/bonecode/TBCEditor/files/460691/XXX.txt)

**Comment by bonecode** [comment]
What was the problem, I can't repeat?

**Comment by piker00** [comment]
![2](https://cloud.githubusercontent.com/assets/11677236/18350747/f8a8f580-75df-11e6-9bed-e007c9a94b63.gif)

**Comment by bonecode** [comment]
Fixed.
