### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#466]
![2](https://cloud.githubusercontent.com/assets/11677236/18425002/25e2ba14-78be-11e6-9d28-092968ab7733.gif)

**Comment by bonecode** [comment]
![image](https://cloud.githubusercontent.com/assets/11475177/18427636/2d74d51e-78d2-11e6-9ef9-957d8a11676f.png)

**Comment by bonecode** [comment]
Fixed.
