### ISSUE TITLE
Word Wrap bugs screen short, test file and SynEdit Demo for compare

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#469]
[SynEdit_word_wrap.zip](https://github.com/bonecode/TBCEditor/files/471575/SynEdit_word_wrap.zip)

**Comment by bonecode** [comment]
Blaah, SynEdit word wrap is an awful example. I've already implemented working word wrap but there are now bugs after including fixed font support. There already is an issue about this, so I close this.
