### ISSUE TITLE
Add cache for GetCharABCWidthsW in TextDrawer

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#47]
GetCharABCWidthsW can account for about 45% for the time spent in gdi32.dll when minimap is active (or many lines are on screen). A way to alleviate that is to cache the values for the ASCII range.

Here is ported version for BCEditor of the GetCachedABCWidth I made for SynEdit a while ago:

https://bitbucket.org/egrange/tbceditorxe/commits/8cb0ac1c7cdd386dd2d42aeda4a5602839d50322

It could eventually be further optimized by maintaining the cache for all styles of the font, but the above is enough to almost double the framerate.

**Comment by bonecode** [comment]
Nice, thanks. :)
