### ISSUE TITLE
Completion proposal - move selection while scrolling with "page down" 

### ISSUE THREAD

**Issue by paresy** [bonecode/TBCEditor#470]
![bettercompletion](https://cloud.githubusercontent.com/assets/260376/18506606/1cd26932-7a6d-11e6-80c7-c5e6028e4dae.gif)

I know that this part is up for refactoring, but i just wanted to suggest a small enhancement. 

When scrolling with "page down" through the list, the selection should be "moved" forward aswell. This would fix the issue that after scrolling, the focus stayed at the top and you cannot use the "down arrow" key for navigation after the "page down" scrolling.

**Comment by bonecode** [comment]
Fixed.
