### ISSUE TITLE
Fixed bug in the TBCEditorLines.SetTextStr & file loading speed, max memory enhancement

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#471]
[BCEditor.Editor.Base_BCEditor.Lines.zip](https://github.com/bonecode/TBCEditor/files/475011/BCEditor.Editor.Base_BCEditor.Lines.zip)

**Comment by bonecode** [comment]
There seems to be a bug. Last line is not loaded.

**Comment by bonecode** [comment]
There was a small bug in the SetTextStr. Notice that I have fixed TStrings GetTextStr and it does not add extra line feed at the end of the text. Loading speed did not improve much but otherwise good good...
