### ISSUE TITLE
Fix BUG in the TBCEditorLines.SetTextStr please

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#473]
if LPValue <= LPLastChar then //BUG Fix
      begin
        if LPValue <> LPStartValue then
        begin
          SetString(LValue, LPStartValue, LPValue - LPStartValue);
          InsertItem(FCount, LValue);
        end
        else
          InsertItem(FCount, '');
        if LPValue^ = BCEDITOR_CARRIAGE_RETURN then
          Inc(LPValue);
        if LPValue^ = BCEDITOR_LINEFEED then
          Inc(LPValue);
        if LPValue^ = WideChar($2028) then
          Inc(LPValue);
      end;
   -------------------------------------------------------
BUG TEST

1. Open test file (Download link for large utf8 xml file). Note, that LPValue - LPStartValue = 15871446 for last line with extra char at end. 
2. Close Tab for this file and get **Out of memory** error

![3](https://cloud.githubusercontent.com/assets/22052292/18568270/18592f92-7ba5-11e6-9bc4-418c24a9717d.png)

**Comment by bonecode** [comment]
That fix will leave the last line out, if you set the Text. Try this:

Editor.Lines.Text := Editor.Highlighter.Info.General.Sample;

**Comment by delphioracle** [comment]
Yes, you are right.  My "FIX" is BUG.
I founded, why there is  Out of memory error while Tab Closing for Text with very long lines.
My new fix resolved this error and has very significantly reduced time of the Tab Closing.
I will upload it in the next comment soon.

**Comment by delphioracle** [comment]
[BCEditor.Editor.Base_BCEditor.Lines.zip](https://github.com/bonecode/TBCEditor/files/476623/BCEditor.Editor.Base_BCEditor.Lines.zip)

**Comment by bonecode** [comment]
Fixed it a little bit.
