### ISSUE TITLE
Fixed TBCEditorLines.GetTextStr optimization

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#474]
[BCEditor.Lines.pas.zip](https://github.com/bonecode/TBCEditor/files/477682/BCEditor.Lines.pas.zip)

Note: Length(FList^[i].Value) does more fast asm code then FList^[i].Value.Length
![code](https://cloud.githubusercontent.com/assets/22052292/18600350/cdd7744e-7c65-11e6-9439-e9751f667508.png)

**Comment by delphioracle** [comment]
![code2](https://cloud.githubusercontent.com/assets/22052292/18601195/22f81cf4-7c6a-11e6-85d9-2a06de8374ef.png)

**Comment by bonecode** [comment]
Thanks, I thought it might be like that.
