### ISSUE TITLE
Fixed additional optimization of often used code

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#475]
[Source.zip](https://github.com/bonecode/TBCEditor/files/478224/Source.zip)

As a result of common efforts in 3 days we achieved impressive result.
Saving of time, additional short-term memory allocation:

1. File loading 25%, 40%
2. Tab closing >80%, 100%
3. Get Text 40%, 100%

**Comment by bonecode** [comment]
Nice, thanks a lot.
