### ISSUE TITLE
First code folding collapse jumps the editor

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#48]
Open a file, scroll a bit downward, then collapse a region.
The editor will jump up, and the region will not be collapsed.

After that, if you attempt it again, it will work.

**Comment by bonecode** [comment]
Can you still repeat this? I can't.

**Comment by ngthach** [comment]
Steps to reproduce this issue:
- Move the caret to the top of editor by pressing CTRL+HOME
- Scroll down to the bottom of the editor (do not move the caret) by drag  & drop the scrollbar
- Click on any Collapse button
- The editor will scroll up to the caret position

**Comment by bonecode** [comment]
Nope, I still don't get it. Did you try my demo or your own fork? Is this XE problem?

Once I got an assert failure from here:

procedure TBCEditorFontStock.SetStyle(Value: TFontStyles);
...
  Assert(Index <= High(TBCEditorStockFontPatterns));

But I haven't got it again...

**Comment by EricGrange** [comment]
I had it in the precompiled 32bit binary (did not try the 64bit one), that
was after scrolling with the mouse wheel or dragging the scrollbar, with
the pascal highlighter on a smallish file (about 200 lines).

If you update the binary I will try again.
Le 15 mai 2015 5:41 PM, "Lasse Rautiainen" <notifications@github.com> a
écrit :

**Comment by bonecode** [comment]
I updated it about 40 minutes ago.

**Comment by ngthach** [comment]
I sent you a video to demo this issue (via wetransfer.com) Please check your Inbox or Junk folder!

**Comment by ngthach** [comment]
Steps to reproduce this issue:
- Open BCEditor.Editor.CodeFolding.Ranges.pas with TBCEditorDemo
- Click end of the line 9: BCEditorCodeFoldingRange = class; { Click here}  
- Scroll the editor downward (dont move the caret) to the end of the editor
- Click Collapse button at the line 331
- The editor will scroll up

**Comment by bonecode** [comment]
Thanks, now I got it.

**Comment by ngthach** [comment]
I use this one : http://www.torry.net/vcl/mmedia/video/PSC.v5.2.3.0.zip

**Comment by bonecode** [comment]
Ok, I will give it a try. Looks simple enough. And this bug is fixed.
