### ISSUE TITLE
Fold all from last line 

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#489]
If editor has many lines of code and many items that can be folded, 
then if you scroll down to the bottom of editor and try to execute "fold all" you will see blank page, until you do something that refresh it, like scroll up.

**Comment by bonecode** [comment]
I can't repeat this in the EditBone but I will test this later.

**Comment by bonecode** [comment]
I can't repeat this with the latest source. Send me a file that will fail, if this is still an issue.

**Comment by piker00** [comment]
Sorry for late I was busy.
Here is sample file, and video with last compiled bonecode.

[frmMainUnit.zip](https://github.com/bonecode/TBCEditor/files/506972/frmMainUnit.zip)

![2](https://cloud.githubusercontent.com/assets/11677236/19049883/f5456eee-89b4-11e6-863a-5415f70d6fb9.gif)

**Comment by bonecode** [comment]
Thanks, I got it.

**Comment by bonecode** [comment]
Fixed.
