### ISSUE TITLE
Wrong unit name in one or more packages

### ISSUE THREAD

**Issue by Manhunter07** [bonecode/TBCEditor#492]
Hello,
I found a bug which prevents BCEditor from being installed on XE5 and possibly some other Delphi versions using the provided packages. The issue is a unit naming bug in the runtime package.
The bug is on line 96 in "BCEditor.Delphi.XE5.Runtime.dpk" and possibly some other packages. The line currently looks like this:
`BCEditor.Editor.SyncEdit in '..\Source\BCEditor.SyncEdit.pas',`,
which will (reasonably) cause errors with "file not found" etc.
The solution is, to add the correct unit name after the "in". The correct line should be:
`BCEditor.Editor.SyncEdit in '..\Source\BCEditor.Editor.SyncEdit.pas',`
Please add this fix to the buggy packages so that they BCEditor can be installed on the corresponding Delphi versions.

**Comment by bonecode** [comment]
It is already fixed. See https://github.com/bonecode/TBCEditor/blob/master/Packages/BCEditor.Delphi.XE5.Runtime.dpk

You must be using quite old version.

**Comment by Manhunter07** [comment]
Well, I was using the latest repository I pulled a few minutes before. Strange it was not changed there...
But thanks anyhow. What I can say is that I first pulled it one or a few months ago and at that time, the bust must definitly have been there. I have no idea why my VCS did not update the file...
Thanks however.
