### ISSUE TITLE
Search fail after firs match if EntireScope set to True

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#493]
Subj

**Comment by bonecode** [comment]
Fixed.

**Comment by piker00** [comment]
Hmmm. I got last trunk, bug still present ...

**Comment by bonecode** [comment]
I am not sure how you're using the search. I tested this with EditBone and it was working.

What I changed was that if soEntireScope is set and the search text is changed, the caret will be set to zero position. That should do the trick. Otherwise search starts from the text caret position.

**Comment by piker00** [comment]
Aha, found mistake, my code was like: 
```
BCEditor.Search.SearchText := Text;
BCEditor.FindNext;
```
When in demo you are using
```
  if BCEditor.Search.SearchText <> Text then
    BCEditor.Search.SearchText := Text 
else
    BCEditor.FindNext;
```
Ok. Now this solved.
