### ISSUE TITLE
Suggestion for demo

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#494]
Instead of use ObjectInspector from EhLib
I suggest to use free one - > https://github.com/MahdiSafsafi/zcontrols
This will let me build demo :] 

or 

Make two demos with different Inspectors

**Comment by bonecode** [comment]
Wow, that looks awesome. I will change EhLib to that.

**Comment by bonecode** [comment]
Ouch, a lot of warnings and hints. It is always a bad sign...

**Comment by bonecode** [comment]
I guessed right. Poor implementation. A lots of problems when FastMM is running. Sorry, I won't use this.

**Comment by bonecode** [comment]
I will try TJvInspector from Jedi.

**Comment by bonecode** [comment]
Nah, the code is so bloated, I can't rip the control easily. I won't install JVCL because 99% of the controls are useless. So, the EhLib stays as long as I can find a working control to replace it that does not require installing of hundreds of useless controls and components.

**Comment by bonecode** [comment]
Sometimes you just have to bend the knee. I replaced TObjectInspectorEh with TJvInspector. Looks better and works with AlphaSkins.
