### ISSUE TITLE
Feature: Fold\Unfold selected by level

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#496]
Subj

**Comment by bonecode** [comment]
This is already implemented. See FoldAllByLevel and UnfoldAllByLevel.

**Comment by piker00** [comment]
Already but it affect everything not only selection ....

**Comment by bonecode** [comment]
Fixed.

**Comment by piker00** [comment]
I think if some block is selected then level 0 must begin from selection and not from entire document order.
For now if we have:
```
procedure RootLevel;
begin
   procedure Level1;
   begin
   //
  end;
end;
```
to apply foldByLevel to selection of **procedure Level1;** start level must be 1, in my opinion it must be 0, because some times it's difficult to know at what level you are.

What do you think ?

**Comment by bonecode** [comment]
Makes sense. Fixed.
