### ISSUE TITLE
Fold by level same problem as issue 489

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#497]
https://github.com/bonecode/TBCEditor/issues/489
![2](https://cloud.githubusercontent.com/assets/11677236/19181129/9899e6d6-8c73-11e6-92e0-d317ffcd1f48.gif)

by the way do reading comments in closed issues ?
github.com/bonecode/TBCEditor/issues/493
github.com/bonecode/TBCEditor/issues/496

**Comment by bonecode** [comment]
Fixed this issue.

Sure, I get notifications via e-mail. I will reopen issues, if needed.
