### ISSUE TITLE
Install in Delphi Berlin

### ISSUE THREAD

**Issue by EpicJhon** [bonecode/TBCEditor#507]
Hello,
I can not install the package for delphi berlin, always get this error:

![image](https://cloud.githubusercontent.com/assets/2496458/19841266/b9393944-9ed6-11e6-8385-2d15cebdc292.png)

I am trying to install the version 1.8.1

Thank you.

**Comment by bonecode** [comment]
Did you install it to C++ Builder first? Error message says that the same unit is also contained in package BCEditor.CBuilder.Berlin.Designtime.
