### ISSUE TITLE
Devexpress Support

### ISSUE THREAD

**Issue by aliyesiloglu** [bonecode/TBCEditor#508]
![ekran alintisi](https://cloud.githubusercontent.com/assets/6508118/19904718/7c787356-a07c-11e6-80d8-3c38f5f1420d.PNG)

Hi, 
TBCEditor is amazing..
Devexpress support would be nice..

best regards

**Comment by bonecode** [comment]
I don't have a license for Devexpress. It is very expensive and without donations this will never happen. But the support should be quite easy to implement. See how AlphaSkins support is implemented.

**Comment by piker00** [comment]
Dear bone if you need, I can give you license for devX for free ;)
And I'm agree with aliyesiloglu that **Devexpress support would be nice.**
at least support for dxPopupmenu.

**Comment by piker00** [comment]
and dxSpellChecker

**Comment by aliyesiloglu** [comment]
and TcxScrollbar

**Comment by bonecode** [comment]
So, the scrollbar is not a skinning solution? Not a good idea.

**Comment by bonecode** [comment]
I did investigate the code and have decided not to implement Devexpress support. So, who needs it, can do it by itself or pay someone to do it. I rather spend my free time to things I need and like. When I am paid, I do what other people need and like. :) But I think I talked with somebody lately who already implemented the scroll bar support. Maybe he would like to share it...
