### ISSUE TITLE
Assertion Failure

### ISSUE THREAD

**Issue by aliyesiloglu** [bonecode/TBCEditor#509]
![ekran alintisi](https://cloud.githubusercontent.com/assets/6508118/19949048/4d723ac4-a158-11e6-9ea4-2dc95f1fa016.PNG)

![av](https://cloud.githubusercontent.com/assets/6508118/19949104/9e8466d0-a158-11e6-8f52-40735e5450c4.PNG)

**Comment by bonecode** [comment]
Does it happen when dropping the control on the form? Is it the latest version 1.8.1? Which Delphi version?

**Comment by aliyesiloglu** [comment]
Yes, Delphi 10 Seattle

**Comment by bonecode** [comment]
I can't repeat this. Are you using the latest release version 1.8.1?

**Comment by aliyesiloglu** [comment]
Yes.. Im using the version 1.8.1 


```
unit BCEditor.Consts;
interface
uses
  Vcl.Graphics;
type
  TBCEditorCharSet = set of AnsiChar;

const
  BCEDITOR_VERSION = '1.8.1';

...
```
![ekran alintisi](https://cloud.githubusercontent.com/assets/6508118/19975783/ee3ce2d6-a1f5-11e6-8962-5ebede35619f.PNG)

**Comment by bonecode** [comment]
In this example it was working? https://github.com/bonecode/TBCEditor/issues/508

Or did you create it run-time?

**Comment by aliyesiloglu** [comment]
The error occurs at design time in Delphi

**Comment by bonecode** [comment]
Yes, I know. Did you comment out Loaded?

**Comment by aliyesiloglu** [comment]
Yes its..

**Comment by bonecode** [comment]
I just fixed design-time painting. Try the latest trunk.

**Comment by bonecode** [comment]
I made another fix for CanFocus.

**Comment by aliyesiloglu** [comment]
Hi, 

Steps : 

1. Select the TBCEditor..
2. TBCEditor.Minimap.Indicator.Options.ioUseBlending  = TRUE

Delphi Version : 10.1 Berlin


![1 1](https://cloud.githubusercontent.com/assets/6508118/19991524/bcc9eebc-a23e-11e6-935a-be0aac0ae5ee.PNG)
![1](https://cloud.githubusercontent.com/assets/6508118/19991525/bcca8d18-a23e-11e6-8f20-a21e51c03ef1.PNG)

**Comment by bonecode** [comment]
Fixed.

**Comment by aliyesiloglu** [comment]
Thank you so much
