### ISSUE TITLE
Mouse drag selection should ignore soPastEndOfFileMarker

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#51]
When extending a selection with the mouse and soPastEndOfFileMarker is set, the automatic scrolling that happens when you extend downward should ignore soPastEndOfFileMarker.

This would be consistent with other editors, and usually when selecting & scrolling it is common to overshoot a bit. In the above case, this leads to all code quickly disappearing from view.

**Comment by bonecode** [comment]
Fixed.

**Comment by EricGrange** [comment]
Issue is still present AFAICT
