### ISSUE TITLE
Advanced Search and Replace with \n \r \t \0 \x...

### ISSUE THREAD

**Issue by piker00** [bonecode/TBCEditor#510]
\n  new line (LF)
\r   carriage return (CR)
\t   tab character
\0  null character
\xddd special character with code ddd

**Comment by bonecode** [comment]
Regular expression engine will handle this after I make some changes. Now it searches line by line which is wrong.

**Comment by bonecode** [comment]
Search is fixed to support multiple lines. Normal search engine supports line break (\n). Regular expression uses carriage return (\r) and line feed (\n) combination.
