### ISSUE TITLE
New feature - support for DevExpress skins/contols, not just VLC/AlphaSkins

### ISSUE THREAD

**Issue by testuser220** [bonecode/TBCEditor#513]
DevExpress is probably the most widely used library for professional VCL development
[(https://www.devexpress.com/)]

A great many products support the DevExpress, i.e TRichView.

**Comment by paresy** [comment]
This was already discussed and dismissed in #508

**Comment by testuser220** [comment]
Too bad :) Please email me how much will it cost to add the minimum support of the cxScrollBar (only) to your Editor Control, so that it shows the skinned scroll bars. That should do it.

**Comment by bonecode** [comment]
My precious free time is not for sale. But like I said, somebody already did that scroll bar fix for DevExpress. If you read this, please consider to share the solution. I can merge it to sources. I don't have a legal license for the latest DevExpress, so I am skipping this hands down.

**Comment by testuser220** [comment]
Lasse,

 

I finally got a few hours to research the skinned Scrollbar issue, and managed to create an example with DevExpress skins. The solution is generic and simple – just use external Scrollbars (of any type) instead of having the built-in scrollbars of TWinControl. It can work even with the VCL/AlphaSkin style scrollbars and no need for complicated Style / WinAPI message hooks (I broke my head trying to figure out how they work, and they turned out to be useless anyway).

 

Only BCEditor.Editor.Base.pas was affected by this change.

 

Here is the attached screenshot and the demo project. I hope this helps – feel free to share/include.

 

Good luck with further development!

 

Thanks,

Art

**Comment by buddyman83** [comment]
Unfortunately theres no screenshot or project attached. This would be great news if DevExpress would be supported... 👍

**Comment by bonecode** [comment]
Send me your BCEditor.Editor.Base.pas. I can review the code and merge it.

**Comment by testuser220** [comment]
Did you receive the DevExpress.zip file attached to my previous message? It contained the screenshot and the sources and the demo project.

 

I am re-attaching it again here.

**Comment by bonecode** [comment]
Nope, it is not there. Send it to lasse@bonecode.com

**Comment by testuser220** [comment]
I just sent to  lasse@bonecode.com

 

Please confirm the receipt.

**Comment by bonecode** [comment]
Yes, I got it, thanks. I will review it later in the evening.
