### ISSUE TITLE
Vertical Scrollbar wrong after commit #6f9930d

### ISSUE THREAD

**Issue by paresy** [bonecode/TBCEditor#515]
After removing the "CanFocus" in the "if" clause everything is fine again. Otherwise the scrollbar is always shown even if you have only 5 lines. And it is always scrollable.

Do you know why you added this? Do i need to make a proper example to highlight the problem?

**Comment by bonecode** [comment]
Hmm, I don't see it. 

![image](https://cloud.githubusercontent.com/assets/11475177/20663335/bba899dc-b55f-11e6-9c46-4ce223d3fd48.png)

What is the line number of the code you are referring?

**Comment by bonecode** [comment]
I can't repeat your problem. SizeOrFontChanged is still called too many times. I need to refactor this later. I have a lot of other things to refactor before that.
