### ISSUE TITLE
DoWordLeft and previouswordposition

### ISSUE THREAD

**Issue by thecupofcoffee** [bonecode/TBCEditor#516]
I think that PreviousWordPosition should be checked only if the char position is at 1. If not than the caret pos is at the end of the prev word.

BCEditor.Editor.Base line 1202

if (AreTextPositionsEqual(LCaretNewPosition, LTextCaretPosition) or (ACommand = ecWordLeft)) and ((LTextCaretPosition.Char = 1) and (LCaretNewPosition.Char = 1)) then
	  LCaretNewPosition := PreviousWordPosition;

Regards

**Comment by bonecode** [comment]
I see the problem but that's not the correct fix. This will be fixed in version 1.9. I won't upload my changes until my refactoring is done.

**Comment by thecupofcoffee** [comment]
Well, thats not what I meant but ok - I just leave it in my code tree. Try to do ctrl + left in this memo of github.

Some illustration where | is the caret - [This is an test|] -> ctrl + left -> [This is an |test]. Without the above of mine it behaves like [This is an| test]

Regards, and no offence. ;)

**Comment by bonecode** [comment]
None taken. Anyone can do what ever they like and need. I don't mind at all. I rather always try to understand the problem and fix the real reason than make an ugly hack over the problem. 

Fixed.

**Comment by thecupofcoffee** [comment]
Sure, it`s mit license anyway. I just point at some none standard behaviour ;)
