### ISSUE TITLE
DoBackspace bug.

### ISSUE THREAD

**Issue by thecupofcoffee** [bonecode/TBCEditor#517]
If you mark an line, and go to the character position 1 in the next line - hit backspace.

  procedure UpdateMarks(AMarkList: TBCEditorMarkList);
  var
    LIndex: Integer;
    LMark: TBCEditorMark;
  begin
    for LIndex := 0 to AMarkList.Count - 1 do
    begin
      LMark := Marks[LIndex];
     
Regards

**Comment by bonecode** [comment]
Fixed.
