### ISSUE TITLE
Code-Folding in LUA

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#520]
found little bug in lua highlighting:

![2016-12-20 15_59_22-coplaning cockpit editor](https://cloud.githubusercontent.com/assets/9843149/21355198/60090f92-c6cd-11e6-803d-e06508465e76.png)

can be easily fixed by adding

` {
				  "OpenToken": "[[",
				  "CloseToken": "]]",
				  "RegionType": "MultiLine"
			   }`

to lua highlighter json

**Comment by buddyman83** [comment]
Hmm, seems theres something more wrong...

the fix mentioned above works but adding this

`{
                  "OpenToken": "--[[",
                  "CloseToken": "]]",
                  "RegionType": "MultiLine"
               }`

to "SkipRegion" will be ignored.

Also the following added to FoldRegion doesn't work

`               {
                  "OpenToken": "--[[",
                  "CloseToken": "]]"
               },
               {
                  "OpenToken": "[[",
                  "CloseToken": "]]"
               }`

Would love to get the same behaviour as in notepad++ :-)))

![2016-12-20 17_28_13-_new 1 - notepad](https://cloud.githubusercontent.com/assets/9843149/21358701/c926b39c-c6d9-11e6-8cfc-15ee6f316a6d.png)

**Comment by bonecode** [comment]
Fixed.
