### ISSUE TITLE
"WordWrap.Indicator.Glyph does not exist"

### ISSUE THREAD

**Issue by aliyesiloglu** [bonecode/TBCEditor#521]
Delphi 10.1 (upd2) Berlin
TBCEditor 1.9.0 (dev)

![tbcediyor](https://cloud.githubusercontent.com/assets/6508118/21548414/df2fc152-cdf4-11e6-907a-5e977d4d0304.PNG)

**Comment by bonecode** [comment]
WordWrap.Indicator is not Glyph anymore but Bitmap since version 1.9.0 which is not released yet. 
 
Note! Version 1.9.0 is in development (dev) and changes are inevitable.
