### ISSUE TITLE
XML Code folding does not work properly

### ISSUE THREAD

**Issue by GooD-NTS** [bonecode/TBCEditor#522]
For some XML files code folding does not work properly, it can fold only few nodes.
![image](https://cloud.githubusercontent.com/assets/18674940/21698597/c0554a22-d3a8-11e6-877c-8cff9ac84a78.png)

Here is the example file:
[Test.txt](https://github.com/bonecode/TBCEditor/files/688460/Test.txt)

**Comment by bonecode** [comment]
Fixed.

**Comment by GooD-NTS** [comment]
Sorry to bring this one again, but I found another scenario where XML Code folding does not work properly.
![test-xml-bug](https://cloud.githubusercontent.com/assets/18674940/21749550/9abf5acc-d5b1-11e6-93b3-078f49e5cd42.png)

Here is the example file:
[test-xml.txt](https://github.com/bonecode/TBCEditor/files/692068/test-xml.txt)

**Comment by bonecode** [comment]
Fixed.
