### ISSUE TITLE
 acntDX10Berlin

### ISSUE THREAD

**Issue by limelect** [bonecode/TBCEditor#523]
acntDX10Berlin is required but is not free.
So i cannot compile
C:\Program Files (x86)\Embarcadero\Studio\LimLib\bonecode\BCControls\Packages\BCControls.Delphi.Berlin.Runtime.dproj

**Comment by bonecode** [comment]
TBCEditor control does not require AlphaSkins to be installed. Only demo does but it is nothing but a show case. Install package, drop the control on a form, load highlighter and color. That is the simplest demo you can have, I don't need to create a demo project for it. If the control does not explain itself, I have failed.

FYI: BCControls are controls and components for bonecode software. Most of these are wrappers to enable single point bug fixing and customizing.

**Comment by limelect** [comment]
Sorry you are right
