### ISSUE TITLE
Find a TBCEditor bug

### ISSUE THREAD

**Issue by hksoobe** [bonecode/TBCEditor#524]
function TForm1.NewPageTab(cxPC_CodeEdit: TPageControl; FileName: string): TTabSheet;
var
  T: TTabSheet;
  E: TBCEditor;
begin
  T := TTabSheet.Create(cxPC_CodeEdit);
  Result := T;
  T.Caption := FileName;
  E := TBCEditor.Create(T);
  E.Align := alClient;
  E.Parent := T;   **//<-- in v1.9.0 Here's the question . If I use Panel1 can be normal**
  E.Highlighter.LoadFromFile(ExtractFilePath(ParamStr(0)) + 'Configs\EditerHH\Highlighters\Lua.json');
  E.Highlighter.Colors.LoadFromFile(ExtractFilePath(ParamStr(0)) + 'Configs\EditerHH\Colors\Default.json');      //Twilight
  E.Lines.Text := E.Highlighter.Info.General.Sample;
  T.PageControl := cxPC_CodeEdit;
  cxPC_CodeEdit.ActivePageIndex := cxPC_CodeEdit.PageCount - 1;
  if E.CanFocus then E.SetFocus;
end;

v.1.9.0
![image](https://cloud.githubusercontent.com/assets/6091308/21750697/442c005a-d5f4-11e6-8232-e5ce6d4d4de9.png)

1.7.1
Can normally display
![image](https://cloud.githubusercontent.com/assets/6091308/21750709/7d434c54-d5f4-11e6-92d7-b6483be3d56d.png)

Please tell me how to modify

**Comment by bonecode** [comment]
This is fixed in trunk now. 

If you can't use the latest trunk version, you can either move this line "T.PageControl := cxPC_CodeEdit;" before "E.Highlighter.LoadFromFile..." line or comment out the last line from TBCBaseEditor.LinesInserted procedure.

**Comment by hksoobe** [comment]
thank you
