### ISSUE TITLE
Combined chars error

### ISSUE THREAD

**Issue by thachngopl** [bonecode/TBCEditor#525]
Test string: Đây là Tiếng Việt
:)

**Comment by bonecode** [comment]
What is the error? Works, if the encoding is set to unicode.

**Comment by thachngopl** [comment]
Hi,

Please copy & paste these lines into the editor.

Đây là tiếng Việt
Đây là tiếng Việt

![capture](https://cloud.githubusercontent.com/assets/16706272/21768080/4c2d3812-d6aa-11e6-9542-9b887e0cb945.PNG)

**Comment by bonecode** [comment]
Fixed.
