### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/TBCEditor#526]
Using a non-fixed width font I found some word wrap bugs where words are wrapped in-word instead of at the proper place/space character.

![wordwrap](https://cloud.githubusercontent.com/assets/7662186/21775542/2c270e74-d65c-11e6-8c95-bed3625ef455.png)

**Comment by bonecode** [comment]
BreakWords option will be added.

**Comment by AlbertWiersch** [comment]
Thank you! What is the expected time for this to be added?

**Comment by bonecode** [comment]
This is currently under development. It will be done when it is done. I need to work 8 hours everyday and after that I have time for my hobbies and this is just one of my many hobbies.

**Comment by AlbertWiersch** [comment]
Thanks. I understand. I’ll switch back to my old editor component and try again for the next update.

 

--
Albert Wiersch
AI Internet Solutions LLC
support@htmlvalidator.com
https://www.htmlvalidator.com/

**Comment by bonecode** [comment]
Fixed, it was much easier than I thought.

**Comment by bonecode** [comment]
Fixed.

**Comment by AlbertWiersch** [comment]
Great. I’ll give it a try. Thank you!

 

--
Albert Wiersch
AI Internet Solutions LLC
support@htmlvalidator.com
https://www.htmlvalidator.com/
