### ISSUE TITLE
Trouble with AutoIt Highlighter

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#528]
Hi, i found some issues with the AutoIt Highlighting JSON.

- The multiline comment tags #cs ... #ce are not supported
   I added it `               {
                  "Type": "BlockComment",
                  "Attributes": {
                     "Element": "Comment"
                  },
                  "TokenRange": {
                     "Open": "#CS",
                     "Close": "#CE"
                  }
               },`
    and it works but code folding doesn't really work. the lines first show up when i enter sth. like "wend". Maybe the # is the reason?

- Same problem with the tags #Region .... #EndRegion 

Example in Notepad++

![bildschirmfoto 2017-01-09 um 21 26 27](https://cloud.githubusercontent.com/assets/9843149/21782072/5b8c87d8-d6b2-11e6-8193-810a0cf5ad4d.png)

**Comment by bonecode** [comment]
Fixed highlighter and code.

**Comment by buddyman83** [comment]
Thanks for quick support, but unfortunately there are still some issues. Seems to have problems when #Region is followed by additional text.

TBCEditor compared to SciTe-Editor
![2017-01-11 08_27_23-autoit rad studio 0 1](https://cloud.githubusercontent.com/assets/9843149/21842057/54ab5cc6-d7e5-11e6-98a9-33313aa26571.png)

Also it seems there is a difference between typing the text by keyboard or pasting from clipboard (or assigning to Text property).

**Comment by buddyman83** [comment]
`Heres the Code I use to test`

**Comment by bonecode** [comment]
Fixed.

Because there are code folding range:
```
{
   "OpenToken": "DO",
   "CloseToken": "UNTIL"
}
```
This "Includes - DO not edit" started that range and other problems were caused by that. I added "OpenTokenBreaksLine" option that breaks the scanning for the line after the open token is found.
