### ISSUE TITLE
CompletionProposal - 2nd ShortCut and Events

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#529]
Hi,

would it be possible to add an event which is fired after an item in the proposal window has been selected? And maybe an event which is triggered when proposal window has been dismissed without selection.

And it would be nice to have a 2nd shortcut and get an info in the BeforeCompletion... event which shortcut has been used.

![c825ab137b55066666d821685ef95e64](https://cloud.githubusercontent.com/assets/9843149/21866272/d1ff8af8-d849-11e6-9f69-cb6b11958117.jpg)

**Comment by bonecode** [comment]
I added OnCompletionProposalCanceled and OnCompletionProposalSelected events. I also added SecondaryShortCut.
