### ISSUE TITLE
Editor goes away when Cursor-Right-Key is used in completion proposal window

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#530]
Easy to reproduce, when the completion proposal window is shown, hit the cursor-right-key. 
The complete editor instance will hide.

Its only the right-key.

PS: thank u so much for the new events. with these, i can implement a rudimentary code completion myself.

**Comment by bonecode** [comment]
It works like it should. Try it for example in Delphi. The focus is in the editor. The completion proposal won't hide, if there is a word like:

![image](https://cloud.githubusercontent.com/assets/11475177/21923496/2581793c-d97d-11e6-8c7c-ec208376c6ac.png)

**Comment by buddyman83** [comment]
Hmm, although i'm using C++ Builder i tried it in Delphi with same results.
Just dropped a TBCEditor object, enter a new line, open the proposal window with CTRL-SPACE and then Cursor-Right. It only happens when the end of line is reached. 

![2017-01-13 09_51_30-form32](https://cloud.githubusercontent.com/assets/9843149/21923736/0345aeee-d976-11e6-8a19-5d2283d92758.png)

**Comment by buddyman83** [comment]
I have fixed it quick&dirty with

```
void __fastcall TForm31::BCEditor1CompletionProposalCanceled(TObject *Sender)
{
   Memo1->Lines->Add ("BCEditor1CompletionProposalCanceled()");

   if (!BCEditor1->Visible)
   {
        Memo1->Lines->Add ("need to reset visible property");
	BCEditor1->Visible = true;
	BCEditor1->SetFocus();
   }
}
```

**Comment by bonecode** [comment]
Aah, I didn't read it properly. So, the whole editor will hide. That must be a bug. I will check it after work.

**Comment by bonecode** [comment]
Fixed.
