### ISSUE TITLE
Exception when hitting Return in an empty editor.

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#533]
Quick&Dirty workaround is to call **clear** method while initialization.

**Comment by bonecode** [comment]
Is your own OnCompletionProposalSelected code causing this? I can't repeat.

**Comment by buddyman83** [comment]
No, i don't mean the proposal window, its the editor itself.

Steps to reproduce:
- drop a TBCEditor on form
- in inspector clear the lines property (so the editor will be empty)
- run the app
- with editor focused, hit enter key

**Comment by bonecode** [comment]
Ah, the editor is not useful without a highlighter. At least the Text highlighter must be loaded. But sure, it should not give an AV.

**Comment by bonecode** [comment]
Fixed.
