### ISSUE TITLE
Some "nice to haves" in completion proposal window

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#534]
Hi, here some ideas and nice2haves for the proposal window:

- enabled scroll wheel
- show column headers with title information
- different fonts for columns
- different images for items

:)

**Comment by bonecode** [comment]
Here you are...

![image](https://cloud.githubusercontent.com/assets/11475177/21964994/f163db16-db5e-11e6-8b18-259845fc629b.png)

Scroll wheel enabled, columns have now font, items, and title properties. Font was removed from CompletionProposal property and Images added.

**Comment by buddyman83** [comment]
You are awesome! Thank you so much!!
