### ISSUE TITLE
Suggestion: Hide scrollbars when no actual scroll is available

### ISSUE THREAD

**Issue by GooD-NTS** [bonecode/TBCEditor#536]
When **Scroll.Bars = ssBoth** and **Scroll.Options does not have soPastEndOfLine**, it would be nice to have option to hide horizontal scrollbar when there is nothing to scroll horizontally. Same for vertical scroll.

Basically, scrollbars must be shown if only there is something to scroll even when Scroll.Bars is set to ssBoth.

**Comment by bonecode** [comment]
Fixed.
