### ISSUE TITLE
OnBeforeCodeCompletionExecute

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#537]
Hi,

i'm not sure if i'm using it right..

When triggered, i first _clear_ the **AItems** and then add matching items to AItems and to a second columns ItemList so they will be displayed.

But... the _clear_ leads to disappear of all the other collected strings from the text (cpoParseItemsFromText).

If i do not _clear_, the content of the second column will be messed up with the parsed items.

I think it would be nicer to control in the BeforeCodeCompletionExecute event, which items will finally be displayed: Only mine,  only the parsed ones or both ...

In addition, it would be nice to disable the import of the predefined keywords from the highlighter json.

:)

**Comment by bonecode** [comment]
I added cpoAddHighlighterKeywords option for completion proposal. I also fixed the BeforeCompletionProposalExecute event and changed the AItems parameter to AColumns.

I tried it like this, didn't test much thou...

```
procedure TMainForm.EditorBeforeCompletionProposalExecute(Sender: TObject;
  AColumns: TBCEditorCompletionProposalColumns; const AInput: string; const AKey: Word; const AShift: TShiftState);
var
  LItem: TBCEditorCompletionProposalColumnItem;
begin
  inherited;
  LItem := AColumns[0].Items.Add;
  LItem.Value := 'Test';
end;
```

**Comment by buddyman83** [comment]
Works like a charm!

Maybe some more suggestions ^^

- Background color for title bar
- ImageIndex for the text parsed items
- Show parsed items in second place
- Show columns content as hint when proposal window is to small

**Comment by bonecode** [comment]
I added Colors property for the column title. Parsed text items already have ImageIndex.

What do you mean by this "second place"? Column items can also be Inserted, if you want to insert them before parsed items.

That hint could be an option...

**Comment by buddyman83** [comment]
Ah of course, inserting instead adding does the trick :)

How can i set an default ImageIndex for the parsed text items? Or do i have to iterate over them and set it for each?

Would be nice to have the header and item line height as property. The font size for the first column seems to be ignored. Also I've set all columns to the same font size, they are display different.



![bildschirmfoto 2017-01-16 um 17 42 36](https://cloud.githubusercontent.com/assets/9843149/21991641/ac1aa4d0-dc13-11e6-97e9-39c519d4ad3c.png)

**Comment by bonecode** [comment]
Yes, just iterate them and set ImageIndex. I could also add DefaultImageIndex but I don't know is that a good idea...

Give me those font names and sizes. I can figure out what is the best way to implement this.

**Comment by buddyman83** [comment]
I used calibri size 11

**Comment by bonecode** [comment]
Should be fixed now.

**Comment by buddyman83** [comment]
Still looks strange, also the selected row isn't highlighted completely as before.

Font is Calibri 11, the first column Bold, the second not.

![2017-01-25 17_32_00-autoit rad studio 0 1](https://cloud.githubusercontent.com/assets/9843149/22299423/50835e24-e324-11e6-9049-f3753ae30e53.png)

**Comment by bonecode** [comment]
Painting fixed and I added cpoUseHighlighterColumnFont option. Column font and size can be also imported from color file.
