### ISSUE TITLE
File not found: BCEditor.Delphi.XE4.Designtime_Icon.ico

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/TBCEditor#542]
I'm getting the following error when trying to install the Delphi XE4 package into the IDE:

[BRCC32 Error] BCEditor.Delphi.XE4.Designtime.vrc(60): file not found: BCEditor.Delphi.XE4.Designtime_Icon.ico

Could you please include the missing ico file? Thanks!

**Comment by bonecode** [comment]
This is a control, not an application. Icon is not needed. I removed it from the project file.
