### ISSUE TITLE
Error in module : CONTAINS clause is incorrect

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/TBCEditor#543]
When I try to load and compile the BCEditor.Delphi.XE4.groupproj project group, I get the following error:

Unable to load project C:\Users\Thomas\Documents\GitHub\TBCEditor\Packages\BCEditor.Delphi.XE4.Runtime.dproj
Error in module : CONTAINS clause is incorrect

followed by this error message box:

Unable to create project C:\Users\Thomas\Documents\GitHub\TBCEditor\Packages\BCEditor.Delphi.XE4.Runtime.dproj. This project will be removed from the project group.

**Comment by ThomasJaeger** [comment]
Looks like it was missing a comma at the end of the line, should be:

  BCEditor.Editor.TokenInfo.PopupWindow in '..\Source\BCEditor.Editor.TokenInfo.PopupWindow.pas',

**Comment by ThomasJaeger** [comment]
I reverted back to a previous commit that did not include the TokenInfo code.

**Comment by bonecode** [comment]
Package is fixed.

**Comment by ThomasJaeger** [comment]
Thank you!
