### ISSUE TITLE
Error creating form: Ancestor for 'TBCBaseForm' not found.

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/TBCEditor#544]
I'm getting error:

Error creating form: Ancestor for 'TBCBaseForm' not found.

When loading the demo project.. I do have the \Common\Source in my library path. Any idea why it would not work? I just would like to see a finished EXE of the demo app. I can take it from there.

**Comment by ismailozenc** [comment]
any news on that one?

**Comment by ismailozenc** [comment]
ok solved it

add TBCEditorDemo.Forms.Main.pas to your project

**Comment by ismailozenc** [comment]
ok that solves the problem but leads to an other one

**Comment by ismailozenc** [comment]
ok to solve that problem you need to add; BCCommon.Form.Base.pas to your project

but in my case even after that the demo does not run properly

**Comment by bonecode** [comment]
Create a project group and add TBCEditorDemo and BCEditor, BCComponents, BCControls, and BCCommon packages into it.

**Comment by ThomasJaeger** [comment]
Ok, now I'm getting this error when trying to compile  the demo source:

[dcc32 Error] TBCEditorDemo.Forms.Main.pas(405): E2001 Ordinal type required

This is at line:

  ObjectInspector.AddUnlistedProperties(['Ctl3D', 'CustomHint', 'Hint', 'HelpContext', 'HelpKeyword', 'HelpType',
    'ImeMode', 'ImeName', 'ParentColor', 'ParentCtl3D', 'ParentCustomHint', 'ParentFont', 'ParentShowHint', 'ShowHint']);

**Comment by bonecode** [comment]
I added ifdef. I don't even understand that bug. It is fixed in later Delphi versions.

**Comment by ThomasJaeger** [comment]
No problem, thanks a lot for your help!
