### ISSUE TITLE
ImagesDataModule missing

### ISSUE THREAD

**Issue by ismailozenc** [bonecode/TBCEditor#545]
When i compile the demo i am getting a

Module 'MainForm' links to module 'ImagesDataModule' which cannot be found in the current project error and cant find that file any where

appearently there is a data module with image lists to help skins for the menus to appear but it is not present with the demo source code. 

if you ignore the image the demo runs without any of the menus

**Comment by bonecode** [comment]
If you read the README.md:

Demo source build requires

AlphaSkins (commercial)
Common
BCControls

ImagesDataModule is found from Common.
