### ISSUE TITLE
Change localization individually at runtime

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#547]
Would be nice to be able to set the few translation strings at runtime.
I'm using ini-files with the strings so the user can translate them himself. but as far as i can see the strings (i.e. "Top line") are not editable at runtime.

**Comment by bonecode** [comment]
Those are resourcestrings. So, you can hook and change them at run-time. This is how I have done it in EditBone:

```
procedure HookResourceString(AResStringRec: PResStringRec; ANewStr: PChar);
var
  OldProtect: DWORD;
begin
  VirtualProtect(AResStringRec, SizeOf(AResStringRec^), PAGE_EXECUTE_READWRITE, @OldProtect);
  AResStringRec^.Identifier := Integer(ANewStr);
  VirtualProtect(AResStringRec, SizeOf(AResStringRec^), OldProtect, @OldProtect);
end;

HookResourceString(@SBCEditorScrollInfoTopLine, 'What ever...');
```

**Comment by buddyman83** [comment]
Thank you, it works :)
