### ISSUE TITLE
Best way to detect text changes by user

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#548]
Hi, whats the best way to detect "real" changes by user?
I mean only when the user types or deletes something.

I would love an event which is triggered only once until the Modified property is set to false.

**Comment by bonecode** [comment]
I added OnModified event that is triggered always when modified goes true.

**Comment by buddyman83** [comment]
Hi, thank you but i think its still too hyperactive.

Just clicking in the editor will fire the event, also moving the cursor or selecting sth.

**Comment by bonecode** [comment]
I can't repeat. Are you sure?

**Comment by bonecode** [comment]
Ah, indeed...

```
procedure TBCBaseEditor.UpdateModifiedStatus;
begin
  SetModified(UndoList.ChangeCount > 0);
end;
```

**Comment by buddyman83** [comment]
I've done the following...

- Create a new project
- Drop an BCEditor, a Memo and a Timer with Interval 2sec on form
- When OnModified is triggered, add a line to the Memo and enable the timer
- When OnTimer is triggered, disable the timer and set BCEditor.Modified to false
- Click into the editor and type something, the OnModified event will be fired and the timer will set it back after 2sec.
- Change the cursor position and the Event will be fired again

**Comment by bonecode** [comment]
So, you are setting Modified to false without clearing undo? Can't work like that.

**Comment by bonecode** [comment]
I fixed UpdateModifiedStatus, how about now?

**Comment by buddyman83** [comment]
I think its wrong to have the undo list cleared. When user saves the current text, the modified flag is set to false. but he should still be able to undo !?

I think now its much better, although there is still a bug: when using backspace, the OnModified event is triggered every time.

**Comment by buddyman83** [comment]
Sure they modify the document but the event should not be triggered when modified-flag is already true.

**Comment by bonecode** [comment]
But it is not true, if you set it to false. It is triggered only, if the value is set from false to true.

**Comment by buddyman83** [comment]
I created a test app. Just put a line into a memo when OnModified is fired, no more code.

When i put an "a" into the document, the event is fired <-- thats correct, at this moment, the flag is true so in my understanding the event should be no more fired in my test app, because there is nothing what sets the flag to false

So when i hit "a" again, the event is not fired <-- thats correct

But...

When i move the cursor with mouse anywhere and hit "a" again, the event is fired again <-- ?!?!?
When i hit enter or backspace, the event is also fired again <-- ?!?!?

**Comment by bonecode** [comment]
Aah, indeed... because UpdateModifiedStatus is now setting it. I will think about this later tonight.

**Comment by bonecode** [comment]
Ok, I think I got this fixed.

**Comment by buddyman83** [comment]
First it worked perfect, but after setting Modified to false, the event is never fired again.

**Comment by bonecode** [comment]
it is called, if the undolist is empty. But if you need it to be called again after manually setting modified to false... the solution is not correct then.

**Comment by buddyman83** [comment]
I set it to false when the user saves the document. But in my opinion the user should still be able to undo the last steps?!

**Comment by bonecode** [comment]
I know, I know. I have a fix for this but I can't commit. "503 service unavailable...". Shit.

**Comment by buddyman83** [comment]
![794781](https://cloud.githubusercontent.com/assets/9843149/22376740/82f5e70a-e4af-11e6-8723-cc8b9af18ce8.png)

**Comment by bonecode** [comment]
I am always calm and relaxed but this Github... Last time I had to remove my whole project to make it work again.

**Comment by bonecode** [comment]
Ok, here we go again.

**Comment by buddyman83** [comment]
Its going to be perfect, but...... :)

When modified flag is false and doing an undo, the event is not fired

**Comment by bonecode** [comment]
Fixed again.

**Comment by buddyman83** [comment]
Brilliant! Now its perfect 👍 
Thank you so much.
