### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by AlbertWiersch** [bonecode/TBCEditor#549]
When displaying the following text in an edit control of the size in the screenshot with wordwrap, it does not display properly. Cursor navigation is also affected. See screenshot.

Text below:
```
The "submit-success" and "submit-error" AMP attribute markers must only be used on direct children of a "form" element. Visit https://www.ampproject.org/docs/reference/components/amp-form for more information.
---
1 message for line 404
```

![clip_5](https://cloud.githubusercontent.com/assets/7662186/22350345/0f4ec424-e3d9-11e6-95cc-1188938f39ca.png)

**Comment by bonecode** [comment]
Fixed.
