### ISSUE TITLE
ImageLists and Menus

### ISSUE THREAD

**Issue by Dimonka01** [bonecode/TBCEditor#550]
Hi,
It is not a big issue, but all of editor's ImageList and PopupMenu properties are typed as "final" types as **TImageList** and **TPopupMenu**. It would be very useful to change those types to **TCustomImageList** and **TCustomPopupMenu** in order to make you editor compatible with third party component sets.

Thanks!

**Comment by bonecode** [comment]
PopupMenu comes from TControl class, I won't create my own over it. TImageLists are changed to TCustomImagelists.
