### ISSUE TITLE
Disable scrolling on mouse wheel click

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#551]
Hi,

when i hit my mouse wheel the cursor turns in something like this

![2017-01-27 15_46_13-autoit rad studio 0 1](https://cloud.githubusercontent.com/assets/9843149/22374765/dc118f2c-e4a7-11e6-81d2-bb27559a9b55.png)

and let me scroll in every direction. However i have a special menu on this button so i dont want this feature. I disabled soWheelClickMove in Scroll options but it still begins to scroll.

**Comment by bonecode** [comment]
Should be fixed. I couldn't test this because I don't have a mouse. I always use the pad.

**Comment by buddyman83** [comment]
Yes its fixed, thank u very much.
