### ISSUE TITLE
Search: FindAll and FindNext

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#552]
When i use **FindAll()** method I can edit all results at one time, this is very nice =) But when in this mode and I press Escape key, it inserts a space char. I think thats a bug.

When i use FindNext(true) and it reaches the end of the document it asks to start over. If FindNext(false), it goes to the end and nothing more happens. Isn't there an option to always start over?

**Comment by buddyman83** [comment]
okay, got it
not sure if thats the best way

```
if (Editor->SearchResultCount && !Editor->FindNext (false))
{
	Editor->GotoLineAndCenter (0, 0);
	Editor->FindNext (false);
}
```

**Comment by bonecode** [comment]
That escape key in find all is a bug. 

Have you tried soWrapAround search option?

**Comment by bonecode** [comment]
Fixed escape bug.
