### ISSUE TITLE
Error or warning hints inside text

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#553]
Hi,

the CustomTokenAttribute with wave lines are nice to show the user code errors. But unfortunately there is no way to show him which errors occurred.

Maybe it would possible to add some kind of tooltip or (even nicer) like its done in Xcode...

![bildschirmfoto 2017-01-29 um 13 41 51](https://cloud.githubusercontent.com/assets/9843149/22404069/3040a934-e629-11e6-97e2-a56bd05c96d6.png)

**Comment by bonecode** [comment]
Well, usually errors are shown in separate error list because error messages can be quite long and contain number of rows. Xcode does also show the error in list (left panel) but it also show the error on line. I don't like the idea of duplicated error messages. 

But I think this is already possible to implement. There are Marks which can be used to show the error image on left panel and paint the background of the line. OnAfterLinePaint can be used to paint the rest.

**Comment by buddyman83** [comment]
As suggested i tried the Marks list to get the line paint in light red. To get the rightaligned dark red box i used the OnAfterLinePaint

```
if (ALineNumber == 2)
{
	String errorMsg = "No visible interface for 'blabla' declares the selector 'blabla'";

	TRect errorRect;
	errorRect.Top = ARect.Top;
	errorRect.Right = ARect.Right;
	errorRect.Bottom = ARect.Bottom;
	errorRect.Left = errorRect.Right - ACanvas->TextWidth (errorMsg);

	ACanvas->Brush->Color = TColor (0x9FAEF6);
	ACanvas->FillRect (errorRect);
	ACanvas->Font->Name = "Arial";
	ACanvas->Font->Color = clBlack;
	ACanvas->TextOut (errorRect.Left, errorRect.Top, errorMsg);
}
```

At the very first time the text is written properly in Black Arial.

![2017-02-01 13_02_24-autoit rad studio](https://cloud.githubusercontent.com/assets/9843149/22506329/2842f332-e880-11e6-93e3-7239358dd666.png)

But the following to lines are also black (unwanted)

After clicking in the editor, the error message gets the current highlighter color. Is that a bug or am i doing anything wrong ... ?! :(

![2017-02-01 13_02_50-autoit rad studio](https://cloud.githubusercontent.com/assets/9843149/22506362/4bc2e65a-e880-11e6-8173-719ef26b0540.png)

**Comment by bonecode** [comment]
You are setting canvas properties without setting them back to originals. Hmm... I will investigate, if that can be avoided easily.

**Comment by buddyman83** [comment]
Of course! I now save them before and set them back at the end. Works! Thank you very much.

**Comment by bonecode** [comment]
I moved editor FillRect to public. It is a bit faster way to fill rect.
