### ISSUE TITLE
AToken in EditorCustomTokenAttribute

### ISSUE THREAD

**Issue by buddyman83** [bonecode/TBCEditor#554]
Hi,

is it intended that non-ascii characters are splitted in AToken?

For example there are some script languages where variables alway begin with a $ like in PHP or AutoIt. In these cases the EditorCustomTokenAttribute is called twice (once for the $ and second for the variable name). In my opinion only a space should separate the ATokens.

**Comment by bonecode** [comment]
Yes. For example word wrap is not working quite well, if tokens are separated only by spaces. And there might be also many other issues, if you think about it.

You can change the code (if you will). 

BCEditor.Highlighter.pas (Line 271)

```
      if Ord(FCurrentLine[FRunPosition - 1]) < 256 then
      while (Ord(FCurrentLine[FRunPosition]) < 256) and not CharInSet(FCurrentLine[FRunPosition], FCurrentRange.Delimiters) do
        Inc(FRunPosition)
      else
      while (Ord(FCurrentLine[FRunPosition]) > 255) and not CharInSet(FCurrentLine[FRunPosition], FCurrentRange.Delimiters) do
        Inc(FRunPosition)
```

That means the tokens are separated by range delimiters. And you can define those delimiters in highlighter file. Or you can even change that to FCurrentLine[FRunPosition] = ' '. But don't expect me to fix all the bugs you're going to have. :)

**Comment by buddyman83** [comment]
maybe it would be easier (and better) to have an event per line with startPos and endPos and no tokens at all ?!

**Comment by bonecode** [comment]
```
  TBCEditorCustomTokenAttributeEvent = procedure(ASender: TObject; const AText: string; const ALine: Integer;
    const AChar: Integer; var AForegroundColor: TColor; var ABackgroundColor: TColor; var AStyles: TFontStyles;
    var ATokenAddon: TBCEditorTokenAddon; var ATokenAddonColor: TColor) of object;
```
There already is AText, ALine, and AChar.  EndPos is AChar + Length(AText).
