### ISSUE TITLE
Slow Highlighter when loading large highlighter.json files

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/TBCEditor#557]
I have created a large MASM Assembler highlighter with an initial Visual MASM color json file. When I use:

```
memo.Highlighter.LoadFromFile('AssemblerMASM.json');
memo.Highlighter.Colors.LoadFromFile('VisualMASM.json');
```

I have attached  the files so that you can test for yourself.

It takes several seconds for the highlighter file itself to be loaded. The same slowdown shows when doing a Ctrl + Space inside the editor.

It looks like TBCEditorHighlighter is dependent on TBCEditor to be its parent because the highlighter is casting a TWinControl to TBCEditor.

Would it make more sense the make the highlighters truly independent controls and assign a highlighter at runtime to a TBCEditor? This would allow loading of highlighter json files and color files independent of the editor text lines. I think this would allow more flexibility and performance can be tweaked independent of TBCEditor.

[AssemblerMASM.zip](https://github.com/bonecode/TBCEditor/files/753005/AssemblerMASM.zip)
[VisualMASM.zip](https://github.com/bonecode/TBCEditor/files/753007/VisualMASM.zip)

**Comment by bonecode** [comment]
Remove API keywords and it is very fast. It is not a good idea to add those in the highlighter. I also noticed that there are unnecessary operators. &&, ==, !=, >=, <=, || are unnecessary. It is enough to just use &, =, !, >, <, and |.

Prepare of highlighter is taking that time. It is not designed for 29 000 keywords...

**Comment by ThomasJaeger** [comment]
I know if I would remove API that it would be fast. It would remove 29,000 keywords.

Any thoughts on addressing the root cause instead? Why would each instance of the editor need the same type of highlighter? If I have 5 files open and have 5 editors, I would need 5 highlighters. Why not share the same highlighter for 5 editors?

**Comment by bonecode** [comment]
I had some code review and now the original highlighter is prepared in 3 seconds (release build).  But you can try to optimize it more. 

```procedure TBCEditorRange.Prepare(AParent: TBCEditorRange);```

In  BCEditor.Highlighter.Rules.pas is the place where magic happens.

It was a conscious choice not to separate the highlighter into a separate component like SynEdit does. Separating the current solution is not easily done, so I won't do it. I need to move to other projects asap.

**Comment by bonecode** [comment]
By removing FindToken calls, it is very fast. Hmm...

**Comment by bonecode** [comment]
I made some optimizations. Is it fast enough?

**Comment by bonecode** [comment]
Damn, not a good solution...

**Comment by ThomasJaeger** [comment]
Yes, its immediate now on my fast machine. Thank you! The Ctrl + Space piece still takes a while to load but it's understandable. Thank you for looking into this.

**Comment by bonecode** [comment]
I will look at that also, if there is something to optimize.
