### ISSUE TITLE
Work with Large document in the Word Wrap mode optimization - Fixed

### ISSUE THREAD

**Issue by delphioracle** [bonecode/TBCEditor#558]
[WordWrapOptim.zip](https://github.com/bonecode/TBCEditor/files/753149/WordWrapOptim.zip)
Merge with your last changes:
[BCEditor.Editor.Base.pas.zip](https://github.com/bonecode/TBCEditor/files/753218/BCEditor.Editor.Base.pas.zip)

1) the number of CreateLineNumbersCache calls is reduced from 6 to 1
2) PaintHelper.SetStyle calls (in  CreateLineNumbersCache) total time for any document -> 0. 
Before optimization this total time was in direct ratio to a style change count. 
For example, test results for Scripts_ExpOracle.xml (149 Mb, >2 000 000 lines, up to 24 Mb Line Length)
![large xml](https://cloud.githubusercontent.com/assets/22052292/22628873/d0c1f282-ebec-11e6-8da5-90b17d91e7ba.png)

Scripts_ExpOracle.**xml** open time: OLD 300 sec; NEW 15 sec 
Scripts_ExpOracle.**txt** open time: OLD  70 sec; NEW 15 sec 
Scripts_ExpOracle.**xml** without word wrap open time: OLD 9 sec; NEW 3 sec 
Scripts_ExpOracle.**txt** without word wrap open time: OLD  3 sec; NEW 3 sec

**Comment by bonecode** [comment]
I reviewed the code and decided not to merge this code. I will investigate how to optimize that later.

**Comment by delphioracle** [comment]
You have saved the test file Scripts_ExpOracle.xml which I sent by mail earlier?

**Comment by bonecode** [comment]
Hmm, I think I have it somewhere. If it was added in the issue, then I will find it.

**Comment by delphioracle** [comment]
I  sent it by e-mail now.

**Comment by bonecode** [comment]
Thanks.
