### ISSUE TITLE
DPI-Awareness

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#559]
While compiling the TBCEditor, it uses the BCEditor.res file with some bitmaps in it. One of it is shown in my first implementation:
![unbenannt](https://cloud.githubusercontent.com/assets/1734822/22646106/e8b21fec-ec6a-11e6-918e-797168408cd0.png)

To make my application as a "DPI-Aware Application", it has to show graphics rendered to the used screen resolution.

So if I use "200%" DPI Text size inside my Windows settings, since I have a high resolution monitor, the graphics has to be shown with 32x32 pixel, but inside the BCEditor.res file, there is only a bitmap with 16x16 pixel.

I didn't check, if the BCEditor is DPI aware and if he only show this graphic in a bad resolution, or if the BCEditor does not support DPI Awareness completely.

If wanted, I can offer more information about DPI-Awareness...

**Comment by bonecode** [comment]
I am well aware of DPI-awareness and all its pitfalls for example with multiple monitors etc. Unfortunately my time is very limited and this is not an issue for me - EditBone is working sufficiently well with high DPI screens (thanks to AlphaSkins). But if somebody has done or is willing to do a better support for this (and does not create spaghetti code), I can merge changes.

**Comment by NilsHoyer** [comment]
Inside my application, I'm loading the icon from a resource, interpolate the size depending on the Windows settings and put it into an ImageList. The code is simple.

The icons are stored with 64x64 pixel with alpha transparency as resources. I open it with the 64x64 pixel from the resources by `FindResource` and `LoadResource`, create an `HICON` based on the used Windows DPI setting by `GetSystemMetrics`, transform it with the `GDI+` engine and put it into the image list.

I think this code is easy to understand and you can overtake it with a few minutes. If I should search the location inside your code, I would need much more time for search than you for implementing it, I think.

Indeed you need new icons in 64x64 pixel. If you want, I can search them for you. Please let me know if you want my assistance.

```delphi
  FImages := TImageList.Create(nil);
  FImages.ColorDepth := cd32Bit;
  FImages.Height := GetSystemMetrics(SM_CYSMICON);
  FImages.Width := GetSystemMetrics(SM_CXSMICON);

  if (FindResource(HInstance, MAKEINTRESOURCE(10000 + I), RT_GROUP_ICON) > 0) then
    begin
      ResInfo := FindResource(HInstance, MAKEINTRESOURCE(10000 + I), RT_GROUP_ICON);
      ResData := LoadResource(HInstance, ResInfo);
      Resource := LockResource(ResData);
      IconId := LookupIconIdFromDirectoryEx(Resource, TRUE, 64, 64, LR_DEFAULTCOLOR);
      ResInfo := FindResource(HInstance, MAKEINTRESOURCE(IconId), RT_ICON);
      ResData := LoadResource(HInstance, ResInfo);
      Icon := CreateIconFromResourceEx(
        LockResource(ResData), SizeOfResource(HInstance, ResInfo),
        TRUE, $00030000, 64, 64, LR_DEFAULTCOLOR);
       Bitmap := Graphics.TBitmap.Create();
      Bitmap.PixelFormat := pf32bit;
      SetBkMode(Bitmap.Canvas.Handle, TRANSPARENT);
      Bitmap.SetSize(FImages.Width, FImages.Height);

      GPBitmap := TGPBitmap.Create(Icon);

      GPGraphics := TGPGraphics.Create(Bitmap.Canvas.Handle);
      GPGraphics.SetInterpolationMode(InterpolationModeHighQuality);
      GPGraphics.DrawImage(GPBitmap, 0, 0, Bitmap.Width, Bitmap.Height);

      ImageList_Add(FImages.Handle, Bitmap.Handle, Bitmap.MaskHandle);

      GPGraphics.Free();
      Bitmap.Free();
    end
```
