### ISSUE TITLE
SelStart, SelLenth, SelText properties

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#562]
The TEdit, TMemo and TRichEdit controls are having SelStart, SelLenth, SelText properties - TBCEditor not.

I would like to have this in TBCEditor too - even I know, they can work with ActiveMode = smNormal only.

If I implement this without "spaghetti code" and offer it to you as "pull request" - are you interested to overtake it? I would handle ActiveMode = smColumn with an exception.

**Comment by bonecode** [comment]
I can add those, no problem.

**Comment by bonecode** [comment]
property SelectedText is SelText and properties SelectionBeginPosition and SelectionEndPosition offers you the position information. I will add SelectionLength property.

**Comment by NilsHoyer** [comment]
I can use SelStart to address the the whole text as an integer value.

Inside my application, I'm using the content of the BCEditor for SQL code, I sent to a SQL server. If the SQL reports a problem, I want to mark the related code inside the BCEditor.

Example:
``` SQL
SELECT 1;
xSELECT 2;
SELECT 3;
```

I can detect the length of the well executed code - in this example 10 character. And I get the length of the invalid code - in this example 11 character.

To mark that code, until now I used SynEdit and the SelStart and SelLength properties. With BCEditor, I have to calculate the Line and the Char.

If you want, I would to this inside the TBCBaseEditor class, to make it more compatible with TMemo and TRichEdit. If you don't want this, I find my own solution. And if you would implement this, I would be happy too... ;-)

**Comment by bonecode** [comment]
Ah, indeed. Long time without using those editors. I can add SelectionStart and SelectionLength properties.

**Comment by bonecode** [comment]
Added, tell me if it is not working like it should.
