### ISSUE TITLE
CompletionProposal does disable <F4>

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#564]
I have a form with a TBCEdior and open the CompletionProposal window. Now I press <F4> to close my form - but nothing happens.

If I press <Esc> the CompletionProposal window closes, and I can press <F4> to close my form.

I have an application with the `WS_POPUP` and `WS_BORDER` ... but I can use the <F4> button, while the popup is open.

Btw: Would be nice, if you would add the `CS_DROPSHADOW` style:
```Delphi
Params.WindowClass.Style := Params.WindowClass.Style or CS_DROPSHADOW;
```

 ... but until now, I didn't find a stable solution for this in my application.

**Comment by bonecode** [comment]
I added cpoShowShadow option for completion proposal. Some like it, some don't.

I am not sure about that other part but now function keys goes back to editor. Does it help?

**Comment by NilsHoyer** [comment]
<F4> still does not work on my end....

**Comment by NilsHoyer** [comment]
Now if I press <F4>, I get an AV in `TBCEditorKeyboardHandler.ExecuteKeyDown` in line 9.

![unbenannt](https://cloud.githubusercontent.com/assets/1734822/22731485/2467c3c6-edeb-11e6-913b-c742531953c5.png)

**Comment by bonecode** [comment]
Cool. 

What do you mean by <F4>? I know Alt+F4 but plain F4 is a mystery for me...

**Comment by NilsHoyer** [comment]
Sorry, my mistake. I ment <Alt+F4> for closing the application.

**Comment by bonecode** [comment]
That seems to work.

**Comment by NilsHoyer** [comment]
Ok, you are not able to see the problem. I respect this.

**Comment by bonecode** [comment]
I can't repeat the issue, so that's it.
