### ISSUE TITLE
CompletionProposal shows reserved words from the highlighter

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#565]
![unbenannt](https://cloud.githubusercontent.com/assets/1734822/22711018/e3a62870-ed7f-11e6-855f-b5a8eb7ddf85.png)

... the left column shows the ReservedWords from the Highlighter. The right column shows my words:
```Delphi
  BCEditor.CompletionProposal.Columns[0].Items.Clear();
  BCEditor.CompletionProposal.Columns[1].Items.Clear();
  BCEditor.CompletionProposal.Columns[0].Items.Add().Value := 'MyCol_1a';
  BCEditor.CompletionProposal.Columns[1].Items.Add().Value := 'MyCol_1b';
  BCEditor.CompletionProposal.Columns[0].Items.Add().Value := 'MyCol_2a';
  BCEditor.CompletionProposal.Columns[1].Items.Add().Value := 'MyCol_2b';
```

What can I do to hide the ReservedWords from the highlighter an show my own words?

**Comment by bonecode** [comment]
Remove the completion proposal option cpoParseItemsFromText.

**Comment by bonecode** [comment]
Remove the completion proposal option cpoAddHighlighterKeywords. Note there is also cpoParseItemsFromText option.

**Comment by NilsHoyer** [comment]
I removed the option cpoAddHighlighterKeywords. Now if I press <Ctrl+Space> nothing happens - I don't see my own columns.

And if I press <Esc> after this ... I get an `integer division by zero` in the first line of `TBCEditorCompletionProposalPopupWindow.Destroy`.

**Comment by bonecode** [comment]
Did you make a second column and left the first column empty?

**Comment by NilsHoyer** [comment]
CompletionColumnIndex = 0.

Like shown above, I'm using 
```Delphi
BCEditor.CompletionProposal.Columns[0].Items.Clear();
BCEditor.CompletionProposal.Columns[1].Items.Clear();
```

I don't have predefined items in the columns.

Btw: I can set column captions - where can I see them?

Btw2: I can define cpoResizable - but I can't resize the popup.

**Comment by bonecode** [comment]
There is Title property what you can set Visible. That resizing works...

![image](https://cloud.githubusercontent.com/assets/11475177/22724654/5ae4200e-edd0-11e6-88ed-b244ef638545.png)

What Windows version you are using? I will test that without AlphaSkins.

**Comment by NilsHoyer** [comment]
Now I was able to resize the popup: The mouse cursor does not change exatly where it should - but 3 or 5 pixel below it changed.

Imho it's not a good implementation to resize a window without giving them the state `WS_SIZEBOX`. Indeed the border if `WS_SIZEBOX` is incredible big, ... but implementing a solution away from the Windows stadard makes trouble ... like shown in this case.

I'm useing Windows 7 with the classic design.

**Comment by bonecode** [comment]
The problem is not easy in this case because the focus is always in the editor, not in the popup. Size box is ugly and didn't fit there.

That classic theme is... well... Some don't even bother to support it. :) It shows well painting errors thou.

**Comment by NilsHoyer** [comment]
I know a lot of problems with the WS_POPUP windows - I fighting with this problems too. But that is the reason, I try to use only Windows standards: If I try to find an other way... somewhere else I get trouble.

Until now, MS mark Vista, 7 and 8 as supported. All of them are offering classic design. Imho we should respect this and supporting it too.

Indeed there are sometimes problems, if we try not to use all Windows standards. Indeed often it's nice to implement a feature or a design, which are not possible by respecting all standards. In this case it's more important to respect the standards than implementing our private wishes.

**Comment by NilsHoyer** [comment]
If I remove `cpoAddHighlighterKeywords` I get an empty proposal popup box.

I entered an item inside the Object Inspector of the Delphi IDE and I added this line to my `FormCreate` procedure:
```Delphi
BCEditor.CompletionProposal.Columns[0].Items.Add().Value := 'MyCol_1a';
```

**Comment by bonecode** [comment]
There is an OnBeforeCompletionProposalExecute event for that...

**Comment by NilsHoyer** [comment]
Inside the `OnBeforeCompletionProposalExecute` I would like to have an option to cancel the completion proposal. I have to fill the column list with the word, which are allowed in that context.

I'm using the BCEditor for a SQL tool. If the user entered "SELECT * FROM" and press opens the completion propsal, I would like to show the list of available table names. But to show them, I have to get it first. So I would like to cancel the proposal showing, receive the table names and initiate the propsal list again.

On this way, I don't have to block my main tread while receiving the table names.

Until now, I worked with SynEdit - and there I had an parameter: `var CanExecute: Boolean`. This parameter is also used in other cases, like changing the TreeView node, closing a form, etc.

Can you implement that parameter for me? If not: Are you interested to get it? I would implement it an offered as PullRequest to you...

**Comment by bonecode** [comment]
Fixed.
