### ISSUE TITLE
Using standard Actions

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#566]
I'm using the Delphi TEditAction Actions inside my main menu. They should be updated by the ActiveControl. But TBCEditor does not support them. I would like to use it.

I'm using the attached procedures to implement the actions inside my component. I think it's easy to understand for your. If not, I could translate it for TBCEditor, if you are interessted about this.

```Delphi
function TMySQLDBGrid.UpdateAction(Action: TBasicAction): Boolean;
begin
  if (Action is TEditAction) then
  begin
    Result := Focused() and Assigned(DataLink.DataSet) and DataLink.DataSet.Active and Assigned(SelectedField);

    if (Result) then
      if (Action is TEditCut) then
        TEditCut(Action).Enabled := not SelectedField.IsNull and not SelectedField.Required and SelectedField.CanModify and (not EditorMode or Assigned(InplaceEditor) and (InplaceEditor.SelText <> ''))
      else if (Action is TEditCopy) then
        TEditCopy(Action).Enabled := EditorMode and Assigned(InplaceEditor) and (InplaceEditor.SelText <> '') or not EditorMode and (not SelectedRows.CurrentRowSelected and not SelectedField.IsNull or SelectedRows.CurrentRowSelected and (DataSource.DataSet is TMySQLDataSet) and (DataSource.DataSet.State <> dsInsert))
      else if (Action is TEditPaste) then
        TEditPaste(Action).Enabled := not ReadOnly and SelectedField.CanModify and (EditorMode and IsClipboardFormatAvailable(CF_UNICODETEXT) or not EditorMode and IsClipboardFormatAvailable(CF_UNICODETEXT))
      else if (Action is TEditDelete) then
        TEditDelete(Action).Enabled := (SelectedRows.Count = 0) and not SelectedField.IsNull and not SelectedField.Required and SelectedField.CanModify and (not EditorMode or Assigned(InplaceEditor) and (InplaceEditor.SelText <> ''))
      else if (Action is TEditSelectAll) then
        TEditSelectAll(Action).Enabled := (DataLink.DataSet.RecordCount > 0)
      else
        Result := False;
  end
  else
    Result := inherited UpdateAction(Action);
end;

function TMySQLDBGrid.ExecuteAction(Action: TBasicAction): Boolean;
begin
  if (Action is TEditCut) then
    Result := EditCutExecute()
  else if (Action is TEditCopy) then
    Result := EditCopyExecute()
  else if (Action is TEditPaste) then
    Result := PasteFromClipboard()
  else if (Action is TEditDelete) then
    Result := EditDeleteExecute()
  else if (Action is TEditSelectAll) then
    begin Result := True; SelectAll(); end
  else
    Result := inherited ExecuteAction(Action);
end;
```

Both functions must be `public` with the attribute `override`.

**Comment by bonecode** [comment]
I don't understand why you need those.

See https://github.com/bonecode/TBCEditor/blob/master/Source/BCEditor.Editor.KeyCommands.pas

You can also see how I have done the same in EditBone.

**Comment by NilsHoyer** [comment]
I'm sorry, but maybe one of us don't understand the sense of the TAction support in Delphi. As far I understood this actions, I use it globally inside my program. Than I can connect main menu, popup menu items and toolbar buttons with this actions. After this, the menu items and buttons are showing the caption of the action and using their short cuts. I don't have to update the `Enabled` options of that items and buttons, since the active component does handle this for me.

For this, the component implements the `UpdateAction` function. Delphi calls this function, if the component will be activated. Than the component answers this function call with `True` or `False`, depending, if it supports the related action. You can do this on this way:

```Delphi
function TBCBaseEditor.UpdateAction(Action: TBasicAction): Boolean;
begin
  if (Action is TEditCut) then
    TEditCut(Action).Enabled := (SelectionBeginPosition.Char <> SelectionEndPosition.Char) or (SelectionBeginPosition.Line <> SelectionEndPosition.Line)
  else if (Action is TEditCopy) then
    TEditCopy(Action).Enabled := (SelectionBeginPosition.Char <> SelectionEndPosition.Char) or (SelectionBeginPosition.Line <> SelectionEndPosition.Line)
  else if (Action is TEditPaste) then
    TEditPaste(Action).Enabled := not ReadOnly and IsClipboardFormatAvailable(CF_UNICODETEXT)
  else if (Action is TEditDelete) then
    TEditDelete(Action).Enabled := not ReadOnly and ((SelectionBeginPosition.Char <> SelectionEndPosition.Char) or (SelectionBeginPosition.Line <> SelectionEndPosition.Line))
  else if (Action is TEditSelectAll) then
    TEditSelectAll(Action).Enabled := Lines.Count > 0
  else if (Action is TEditUndo) then
    TEditUndo(Action).Enabled := UndoList.CanUndo
  else
    Result := inherited;
end;
```

If you implement this function, I can choose the menu item or click on the toolbar button. In this case, Delphi calls the `ExecuteAction` function of the active component. And this function executes the action. On this way, I don't have to implement a code into my application.

There are some standard actions, defined in the `StdActns` unit. Imho every component should support this actions. On this way, I don't have to think about the implementation of this features of my program. And the actions Cut, Paste, Delete and Copy are used in a lot of different components of my program.

You can implement the `ExecuteAction` function on this way:
```Delphi
function TBCBaseEditor.ExecuteAction(Action: TBasicAction): Boolean;
begin
  if (Action is TEditCut) then
    begin Result := True; ExecuteCommand(ecCut, #0, nil); end
  else if (Action is TEditCopy) then
    begin Result := True; ExecuteCommand(ecCopy, #0, nil); end
  else if (Action is TEditPaste) then
    begin Result := True; ExecuteCommand(ecPaste, #0, nil); end
// ecDelete is not supported
//  else if (Action is TEditDelete) then
//    begin Result := True; ExecuteCommand(ecDelete, #0, nil); end
  else if (Action is TEditSelectAll) then
    begin Result := True; ExecuteCommand(ecSelectAll, #0, nil); end
  else if (Action is TEditUndo) then
    begin Result := True; ExecuteCommand(ecUndo, #0, nil); end
  else
    Result := inherited;
end;
```

I tested this impementation - it works fine (without the missing ecDelete command).

You have to add `StdActns` to the uses clause and into the declaration of `TBCBaseEditor` this lines:
```Delphi
public
    function ExecuteAction(Action: TBasicAction): Boolean; override;
    function UpdateAction(Action: TBasicAction): Boolean; override;
```

... it's not only for me ... it's for every developer using the Actions of Delphi. Actions are support since Delphi 7 or before.

**Comment by bonecode** [comment]
Ah, the code helps to understand what you mean. Sure, that can be added.
