### ISSUE TITLE
Setting colors while runtime.

### ISSUE THREAD

**Issue by NilsHoyer** [bonecode/TBCEditor#567]
I would like to change the colors while runtime ... to allow the users defining his own colors.

I tried this way ... bu it doesn't work:
```Delphi
  BCEditor.Highlighter.Colors.LoadFromFile('Colors.json');
  BCEditor.Highlighter.LoadFromFile('Highlighter.json');

  BCEditor.Highlighter.Colors.GetElement('Editor').Background := clRed;
```

The colors of that files are shown as well. What is my mistake?

**Comment by bonecode** [comment]
Use TJsonObject to load the color file, modify it and save it. Does not make sense to modify elements like that. You need to save user definition anyway.

There is a one kind of implemention in EditBone. Options->Colors.

**Comment by NilsHoyer** [comment]
> Does not make sense

This is exactly your problem: Often you don't see the sense of something. But this is not the problem. The problem is: You don't **try** to see the sense of it. Instead of this, you just ignore it. This is arrogant and selfish of you.

... and that are the reason, why I don't use your software in the moment.

May you find, what you are looking for...

**Comment by bonecode** [comment]
I don't have problems. You are the one who is having them and ask. I offered you a proper solution. That is all I can do.

Remember this is a hobby project for my own editor. I am not running a company. I am not getting a dime from this. I give away thousands of hours of work for free and you don't respect it. Thanks a lot.

**Comment by NilsHoyer** [comment]
> I don't have problems.

More ignorant is not possible!

> Remember this is a hobby project

All we do, we should do for god and for serving other people. But you do something for your own - this is selfish.

>  I give away thousands of hours of work

Yes, you waste a lot of time, because you are not able to concentrate to the important things. But this is not the problem. The problem is: You don't **try** to find out, what is important.

Important is serving other people. This means, you have to figure out, what other people needs and what they wants to have.

>  for free

You should **never** ask for anything - that is selfish only. You should only find out, how you can serve other people and wait for other people, that they serve you.

But I think it's wasting energy to teach this to you. You are selfish and ignorant. You don't **try** to change yourself. This is not what god wants from us...
