### ISSUE TITLE
Unicode support beyond UCS-2

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#57]
Unicode characters outside the BMP (Basic Multilingual Plane) are not properly supported by delete/backspace as well as selections, they will remove only one of the two 16-bits elements, leaving an invalid one.
Selections will happily end up in the middle of the character, and copy/paste one half of a character resulting in an invalid unicode string.

For instance you can try with 𠀀 (http://www.fileformat.info/info/unicode/char/20000/index.htm)

**Comment by bonecode** [comment]
That happens because character count for that character is 2. 

I tested TMemo and it works. It is using TMemoStrings... Get and Put doing things little differently.

**Comment by EricGrange** [comment]
Yep, it's outside of the BMP.

Compatibility with such characters is what separates UCS-2 from Unicode, and also is required for full Chinese support (most common Chinese are in the BMP, but there are a few tens of thousandths "rare" characters that are not... except they can sometimes be not rare at all as they appear in names... which means they can appear in source code comments, hehe).

**Comment by bonecode** [comment]
Fixed delete of surrogate pair. Selection will follow...

**Comment by bonecode** [comment]
Fixed.
