### ISSUE TITLE
Avoid Format() for string concatenation

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#58]
Makes the intent less obvious, is less efficient and prone to runtime errors (as types are not checked at compile-time)

Present in TBCBaseEditor.GetColorsFileName and TBCBaseEditor.GetHighlighterFileName

**Comment by bonecode** [comment]
Personally I hate concatenations (specially a multi-line) with plus character which are just a mess of code. Efficiency at this point is also not an issue.

**Comment by EricGrange** [comment]
In those particular cases, there is no multi-line issue since the concatenation is shorter than the Format(), f.i.

    Result := IncludeTrailingPathDelimiter(Result) + ExtractFileName(AFileName);

vs 

    Result := Format('%s%s', [IncludeTrailingPathDelimiter(Result), ExtractFileName(AFileName)]);

More than efficiency, readability is at stake, I had to do a double take to figure out what code was trying to do :)
