### ISSUE TITLE
Change CreateHighlighterIncludeFileStream to CreateFileStream

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#59]
And use it for colors and the main highlighters load.

This way it "virtualizes" the file system as far as the editor goes (and can allow removing some code)

**Comment by EricGrange** [comment]
Also the method should release the stream it was passed

**Comment by bonecode** [comment]
What do you mean? There already is a stream load for colors and highlighters and hard to see how to combine these into same create with this include... I am missing the point here somehow... No surprise, after sleeping so little lately. :D

**Comment by EricGrange** [comment]
I mean that currently you have 3 different methods required to abstract the file system: the main highlighter LoadFromStream, the CreateHighlighterIncludeFileStream and the colors LoadFromStream.

If all LoadFromFile methods were to just wrap LoadFromStream & CreateFileStream, then you could just use the LoadFromFile methods all the time, and only override CreateFileStream to control where/how the streams are created from the file names.

**Comment by bonecode** [comment]
And file names as parameters?

**Comment by EricGrange** [comment]
I'm thinking that all LoadFromFile methods could be like

    procedure XXX.LoadFromFile(AFileName);
    var
        s : TStream;
    begin
        s := CreateFileStream(AFileName);
        try
            LoadFromStream(s);
        finally
            s.Free;
        end;
    end;

This way you have a single point (CreateFileStream) to override to switch from OS file system, bundled resources, DB resources, or whatever resources.

(the use case I have here being bundled default resources, which can be overridden by file resources, f.i. is CSS.json is on the file system, use that, if not use the bundled version)

**Comment by bonecode** [comment]
Ah, now my brains are connecting. :)

**Comment by bonecode** [comment]
Fixed.
