### ISSUE TITLE
Assigning from Editor.Lines should not eliminate folded code

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#61]
Currently if you do

    var s : TStrings;
    ...
    s.Assign(editor.Lines)

s will not contain the folded lines.
Or is there another way to obtain the whole edited code?

**Comment by bonecode** [comment]
GetCodeFoldingUncollapsedStrings; will return what it says...

**Comment by EricGrange** [comment]
Maybe, but it's private :)
