### ISSUE TITLE
GotoLineAndCenter and code folding (round 2)

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#62]
Issue #54 was only partially fixed, the fix only covers the case where there is a single collapsed region above the line you're going to.

- it's still incorrect if there are multiple folded regions above the lines you're going
- it's incorrect if going to a line in a folded region (even the first folded region)

When going to a folded line, I think it should unfold all the necessary regions

**Comment by bonecode** [comment]
Fixed.
