### ISSUE TITLE
Add OnSelectionChange/OnCaretChange or OnStatusChange

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#64]
The idea is to get notifications for caret/selection change events specifically for one editor.

In the demo ApplicationEventsMessage is used, but while that's okay for a demo or a simple editor project, in a more complex case, ApplicationEventsMessage can get very busy, and updating & checking everything in there can get very inefficient and make the UI feel sluggish.

Associated to caret/selection change you can f.i. have code insight, source tree location and other relatively expensive stuff happening. When the only way is through ApplicationEvents, it means you have to cache the editor caret/selection state to sort out the editor caret/selection from the rest.

**Comment by bonecode** [comment]
Fixed.
