### ISSUE TITLE
TBCBaseEditor.SearchChanged  option to avoid FindNext

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#66]
The purpose would be to be able to use the search functionality to highlight terms similar to the selection (same as in notepad++)

This means the search should be able to search all terms, activate the highlight and map, but not move the editor in any way (see also issue #65)

**Comment by bonecode** [comment]
Fixed. Selection.Options soHighlightSimilarTerms

**Comment by EricGrange** [comment]
How is it used?
