### ISSUE TITLE
GetCodeFoldingUncollapsedStrings is private

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#67]
Should be accessible in some way so the editor content can be accessed without saving to a file or stream cf. Issue #61

Ideally though, I would expect Lines to reflect the editor content, with the folded content being just an internal implementation thing.

**Comment by bonecode** [comment]
I think I remove Lines (because you don't know what it means in this context) and add UncollapsedLines and CollapsedLines...

**Comment by EricGrange** [comment]
Yes, that would work, though it might complicate things.

I don't think that CollapsedLines need to be accessible outside the component (I certainly do not see myself needing them), they could be abstracted/encapsulated by the component, this way you will also not have to maintain two sets of methods & coordinates to access/manipulate the collapsed or uncollapsed lines.

**Comment by bonecode** [comment]
That is true... today I have many ideas and most of them are not thought through. Lines it is, and it should return uncollapsed lines.

**Comment by EricGrange** [comment]
GetCodeFoldingUncollapsedStrings is not directly usable for that though: it recreates a TStrings at each call, and also does not allow to modify the editor content, so it should probably be an adapter class (that automagically maps the indexes both ways), rather than a value/container/collection.

A sluggish adapter implementation could be "good enough", and optimized later once the dust has settled.

**Comment by bonecode** [comment]
I changed GetCodeFoldingUncollapsedStrings into CreateUncollapsedLines and made it public. I will get back to this Lines issue later.
