### ISSUE TITLE
Way to clear search without scrolling to top?

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#68]
Once you have started a search, is there a way to clear the search without also scrolling to top?

Setting Search.Enabled to false does not clear the highlights, and setting Search.SearchText to an empty string will clear the results but also scroll to the top (because of a CaretZero call)

(probably related to Issue #65)

**Comment by bonecode** [comment]
Fixed. Setting.SearchText to empty will clear the results.
