### ISSUE TITLE
TBCBaseEditor.CodeFoldingRangeForLine is slow

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#69]
At the moment, when editing a file like BCEditor.Editor.Base, about 40% of the rendering time is spent in TBCBaseEditor.CodeFoldingRangeForLine, which scans the CodeFoldings at every call.

Ideally an array could be built with one entry per line, so that looking up the code-folding per line would just be an array access. This array could be flushed at a cost similar to one TBCBaseEditor.CodeFoldingRangeForLine call, so it would be much more efficient, however I do not know if the flush would be easy to hook.

A more minor optimization could consist in streamlining the search loops, for instance the function could be rewritten as follows this reduces register pressure a bit (and allows eliminating the 'with'), and some key functions could be marked as inline (f.i. GetAllFoldRange)

    function TBCBaseEditor.CodeFoldingRangeForLine(ALine: Integer): TBCEditorCodeFoldingRange;
    var
       i : Integer;
    begin
       for i := 0 to FAllCodeFoldingRanges.AllCount - 1 do begin
          Result := FAllCodeFoldingRanges[i];
          if not Result.ParentCollapsed and (Result.FromLine = ALine) then Exit;
       end;
       Result := nil;
    end;

the improvement from that is measurable, but not comparable to using the lookup array (which makes CodeFoldingRangeForLine basically "free")

**Comment by bonecode** [comment]
True. The component has a lot to be optimized and refactored.

**Comment by EricGrange** [comment]
Is there a particular place to be notified of codefolding & code change? I could add the cache code

**Comment by EricGrange** [comment]
I'll go ahead and write the cache, flushing it at every paint, should already be able to vastly improve the perf

**Comment by EricGrange** [comment]
Done

https://bitbucket.org/egrange/tbceditorxe/commits/b30eda3f263ca515ae8c025b3a0b94081fa4c57b

Code can probably be simplified as there are things I did not know, so it may be working extra hard for things that cannot happen (cf. comments)

FWIW next bottlenecks are

- TCanvas.FillRect (too many calls? some overlap? not sure yet)
- Windows.ExtTextOutW (probably unavoidable)
- TBCBaseEditor.PaintGuides (loops over FAllCodeFoldingRanges, might be able to share the CodeFoldingRangeForLine cache)
- AdjustEndRect (not sure what it does exactly)
- TBCEditorTextDrawer.GetCachedABCWidth (need to add cache for more than one font styles)

**Comment by bonecode** [comment]
Ok, good, I am grateful for all the help. I have a lot of projects that need my time and a daily job on the side.

**Comment by EricGrange** [comment]
I also appreciate what you're doing, I have had some desire to start on a code-folding fork for some time, but no free time to tackle the whole project on my own.
I will contribute what I can to testing, optimizations & fixes :)

**Comment by bonecode** [comment]
Code folding for one specific language is a walk in a park but making it generic has been a pain in the ass. :)

**Comment by bonecode** [comment]
Fixed. I modified this:

procedure TBCBaseEditor.CodeFoldingPrepareRangeForLine;
var
  i: Integer;
  LMaxFromLine: Integer;
  LCodeFoldingRange: TBCEditorCodeFoldingRange;
begin
  LMaxFromLine := 0;
  SetLength(FCodeFoldingRangeForLine, FLines.Count); { max it can be}
  for i := FAllCodeFoldingRanges.AllCount - 1 downto 0 do
  begin
    LCodeFoldingRange := FAllCodeFoldingRanges[i];
    if not LCodeFoldingRange.ParentCollapsed then
    begin
      if LCodeFoldingRange.FromLine >= LMaxFromLine then
        LMaxFromLine := LCodeFoldingRange.FromLine;
      FCodeFoldingRangeForLine[LCodeFoldingRange.FromLine] := LCodeFoldingRange;
    end;
  end;
  SetLength(FCodeFoldingRangeForLine, LMaxFromLine); { actual size }
end;

Calling SetLength in a loop is never a good thing...

**Comment by EricGrange** [comment]
> Calling SetLength in a loop is never a good thing...

I was not sure if the max was FLines.Count (visible lines) or the actual line count (uncollapsed lines)

With FastMM (any Delphi beyond XE), growing an array size in a loop is not an issue (it does speculative re-allocation), and you can/should probably remove the SetLength after the loop, given that memory usage there is not an issue, this way the check in CodeFoldingRangeForLine can be removed as well.

Unintuitively enough, because of that final SetLength, your version will occasionally end up with one more actual reallocation than mine with many SetLength calls did :)
SetLength on an array with FastMM is no worse than doing an .Add() on a list without having set Capacity before.
