### ISSUE TITLE
soHighlightSimilarTerms low performance

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#71]
soHighlightSimilarTerms triggers a GetSelectedText which does a FindAll

The GetSelectedText is currently very slow because it works from the uncollapsed lines, which are rebuilt from scratch each time, so this makes any selection change very slow.

Without rewriting GetSelectedText, a simple fix would be to use the same logic as notepad++ and highlight only when the selection is a whole word, cf.

https://bitbucket.org/egrange/tbceditorxe/commits/04dec1b37c7f484c3282a3bc7926fd057ee16f46

(as a side Issue, while the search is performed, I do not see it highlighted, not sure what other property I have set incorrectly)

**Comment by bonecode** [comment]
Actually, you can delete this code. My bad, there's no need to call FindAll. :)
