### ISSUE TITLE
Faster PaintLines / FillRect

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#72]
Not really an issue but more discussion/idea dump

FillRect bottlenecks comes mostly from many calls in PaintHighlightToken, and the Minimap is the one that suffers the most (lots of call, very small areas). Worst case are lines with many short tokens (such as symbols).

When the line is filled in one call at the beginning of PaintLines, and the FillRects in PaintHighlightToken are commented out, then painting is very fast, though of course that breaks a lot of things.

One possible clean fix could be to used deferred rendering: PaintHighlightToken would not paint to the canvas, but add "blocks" paint information in simple queue, a block would be text, font styles, back & foreground colors.

The blocks queue could then be painted by a routine that would coalesce the FillRect of blocks with common background attributes. It might be possible to coalesce text as well in some cases. For typical lines, this would result in a single FillRect call.

**Comment by bonecode** [comment]
Back in the old days we used to copy a rect from a blank bitmap... it was faster than calling the FillRect. Don't know, if that is valid anymore or ever was. :)

**Comment by bonecode** [comment]
var
  i: Integer;
  T1, T2: TTime;
  LBitmap: TBitmap;
begin
  T1 := Now;
  for i := 0 to 1000000 do
    Canvas.FillRect(ClientRect);
  T2 := Now;
  OutputDebugString(PChar(FormatDateTime('s.zzz', T2 - T1)));
  LBitmap := TBitmap.Create;
  try
    LBitmap.Height := ClientRect.Height;
    LBitmap.Width := ClientRect.Width;
    T1 := Now;
    for i := 0 to 1000000 do
      Canvas.CopyRect(ClientRect, LBitmap.Canvas, ClientRect);
    T2 := Now;
    OutputDebugString(PChar(FormatDateTime('s.zzz', T2 - T1)));
  finally
    LBitmap.Free;
  end;
end;

FillRect took about 48 s and CopyRect 2 s...

**Comment by EricGrange** [comment]
Interesting, this would require to prepare a bitmap for every fill color, but that might be simpler to setup & cache

**Comment by CWBudde** [comment]
I'm not sure if the benchmark you performed is fully satisfying (beyond showing a trend). There are several factors that are left out of this benchmark, but that could probably explain smaller differences.

Anyway, have you also compared this with manual filling (getting the scanline and doing a move/fillchar)? For GR32 several really fast algorithms has been written that could be reused, even without having the editor be based on a TBitmap32. See the GR32_LowLevel unit for ideas.

**Comment by CWBudde** [comment]
Btw. the above code took 1.339 vs 6.424 seconds on my machine (Windows 7 x64, Intel Core2Duo).

**Comment by CWBudde** [comment]
I modified the example now to this:

var
  i: Integer;
  Counter: TJclCounter;
  Time: Extended;
  LBitmap: TBitmap;
begin
  Counter := TJclCounter.Create;
  try
    Counter.Start;
    Canvas.Brush.Color := clRed;
    for i := 0 to 10000 do
      Canvas.FillRect(ClientRect);
    Time := Counter.Stop;
    OutputDebugString(PChar(FloatToStr(Time)));

    LBitmap := TBitmap.Create;
    try
      LBitmap.Height := ClientRect.Height;
      LBitmap.Width := ClientRect.Width;
      LBitmap.Canvas.Brush.Color := clLime;
      LBitmap.Canvas.FillRect(ClientRect);
      Counter.Start;
      for i := 0 to 10000 do
        Canvas.CopyRect(ClientRect, LBitmap.Canvas, ClientRect);
      Time := Counter.Stop;
      OutputDebugString(PChar(FloatToStr(Time)));
    finally
      LBitmap.Free;
    end;
  finally
    Counter.Free;
  end;

With the more accurate JCLCounter I also switched to high performance mode to avoid false readings of the performance counter. Now I get reliable readings for the first method (1.7 seconds) and the second method (6.7 seconds). Despite the different color (red vs. green) the code is about to be the same as in the initial example.
Note: I had to reduce the number of iterations dramatically (factor 100) in order to get computed without the need to minimize the window (resulting in false results).

**Comment by bonecode** [comment]
Hmm, don't know what happened on my computer at work. Now the FillRect is indeed faster. :/

Btw. If you set the brush color before width/height, you don't need to call FillRect. Not documented but so it is.

**Comment by bonecode** [comment]
Back to crime scene and now with your example (changed 10000  to 1000000) I got 80,34 and 120,78. Myth busted. I think I concentrate on other things than optimizing FillRect. :)

**Comment by IC0ffeeCup** [comment]
Hi there, please try to use ExtTextOut from winapi to fill a rect - should be faster at least i used it in my source control.

**Comment by bonecode** [comment]
See https://github.com/bonecode/TBCEditor/blob/master/Source/BCEditor.TextDrawer.pas

It is using Winapi.Windows.ExtTextOut. That's not the issue here.

**Comment by thecupofcoffee** [comment]
No doubt, i just mean that it can replace FillRect.

**Comment by bonecode** [comment]
Partly yes, but not completely. There are parts which are not text.

**Comment by EricGrange** [comment]
On a side note, while replacing with direct bitmap access would likely be faster, it could also reduce performance when used over RDP.

Most FillRect calls just paint small adjacent rects with the same color, and the trouble is not the fill rate, but the WinAPI call overhead. Coalescing smaller FillRects of the same color into bigger ones is very effective.

The deferred renderer itself is very simple/stupid code, the problem is more migrating the paint routines from direct TCanvas & WinApi calls to a deferred renderer, without introducing side-effects (ie. all the calls need to be identified, deferred and handled).

**Comment by bonecode** [comment]
I checked all FillRects and found many places where those were in totally wrong place or unnecessary. PaintCodeFolding was the worst. I will check a few other problem and upload changes.

**Comment by bonecode** [comment]
Fixed.
