### ISSUE TITLE
Arrow selection does not take into account recently typed text

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#74]
In the pascal highligter hello world snippet f.i, go on the line of the "begin", start typing a few characters (do not type enter key or arrows), then do a shift + down to extend the selection downward.

The selection will start at the end of the begin instead of the end of the newly typed text.

Same problem exists if if you delete a few characters with backspace, then extend selection: the selection will start where you started deleting, not where the caret is.

**Comment by bonecode** [comment]
Fixed.
