### ISSUE TITLE
Undo/Redo grouping is not coherent

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#75]
In the default snippet, select the writeln in 

    writeln('Hello, world!');

copy it, then move you caret between the n and the (, and paste twice

    writelnwritelnwriteln('Hello, world!');

now hit ctrl+z, it takes two ctrl+z to remove the two extra writeln (as expected), but if you now do a redo with ctr+shift+z, both writeln will reappear at the same time

**Comment by bonecode** [comment]
Yes, that happens, if the uoGroupUndo in Undo.Options is set.

**Comment by EricGrange** [comment]
Currently uoGroupUndo is more of a uoGroupRedo :)

One solution is to handle the undo grouping at the time of the action, by bundling it into the previous undo entry rather than creating a new one. This way there is a single place in the code where group undo is managed, and the undo/redo methods can be "dumb".

(this requires having entries that are actually chains of entries, for instance by adding a NextItem in TBCEditorUndoItem, and the grouped entries then do not appear as seperate entries in the undo list)

**Comment by bonecode** [comment]
Fixed.
