### ISSUE TITLE
pair matching (?) interferes with selection & paste

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#76]
I do not have a simple reproduceable case, but sometimes the pair matching interferes withe the painting during/after a paste, for instance with in the clipboard

    item.getElementsByTagName('title')

I had a line of code with 

      PrintLn(title[0].text);

when selecting title[0] and pasting I ended up with 

     PrintLn(item.[e]ElementsByTagName('title').text);

displayed in the editor, with the [ ] highlighted (which is why I suspect pair matching, these are the brackets of title[0] before the paste, that somehow got highlighted/painted after the paste)

The buffer is correct, and when doing any operation that triggers a repaint, the display becomes correct again.

**Comment by bonecode** [comment]
Hmm, it was something like that what I fixed but the fix did break other things. The code is still in the comment (line 1381), I will get back to it sooner or later.

**Comment by bonecode** [comment]
I can't repeat this anymore. I call it fixed. :)

**Comment by bonecode** [comment]
Now I got this. :)

**Comment by bonecode** [comment]
Fixed.
