### ISSUE TITLE
DoGetSelectedText should avoid CreateUncollapsedLines when LFirst = LLast

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#78]
Currently it always goes through CreateUncollapsedLines, which can be very slow.

When LFirst=LLast, then uncollapsed lines are not necessary.

If the selection is made over a collapsed line, the the SelectedText is going to be garbage.

As a side note, the region end of a collapsed region should either not be present (as in other editors) not be selectable, or the selected text mechanism should be improved to include the collapsed content (currently it only extends the selection to hidden content of the first line of the region...)

**Comment by bonecode** [comment]
This is a bug. SelectedText should include collapsed lines.

**Comment by EricGrange** [comment]
Might still be worth it to avoid CreateUncollapsedLines when the selection is single-line, and that line is not a collapsed region.

**Comment by bonecode** [comment]
There was an unnecessary call from the search highlighter and that is fixed. But that selection bug is still in my todolist.

**Comment by bonecode** [comment]
SelectedText is fixed.
