### ISSUE TITLE
Do not use MessageDialog directly but virtual methods

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#79]
Currently there is a hard-coded call to CreateMessageDialog and hard-coded Format calls before that call. There should ideally be virtual methods that take care of the message dialog.

https://bitbucket.org/egrange/tbceditorxe/commits/270acc5fe33ccc6094c39296c9e794a3ca7f1e89

Purpose: we use custom message dialogs and custom translation utilities, and pre-formatted message based on a resource-string does not cut it (our translations are DB-based or delivered over http, which is required to allow live updates).

As a bonus it allows deactivating the wraparound dialog without needing an option.

**Comment by bonecode** [comment]
Fixed.
