### ISSUE TITLE
Crash in TBCEditorHighlighter.SetCurrentLine

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#82]
Latest code crashes in TBCEditorHighlighter.SetCurrentLine on the "FCurrentToken.Free;" call.

When running with FastMM full debug mode, the crash is immediate, using BCEditor.Editor.Base as file and the Object Pascal highlighter.

Without FastMM full debug mode, the crash happens "sometimes", when destroying a form that contains the editor.

**Comment by bonecode** [comment]
I haven't noticed this. You may not have all changes.

**Comment by EricGrange** [comment]
It was only 100% reproducible under FastMM full debug mode, it looked like a dangling pointer or something like that (the debugger would barf as well when trying to evaluate FCurrentToken on the FCurrentToken.Free line)

**Comment by bonecode** [comment]
You were right. Fixed.

This doesn't help much :D
  
{$ifdef DEBUG}
  //FastMM4,
{$endif }
