### ISSUE TITLE
Drawing is wrong when selecting a text block

### ISSUE THREAD

**Issue by ngthach** [bonecode/TBCEditor#83]
Modify Colors\Default.js as below:
- SET "SelectionForeground":"clNone"
- Remove BOLD from Method style
- Run Demo project
- Select a block like attachment
![capture](https://cloud.githubusercontent.com/assets/7973218/7774243/0463a604-00d4-11e5-869e-27bde3553572.PNG)

**Comment by bonecode** [comment]
Hmm, I don't get this...

![image](https://cloud.githubusercontent.com/assets/11475177/7787471/694f66be-0216-11e5-8153-0644f1e3e6c8.png)

**Comment by bonecode** [comment]
But I see another problem with the green color. Maybe related...

![image](https://cloud.githubusercontent.com/assets/11475177/7787476/aa90cae6-0216-11e5-88b7-c966ebcb1360.png)

**Comment by ngthach** [comment]
In Monokai.json, line 135

            "Name":"Method",
            "Foreground":"$00EFD966",
            "Background":"$00222827",
            "Style":"Italic" -> remove this line

**Comment by ngthach** [comment]
![capture](https://cloud.githubusercontent.com/assets/7973218/7787756/ea2fa926-0246-11e5-802b-346a1cc43f7a.PNG)

**Comment by bonecode** [comment]
Actually methods are in italic...

![image](https://cloud.githubusercontent.com/assets/11475177/7788309/021e0be4-023e-11e5-99d4-78e97e55096e.png)

**Comment by ngthach** [comment]
I mean: if you want to reproduce my issue, you should remove this line: ""Style":"Italic"

**Comment by bonecode** [comment]
Fixed.
