### ISSUE TITLE
Use CeilOfIntDiv in TBCEditorTextDrawer.GetCharCount

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#86]
...and move CeilOfIntDiv to a utilities unit.

It's being used for the same purpose in ExpandAtWideGlyphs (Editor.Base), and it's more efficient than Ceil(). The Math unit currently shows up in profiling because of Ceil() call, with CeilOfIntDiv, it does not anymore (and neither does CeilOfIntDiv, it's fast enough to be below the radar), it's a very minor speedup, but it also unifies the way it's computed.

**Comment by bonecode** [comment]
Fixed.
