### ISSUE TITLE
Leverage CharWidth cache more

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#87]
After the FillRect optimization -- well done :) -- the gdi32.dll CPU usage breaks down basically in thirds:
- 1/3 for FillRect
- 1/3 for GetTextSize
- 1/3 for AdjustRect/GetCharABCWidthsW stuff

A lot (all?) of the GetTextSize calls are actually just asking for the width of a single character repeatedly, even AdjustEndRect does it, so maybe 40% or more of the gdi32.dll CPU usage consist in asking for the same char widths repeatedly.

There is a CharWidth cache in TBCEditorTextDrawer, but it's not used everywhere, it might be worthwile to use it everywhere and/or move it to its own class (so it can be used everywhere).

To catch all occurences, a way would be to deprecate all the current TextWidth/TextSize/TextExtent routines (and other variations), and unify to just a couple routines: one for character widths, one for string widths, this would also allow to merge the CharWidth cache with the ABCWidth one.

**Comment by bonecode** [comment]
Aah, thanks for pointing that out, I will check those calls carefully asap.

**Comment by bonecode** [comment]
GetCharCount is now fixed. I will check other calls little later.

**Comment by bonecode** [comment]
AdjustLastCharWidthAndRect is fixed. What do you get now?

**Comment by EricGrange** [comment]
Updated profiling for gdi32.dll calls:

![image](https://cloud.githubusercontent.com/assets/2197210/7953609/3e7953ec-09c7-11e5-9d48-e53276f58e75.png)

So the calls to get char width are basically down to 15%, and could be reduced by improving the ABCWidth cache to track more than one font style.

FillRect is back to being the bottleneck, from PaintLines calls.

Overall gdi32.dll call represents 60% of the time spent, the rest is on the Delphi side:
- PaintGuides
- GetUncollapsedLineNumbersDifference
- TBCEditorHighlighter.GetToken through its String memory allocation/deallocations and conversion from PChar to String
- GetAllFoldRange (given its code is simple and it shows up in the sampling profiler, it must be called an inordinate amount of times)

(opened a separate issue for GetAllFoldRange calls, there are some anti-patterns at work, and more than performance to gain)

**Comment by bonecode** [comment]
I fixed those GetAllFoldRange calls.

**Comment by bonecode** [comment]
I close this, a lot of fixes done. GetUncollapsedLineNumbersDifference has its own issue.
