### ISSUE TITLE
Minimize calls to GetAllFoldRange

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#88]
It shows up the profiler despite being a really simple function, in part because there are some anti-patterns at work when invoking the AllCodeFoldingRanges[] indexed property.

The anti-patterns basically boil down to the lack of a local variable, for instance in TBCBaseEditor.CreateUncollapsedLines the function is invoked repeatedly and makes the code look more complicated than it is. Simply adding a 

    range := FAllCodeFoldingRanges[j];

and then using 'range' in the rest of the code would fix both performance and readability.

Another common anti-pattern is use of the form

    for i := 0 to FAllCodeFoldingRanges.AllCount - 1 do
    with FAllCodeFoldingRanges[i] do

which besides the "with" usually also has code inside the loop that does invoke FAllCodeFoldingRanges[i] again.

Using a local variable would solve both the "with" and the repeated calls. In the cases where the index is not used, a "for in" might further help readability.

In the case of TBCBaseEditor.GetUncollapsedLineNumberDifference, which at the moment is on the critical performance path, using something else than a loop might be preferable (a lookup table maybe, or an index)

**Comment by bonecode** [comment]
Fixed. I made a new issue about that GetUncollapsedLineNumberDifference. I thought I had a solution for it but this is not as easy as it looks.
