### ISSUE TITLE
Highlight similar terms highlights partial matches, and is sensitive to selection direction

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#89]
On the following code line

      Assert(False, a[1]);

If you select the 'a' from 'a[1]' it will highlight the A in Assert and the a in False, while it should not.

Also if you select the same 'a' from 'a[1]' with a right-to-left selection (by moving the mouse to the left, or using shift+left on the keyboard), then nothing is highlighted.

**Comment by bonecode** [comment]
Fixed.
