### ISSUE TITLE
Selection bug after typing a character beyond end of line

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#90]
Position caret several blanks after the last character of a line (with mouse or cursor), then type 'a', then do a shift+left, this will select the blanks between the previous end of the line and 'a', rather than 'a'.

If you click or use the arrows before selecting, the bug is not triggered.

**Comment by EricGrange** [comment]
Might be a duplicate of Issue #74

**Comment by bonecode** [comment]
Fixed.
