### ISSUE TITLE
Access Violation when clicking on the TBCEditor component

### ISSUE THREAD

**Issue by stephanewierzbicki** [bonecode/TBCEditor#93]
I'm having Access Violation when clicking on the TBCEditor component.
Steps to reproduce this are quite simple :
- create an empty VCL application
- drop a TBCeditor
- compile and run
- at runtime, click on the TBCEditor

Act: an access violation is raised
Expt: no access viiolation ?

**Comment by bonecode** [comment]
Fixed.
