### ISSUE TITLE
Low framerate since last commits

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#95]
Not sure exactly why, but the framerate took a nosedive in the last commits, Paint calls last between 16 and 120 ms, and in some cases (scrolling and selection in BCEditor.Editor.Base), the painting is slow enough to be visible on screen.

Profiler shows a notable increase in memory allocation, notable spots are TBCEditorHighlighter.GetToken, InitExtTextOutDistance, and TBCEditorTextDrawer.GetCharCount.

For InitExtTextOutDistance the problem is that the FExtTextOutDistance is dumped each time the font changes (which is often with an highlighter), AFAICT it could be kept around between calls, and only grown to be large enough (also an "array of integer" should work just fine there)

For TBCEditorTextDrawer.GetCharCount the problem is that call to TextWidth, which takes a String but is passed a Char, so there is an allocation/destruction of a single-character string each time.

As this is a problem that is bound to come back, ideal would be to deprecate all current Text/Char width strings, and introduce two new ones, which would take a Char and a String, give them different names and use a deprecated overload as canary to catch implicit conversions.

Something like

    function NewCharWidth(c : Char) : Integer;

    function NewTextWidth(const s : String) : Integer; overload;
    function NewTextWidth(c : Char) : Integer; overload; deprecated "uh oh";

**Comment by bonecode** [comment]
Hmm, maybe I should get an old and very slow computer with poor graphic card because I never notice anything. :D I might have done something stupid...

**Comment by EricGrange** [comment]
You don't need a slow computer or poor graphic card, though if you have a slow screen or a small laptop screen, that may hide the issue.

Just open BCEditor.Editor.Base with minimap & code folding active, Pascal highlighter, scroll near the bottom of the file, make the editor large enough (at least 1000x700), then scroll up/down with the mouse wheel or select most of the visible content with the mouse.

You can also add a basic timer around the Paint call, ideally you should be below 30 msec (30 FPS) at all times, whenever it gets above that, it will feel laggy will be visible, whenever it gets above 100 msec, the incremental paint will be visible to the eye.

**Comment by EricGrange** [comment]
Also you can always run with FastMM Full Debug Mode, besides catching various issues, this has the effect of slowing down memory management, which makes memory management issues more prominent.

**Comment by bonecode** [comment]
Yes, I am rolling minimap in full hd and also profiling occasionally... I close this issue, those ExtTextOutDistance and GetCharCount issues are fixed.
