### ISSUE TITLE
Highlighters with sub-highlighters questions... many questions :)

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#98]
I tweaked the Object Pascal editor for DWScript, this works all right on its own
https://bitbucket.org/egrange/tbceditorxe/src/e4583b8f03d7bf823a0051e3461ccf02671224b3/Highlighters/DWScript.json?at=master

Now I'm trying to adapt it to the "HTML with scripts"
https://bitbucket.org/egrange/tbceditorxe/src/e4583b8f03d7bf823a0051e3461ccf02671224b3/Highlighters/HTML%20with%20DWScript.json?at=master

Basically I want the <?pas & ?> markers to indicate a section that should use the DWScript.json, but that does not seem to work for some reason. Any idea what's wrong or what's the best way to debug this? 

In addition I will eventually want <script type="pascal"> to be highlighted with DWScript.json, but other <script to stay with JavaScript.json, is the priority determined by the order?

Is there a way for a section to have a background color depending on the active the rule? f.i. when the caret is in the HTML, the HTML should have a white background, and the DWScript section a gray background, but when the caret is in a DWScript section, then it should have a white background, and the HTML a gray one (and ofc it could be richer than that to differentiate HTML/CSS/JS sections by background when the caret is not in them)

Also for the html with scripts, I noticed that CSS sections for instance are not highlighted correctly the first time the editor is painted, but the folding for a CSS class is present. If you collapse/expand a CSS class, then it's highlighted correctly.

**Comment by EricGrange** [comment]
Sample code to be highlighted

<html>
<body>

<style>
p {
   color: #12345;
   coolor: "gheg";
}
</style>

<?pas
if True then begin
   PrintLn('hello');
end;
?>

if True then begin  // this is not pascal but html text
   PrintLn('hello');
end;

<script type="pascal">
if True then begin
   PrintLn('hello');
end;
</script>

<script>
if (1==1) {
   var v = "ghgh";
}
</script>

</body>
</html>

**Comment by bonecode** [comment]
You need to add a name for the range you want to include. Add this to your DWScript.json:

<pre>
...
"MainRules":{
         "Name": "DWScript",
...
</pre>

**Comment by EricGrange** [comment]
Thanks, highlighting now works, but however code folding does not, only the CSS is showing fold regions, any idea?

Also any way to control background color of an highlighter based on the highlighter where the caret currently is?

**Comment by bonecode** [comment]
Yes, too many ideas and too little time. Currently only range is included. Maybe there should be something like:

<pre>
"FoldRegion":[
         {
            "File":"DWScript.json"
         },
</pre>

Now you need to add the fold regions also into HTML with DWScript.json file.

**Comment by bonecode** [comment]
Fixed. Now you can include other highlighter files in SkipRegion, FoldRegion, MatchingPair, and CompletionProposal. See HTML with Scripts.json for example.
